/* eslint-disable */
// Auto-generated by scripts/sync-events.ts from the Google Sheets August Events tab. Do not edit by hand.
import type { PrideEvent } from '../../types/event';

export const generatedEvents: PrideEvent[] = [
  {
    "id": "5",
    "festival": "august-events",
    "day": "monday",
    "dayDate": "2026-08-17",
    "dayLabel": "Monday",
    "name": "Virtual Intuitive Movement: A Grounding & Embodiment Experience with Dr. Udim Isang",
    "organizer": "Lesbifriends Travel",
    "types": [
      "workshop",
      "meetup"
    ],
    "vibesRaw": "wellness chill",
    "free": false,
    "price": "Donation-based, starts at $5 (no maximum)",
    "badges": [
      "Workshop",
      "Meetup"
    ],
    "time": "7:30 PM",
    "location": "N/A (virtual event)",
    "vibeTags": [
      "Wellness",
      "Chill"
    ],
    "ctaHref": "https://www.lesbifriendstravel.com/events/virtual-intuitive-movement",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-workshop",
    "city": "dc"
  },
  {
    "id": "6",
    "festival": "august-events",
    "day": "sunday",
    "dayDate": "2026-08-16",
    "dayLabel": "Sunday",
    "name": "Lesbifriends in the Park 2.0",
    "organizer": "Lesbifriends Travel",
    "types": [
      "outdoors-hangout",
      "meetup"
    ],
    "vibesRaw": "chill community groove family",
    "free": true,
    "price": "Free (suggested $10 donation)",
    "badges": [
      "Outdoors Hangout",
      "Meetup",
      "Free"
    ],
    "time": "12:00 PM",
    "location": "Rock Creek Park · Washington, DC (exact site withheld pre-event for attendee privacy -- not a data gap)",
    "vibeTags": [
      "Chill",
      "Community",
      "Groove",
      "Family"
    ],
    "ctaHref": "https://www.lesbifriendstravel.com/events/lbf-in-the-park-2",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-outdoors-hangout",
    "city": "dc"
  },
  {
    "id": "8",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-01",
    "dayLabel": "Saturday",
    "name": "Ethernet Ft Madness Of",
    "organizer": "Transmission",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove",
    "free": false,
    "price": "$20",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "TRANSMISSION · 1353 H Street Northeast, Washington, DC 20002",
    "vibeTags": [
      "Ass Shaking",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/ethernet-2",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "9",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-01",
    "dayLabel": "Saturday",
    "name": "Boardwalk Bounce Pres By Caribbeanmills X Jam2x",
    "organizer": "Transmission",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove",
    "free": false,
    "price": "$15",
    "badges": [
      "After Dark"
    ],
    "time": "11:00 PM",
    "location": "TRANSMISSION · 1353 H Street Northeast, Washington, DC 20002",
    "vibeTags": [
      "Ass Shaking",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/boardwalk-bounce-pres-by-caribbean-mills-x-jam-2-x",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "10",
    "festival": "august-events",
    "day": "thursday",
    "dayDate": "2026-08-06",
    "dayLabel": "Thursday",
    "name": "Bloodlust Ft DJ Re:Code",
    "organizer": "Transmission",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove",
    "free": false,
    "price": "$20",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "TRANSMISSION · 1353 H Street Northeast, Washington, DC 20002",
    "vibeTags": [
      "Ass Shaking",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/bloodlust-vampire-club-night",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "11",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-07",
    "dayLabel": "Friday",
    "name": "Kink N' Draw At Transmission",
    "organizer": "Transmission",
    "types": [
      "live-show",
      "workshop"
    ],
    "vibesRaw": "creative flirt live show groove kink",
    "free": false,
    "price": "$30",
    "badges": [
      "Live Show",
      "Workshop"
    ],
    "time": "6:00 PM",
    "location": "TRANSMISSION · 1353 H Street Northeast, Washington, DC 20002",
    "vibeTags": [
      "Creative",
      "Flirt",
      "Live Show",
      "Groove",
      "Kink"
    ],
    "ctaHref": "https://shotgun.live/en/events/kink-n-draw--aug7",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-live-show",
    "city": "dc"
  },
  {
    "id": "12",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-07",
    "dayLabel": "Friday",
    "name": "Armana Khan Residency 001",
    "organizer": "Transmission",
    "types": [
      "after-dark",
      "live-show"
    ],
    "vibesRaw": "ass shaking groove community flirt",
    "free": false,
    "price": "$30",
    "badges": [
      "After Dark",
      "Live Show"
    ],
    "time": "10:00 PM",
    "location": "TRANSMISSION · 1353 H Street Northeast, Washington, DC 20002",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Community",
      "Flirt"
    ],
    "ctaHref": "https://shotgun.live/en/events/armana-khan-residency001",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "13",
    "festival": "august-events",
    "day": "thursday",
    "dayDate": "2026-08-13",
    "dayLabel": "Thursday",
    "name": "Substrate Pres. Moktar",
    "organizer": "Transmission",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove community flirt",
    "free": false,
    "price": "$20",
    "badges": [
      "After Dark"
    ],
    "time": "9:00 PM",
    "location": "TRANSMISSION · 1353 H Street Northeast, Washington, DC 20002",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Community",
      "Flirt"
    ],
    "ctaHref": "https://shotgun.live/en/events/substrate-pres-moktar",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "14",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-14",
    "dayLabel": "Friday",
    "name": "Les Play House Tour",
    "organizer": "Transmission",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove community flirt",
    "free": false,
    "price": "$20",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "TRANSMISSION · 1353 H Street Northeast, Washington, DC 20002",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Community",
      "Flirt"
    ],
    "ctaHref": "https://shotgun.live/en/events/les-play-house-2026-tour",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "15",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-15",
    "dayLabel": "Saturday",
    "name": "Möya Afro House Experience: G-Wash10",
    "organizer": "Transmission",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove community flirt",
    "free": false,
    "price": "$20",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "TRANSMISSION · 1353 H Street Northeast, Washington, DC 20002",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Community",
      "Flirt"
    ],
    "ctaHref": "https://shotgun.live/en/events/moya-afro-house-experience-g-wash-10",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "16",
    "festival": "august-events",
    "day": "thursday",
    "dayDate": "2026-08-20",
    "dayLabel": "Thursday",
    "name": "Substrate Pres. DJ Stingray 313",
    "organizer": "Transmission",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove community flirt",
    "free": false,
    "price": "$20",
    "badges": [
      "After Dark"
    ],
    "time": "9:00 PM",
    "location": "TRANSMISSION · 1353 H Street Northeast, Washington, DC 20002",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Community",
      "Flirt"
    ],
    "ctaHref": "https://shotgun.live/en/events/substrate-pres-313",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "17",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-21",
    "dayLabel": "Friday",
    "name": "Baile World",
    "organizer": "Transmission",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove community flirt",
    "free": false,
    "price": "$20",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "TRANSMISSION · 1353 H Street Northeast, Washington, DC 20002",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Community",
      "Flirt"
    ],
    "ctaHref": "https://shotgun.live/en/events/baile-world",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "18",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-22",
    "dayLabel": "Saturday",
    "name": "Thot Daughter Tour: Archangel, Bbymutha, DJ Haram, & Sha Ray",
    "organizer": "Transmission",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove community flirt",
    "free": false,
    "price": "$30",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "TRANSMISSION · 1353 H Street Northeast, Washington, DC 20002",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Community",
      "Flirt"
    ],
    "ctaHref": "https://shotgun.live/en/events/thot-daughter-tour-archangel-bby-mutha-dj-haram-sha-ray",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "19",
    "festival": "august-events",
    "day": "wednesday",
    "dayDate": "2026-08-19",
    "dayLabel": "Wednesday",
    "name": "Sapphic Social: Summer Edition",
    "organizer": "QueerTalk",
    "types": [
      "happy-hour",
      "meetup"
    ],
    "vibesRaw": "chill flirt community",
    "free": false,
    "price": "$12",
    "badges": [
      "Happy Hour",
      "Meetup"
    ],
    "time": "6:00 PM",
    "location": "Spark Social Patio · 2009 14th St NW, Washington, DC 20009, USA",
    "vibeTags": [
      "Chill",
      "Flirt",
      "Community"
    ],
    "ctaHref": "https://posh.vip/e/sapphic-social-summer-edition?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnedrpzcKVQo_eE3MGszk84HqrS2cJimzoblnQnzus8rj6Kq4ox6s0qX0rV2s_aem_OlYz8Hi3mUL--5VupDMJUw",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-happy-hour",
    "city": "dc"
  },
  {
    "id": "20",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-29",
    "dayLabel": "Saturday",
    "name": "Verify manually",
    "organizer": "QueerTalk",
    "types": [
      "brunch",
      "meetup"
    ],
    "vibesRaw": "flirt community food cultural",
    "free": false,
    "price": "$70",
    "badges": [
      "Brunch",
      "Meetup"
    ],
    "time": "10:30 AM",
    "location": "Washington Union Station - Main Entrance · 40 Massachusetts Avenue Northeast\nWashington, DC 20002",
    "vibeTags": [
      "Flirt",
      "Community",
      "Food",
      "Cultural"
    ],
    "ctaHref": "https://www.eventbrite.com/e/dykes-uncorked-sapphic-virginia-tour-tickets-1995700422687",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-brunch",
    "city": "dc"
  },
  {
    "id": "21",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-22",
    "dayLabel": "Saturday",
    "name": "BLxGL Anime NYC Afterparty (Yuri Yaoi Cosplay Party)",
    "organizer": "Dykemint",
    "types": [
      "workshop",
      "after-dark",
      "live-show"
    ],
    "vibesRaw": "creative community live show flirt groove",
    "free": false,
    "price": "GA Online $10 / At the Door $20",
    "badges": [
      "Workshop",
      "After Dark",
      "Live Show"
    ],
    "time": "8:00 PM",
    "location": "SPIN Times Square · 1626 Broadway, New York, NY 10019",
    "vibeTags": [
      "Creative",
      "Community",
      "Live Show",
      "Flirt",
      "Groove"
    ],
    "ctaHref": "https://sonicboombox.com/events/anyc-yuri-yaoi-dykemint-party/sbb/",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-workshop",
    "city": "nyc"
  },
  {
    "id": "22",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-08",
    "dayLabel": "Saturday",
    "name": "Planet Rooted: Rooted Festival 2026",
    "organizer": "Rooted Collective",
    "types": [
      "meetup",
      "workshop",
      "educational"
    ],
    "vibesRaw": "creative community games groove",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Workshop",
      "Educational",
      "Free"
    ],
    "time": "10:30 AM",
    "location": "Patterson Park (Pavilion 2) · 2601 East Baltimore Street, Baltimore, MD 21224",
    "vibeTags": [
      "Creative",
      "Community",
      "Games",
      "Groove"
    ],
    "ctaHref": "https://www.eventbrite.com/e/planet-rooted-rooted-festival-2026-tickets-1993340398792",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "city": "baltimore"
  },
  {
    "id": "23",
    "festival": "august-events",
    "day": "thursday",
    "dayDate": "2026-08-13",
    "dayLabel": "Thursday",
    "name": "Black Folx Book Club Sunset Cruise and Book Swap!",
    "organizer": "Greedy Reads",
    "types": [
      "meetup",
      "outdoors-hangout",
      "educational"
    ],
    "vibesRaw": "chill creative community",
    "free": false,
    "price": "$50",
    "badges": [
      "Meetup",
      "Outdoors Hangout",
      "Educational"
    ],
    "time": "7:00 PM",
    "location": "Baltimore Water Taxi · 901 South Broadway, Baltimore, MD 21231",
    "vibeTags": [
      "Chill",
      "Creative",
      "Community"
    ],
    "ctaHref": "https://www.eventbrite.com/e/black-folx-book-club-sunset-cruise-and-book-swap-tickets-1990343237201",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "city": "baltimore"
  },
  {
    "id": "24",
    "festival": "august-events",
    "day": "tuesday",
    "dayDate": "2026-08-04",
    "dayLabel": "Tuesday",
    "name": "Expand the Canon Book Club: \"Their Eyes Were Watching God\"",
    "organizer": "Greedy Reads",
    "types": [
      "meetup",
      "educational"
    ],
    "vibesRaw": "chill creative community",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Educational",
      "Free"
    ],
    "time": "7:00 PM",
    "location": "Greedy Reads Remington · 320 West 29th Street, Baltimore, MD 21211",
    "vibeTags": [
      "Chill",
      "Creative",
      "Community"
    ],
    "ctaHref": "https://www.eventbrite.com/e/expand-the-canon-book-club-their-eyes-were-watching-god-tickets-1990182788294",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "city": "baltimore"
  },
  {
    "id": "25",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-08",
    "dayLabel": "Saturday",
    "name": "Yoga with Indie and Lez Black Gurls Presents: Community Yoga",
    "organizer": "Yoga with Indie x Lez Black Gurls (confirmed collab)",
    "types": [
      "workshop",
      "educational"
    ],
    "vibesRaw": "chill creative community wellness",
    "free": false,
    "price": "$13",
    "badges": [
      "Workshop",
      "Educational"
    ],
    "time": "10:30 AM",
    "location": "The Pride Center of Maryland · 2418 Saint Paul Street, Baltimore, MD 21218",
    "vibeTags": [
      "Chill",
      "Creative",
      "Community",
      "Wellness"
    ],
    "ctaHref": "https://www.eventbrite.com/e/yoga-with-indie-and-lez-black-gurls-presents-community-yoga-registration-1994399568798",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-workshop",
    "city": "baltimore"
  },
  {
    "id": "26",
    "festival": "august-events",
    "day": "sunday",
    "dayDate": "2026-08-30",
    "dayLabel": "Sunday",
    "name": "Raw Honey: Rooftop Party",
    "organizer": "Raw Honey",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove community flirt",
    "free": false,
    "price": "$13.91",
    "badges": [
      "After Dark"
    ],
    "time": "5:00 PM",
    "location": "The Sultan Room Rooftop · 234 Starr St, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Community",
      "Flirt"
    ],
    "ctaHref": "https://dice.fm/event/dkd9og-raw-honey-30th-aug-the-sultan-room-rooftop-brooklyn-tickets",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "28",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-14",
    "dayLabel": "Friday",
    "name": "Out N Bad x SheShed DC x Sapphic JA: THE CROSSOVER (Twerk vs Bashment)",
    "organizer": "She Shed",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove community flirt",
    "free": false,
    "price": "$18",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "The House · 29 Locust St, Brooklyn, NY 11206, USA",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Community",
      "Flirt"
    ],
    "ctaHref": "https://posh.vip/e/out-n-bad-x-sapphic-ja-x-sheshed-dc-presents-the-crossover-twerk-vs-bashment",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "29",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-15",
    "dayLabel": "Saturday",
    "name": "Zestyworld: The Collective Weekend",
    "organizer": "Zesty World",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove community flirt",
    "free": false,
    "price": "$19",
    "badges": [
      "After Dark"
    ],
    "time": "11:00 PM",
    "location": "Putnam's Pub & Cooker · 419 Myrtle Avenue, Brooklyn, NY 11205",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Community",
      "Flirt"
    ],
    "ctaHref": "https://posh.vip/e/nyc-zestyworld-the-collective-weekend",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "31",
    "festival": "august-events",
    "day": "wednesday",
    "dayDate": "2026-08-05",
    "dayLabel": "Wednesday",
    "name": "LADIES LOVE R&B ❤️",
    "organizer": "MIM Entertainment",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove community flirt",
    "free": true,
    "price": "Free",
    "badges": [
      "After Dark",
      "Free"
    ],
    "time": "9:00 PM",
    "location": "SAINT-EX · 1847 14th St NW, Washington, DC 20009, USA",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Community",
      "Flirt"
    ],
    "ctaHref": "https://posh.vip/e/ladies-love-rb--21",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "32",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-08",
    "dayLabel": "Saturday",
    "name": "Verify manually",
    "organizer": "Big Kids Club DMV",
    "types": [
      "meetup",
      "outdoors-hangout",
      "workshop"
    ],
    "vibesRaw": "chill creative community wellness",
    "free": false,
    "price": "$6",
    "badges": [
      "Meetup",
      "Outdoors Hangout",
      "Workshop"
    ],
    "time": "9:00 AM",
    "location": "Rock Creek Park Nature Center and Planetarium · 5200 Glover Rd NW, Washington, DC 20015, USA",
    "vibeTags": [
      "Chill",
      "Creative",
      "Community",
      "Wellness"
    ],
    "ctaHref": "https://posh.vip/e/muse-hike",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "city": "dc"
  },
  {
    "id": "33",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-15",
    "dayLabel": "Saturday",
    "name": "Verify manually",
    "organizer": "Big Kids Club DMV",
    "types": [
      "meetup",
      "outdoors-hangout"
    ],
    "vibesRaw": "chill creative community wellness",
    "free": false,
    "price": "$6",
    "badges": [
      "Meetup",
      "Outdoors Hangout"
    ],
    "time": "9:00 AM",
    "location": "Rock Creek Park Nature Center and Planetarium · 5200 Glover Rd NW, Washington, DC 20015, USA",
    "vibeTags": [
      "Chill",
      "Creative",
      "Community",
      "Wellness"
    ],
    "ctaHref": "https://posh.vip/e/hang-n-hike-masc-edition",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "city": "dc"
  },
  {
    "id": "34",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-08",
    "dayLabel": "Saturday",
    "name": "MAMACITA FESTIVAL 2026 (2nd Edition)",
    "organizer": "TASTE TAKEOVER",
    "types": [
      "day-party",
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community grown & sexy groove live show",
    "free": false,
    "price": "$29",
    "badges": [
      "Day Party",
      "After Dark"
    ],
    "time": "4:00 PM",
    "location": "Hook Hall · 3400 Georgia Avenue Northwest, Washington, DC 20010",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Grown & Sexy",
      "Groove",
      "Live Show"
    ],
    "ctaHref": "https://www.eventbrite.com/e/mamacita-festival-tickets-1987149247893",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "dc"
  },
  {
    "id": "35",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-15",
    "dayLabel": "Saturday",
    "name": "Sapphic After Dark",
    "organizer": "Sapphic Social DC",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community grown & sexy groove",
    "free": false,
    "price": "$10",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "Mixxed DC · 2427 18th St NW, Washington, DC 20009, USA",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/sapphic-after-dark",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "36",
    "festival": "august-events",
    "day": "sunday",
    "dayDate": "2026-08-23",
    "dayLabel": "Sunday",
    "name": "H.A.G.S",
    "organizer": "Alphabet Soup",
    "types": [
      "day-party"
    ],
    "vibesRaw": "ass shaking flirt community grown & sexy groove live show",
    "free": false,
    "price": "$10",
    "badges": [
      "Day Party"
    ],
    "time": "12:00 PM",
    "location": "Wunder Garten · 1101 1st St NE, Washington, DC 20002, USA",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Grown & Sexy",
      "Groove",
      "Live Show"
    ],
    "ctaHref": "https://posh.vip/e/hags-1",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "dc"
  },
  {
    "id": "37",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-14",
    "dayLabel": "Friday",
    "name": "Hashtag 2016",
    "organizer": "Alphabet Soup",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$10",
    "badges": [
      "After Dark"
    ],
    "time": "11:00 PM",
    "location": "DC9 · 1940 9th St NW\nWashington, DC 20001",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://dc9.club/event/hashtag-2016/",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "38",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-22",
    "dayLabel": "Saturday",
    "name": "Motorboat: A sunset rooftop pool party",
    "organizer": "Alphabet Soup",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$18",
    "badges": [
      "After Dark"
    ],
    "time": "5:00 PM",
    "location": "Tag Rooftop Bar at The Ven at Embassy Row · 2015 Massachusetts Ave NW, Washington, DC 20036, USA",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/motorboat-a-sunset-rooftop-pool-party?u=mp3f1les&_t=msdhjwro&os=web&src=event_page",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "39",
    "festival": "august-events",
    "day": "sunday",
    "dayDate": "2026-08-30",
    "dayLabel": "Sunday",
    "name": "Motorboat: A daytime rooftop pool party",
    "organizer": "Alphabet Soup",
    "types": [
      "day-party"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$18",
    "badges": [
      "Day Party"
    ],
    "time": "2:00 PM",
    "location": "Tag Rooftop Bar at The Ven at Embassy Row · 2015 Massachusetts Ave NW, Washington, DC 20036, USA",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/motorboat-a-sunset-rooftop-pool-party-1?u=mp3f1les&_t=msdhr0it&os=web&src=event_page",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "dc"
  },
  {
    "id": "40",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-07",
    "dayLabel": "Friday",
    "name": "Dirty Circus: Hot & Bothered",
    "organizer": "House of Yes",
    "types": [
      "day-party",
      "happy-hour"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$47.25+",
    "badges": [
      "Day Party",
      "Happy Hour"
    ],
    "time": "6:30 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/dirty-circus-variety-show-august-7-2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "nyc"
  },
  {
    "id": "41",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-07",
    "dayLabel": "Friday",
    "name": "House Of Grooves: Stretch Armstrong + Sissies Of Mercy",
    "organizer": "House of Yes",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$11.00+",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/house-of-grooves-august-7-2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "42",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-07",
    "dayLabel": "Friday",
    "name": "Inner Sin: Mandrake + Maayan Nidam",
    "organizer": "House of Yes",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$16.00+",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "The Onyx Room · 8 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/inner-sin-aug-7-2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "43",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-08",
    "dayLabel": "Saturday",
    "name": "Dirty Circus: Hot & Bothered",
    "organizer": "House of Yes",
    "types": [
      "day-party",
      "happy-hour"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$52.50+",
    "badges": [
      "Day Party",
      "Happy Hour"
    ],
    "time": "6:30 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/dirty-circus-hot-bothered-august-8-2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "nyc"
  },
  {
    "id": "44",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-08",
    "dayLabel": "Saturday",
    "name": "Festival Dominicano: Mundo + Brian Cid Presents Ladobé",
    "organizer": "House of Yes",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$22.05+",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/festival-dominicano-august-8-2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "45",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-14",
    "dayLabel": "Friday",
    "name": "Dirty Circus: Hot & Bothered",
    "organizer": "House of Yes",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "price": "$36.75+",
    "badges": [],
    "time": "6:30 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [],
    "ctaHref": "https://shotgun.live/en/events/dirty-circus-hot-bothered-august-14-2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "nyc"
  },
  {
    "id": "46",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-14",
    "dayLabel": "Friday",
    "name": "Futch",
    "organizer": "House of Yes",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$11.00-$20.00 (door)",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/futch-august-14-2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "47",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-15",
    "dayLabel": "Saturday",
    "name": "Dirty Circus: Hot & Bothered",
    "organizer": "House of Yes",
    "types": [
      "day-party",
      "happy-hour"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$42.00+",
    "badges": [
      "Day Party",
      "Happy Hour"
    ],
    "time": "6:30 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/dirty-circus-hot-bothered-august-15-2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "nyc"
  },
  {
    "id": "48",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-15",
    "dayLabel": "Saturday",
    "name": "Heat Wave: Egyptian Lover, Stacey Hotwaxx Hale, Bridge",
    "organizer": "House of Yes",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$43.31+",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/egyptian-lover-august-15-2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "49",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-15",
    "dayLabel": "Saturday",
    "name": "Rosa Perreo At The Onyx Room",
    "organizer": "House of Yes",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$11.00+",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "The Onyx Room · 8 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/rosa-perreo-august-15-at-the-house-of-yes-onyx-room",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "50",
    "festival": "august-events",
    "day": "thursday",
    "dayDate": "2026-08-20",
    "dayLabel": "Thursday",
    "name": "Hot & Fresh · Burlesque",
    "organizer": "House of Yes",
    "types": [
      "day-party",
      "happy-hour"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": true,
    "price": "Free RSVP / $11 Donation / $47.25 Priority",
    "badges": [
      "Day Party",
      "Happy Hour",
      "Free"
    ],
    "time": "6:30 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/hot-and-fresh-burlesque-aug-20-2026",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-day-party",
    "city": "nyc"
  },
  {
    "id": "51",
    "festival": "august-events",
    "day": "thursday",
    "dayDate": "2026-08-20",
    "dayLabel": "Thursday",
    "name": "Gasolina With Ultra Violet",
    "organizer": "House of Yes",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": true,
    "price": "Free RSVP / $11.00",
    "badges": [
      "After Dark",
      "Free"
    ],
    "time": "10:00 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/gasolina-aug20",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "52",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-21",
    "dayLabel": "Friday",
    "name": "Dirty Circus: Variety Show",
    "organizer": "House of Yes",
    "types": [
      "day-party",
      "happy-hour"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$36.75+",
    "badges": [
      "Day Party",
      "Happy Hour"
    ],
    "time": "6:30 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/dirty-circus-variety-show-august-21-2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "nyc"
  },
  {
    "id": "53",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-21",
    "dayLabel": "Friday",
    "name": "Leo Rising: Kyle Hall, Shaun J. Wright, Tee Em Dee",
    "organizer": "House of Yes",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$0-$22.05",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/leo-rising-august-21-2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "54",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-22",
    "dayLabel": "Saturday",
    "name": "Dirty Circus: Variety Show",
    "organizer": "House of Yes",
    "types": [
      "day-party",
      "happy-hour"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$42.00+",
    "badges": [
      "Day Party",
      "Happy Hour"
    ],
    "time": "6:30 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/dirty-circus-variety-show-august-22-2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "nyc"
  },
  {
    "id": "55",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-22",
    "dayLabel": "Saturday",
    "name": "Full Throttle: Township Rebellion",
    "organizer": "House of Yes",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$19.50-$27.30",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/august-22-2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "56",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-22",
    "dayLabel": "Saturday",
    "name": "She.They.Dj: Mangumami, Bossy Boots And More! (5 year anniversary)",
    "organizer": "House of Yes",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$11.00+",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "The Onyx Room · 8 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/she-they-dj-aug-22-2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "57",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-28",
    "dayLabel": "Friday",
    "name": "Dirty Circus: Variety Show",
    "organizer": "House of Yes",
    "types": [
      "day-party",
      "happy-hour"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$36.75+",
    "badges": [
      "Day Party",
      "Happy Hour"
    ],
    "time": "6:30 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/dirty-circus-variety-show-august-28-2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "nyc"
  },
  {
    "id": "58",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-28",
    "dayLabel": "Friday",
    "name": "Slayyyland: Cam Girl, Vice, P_A_T",
    "organizer": "House of Yes",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$0-$16.00",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/slayyyland-2",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "59",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-29",
    "dayLabel": "Saturday",
    "name": "Dirty Circus: Variety Show",
    "organizer": "House of Yes",
    "types": [
      "day-party",
      "happy-hour"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$42.00+",
    "badges": [
      "Day Party",
      "Happy Hour"
    ],
    "time": "6:30 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/dirty-circus-variety-show-august-29-2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "nyc"
  },
  {
    "id": "60",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-29",
    "dayLabel": "Saturday",
    "name": "Abc Party: Sponges & N2n",
    "organizer": "House of Yes",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$16.00+",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/abcparty-sponges-n2n-august292026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "61",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-14",
    "dayLabel": "Friday",
    "name": "Out N Bad x SheShed DC x Sapphic JA: THE CROSSOVER (Twerk vs Bashment) -- confirms/updates the She Shed row",
    "organizer": "Out N Bad",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": false,
    "price": "$18",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "The House · 29 Locust St, Brooklyn, NY 11206, USA",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://www.outnbad.com/events",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "62",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-14",
    "dayLabel": "Friday",
    "name": "All Gays Go To Heaven (per ticket-link URL slug, unconfirmed -- dice.fm page could not be fetched)",
    "organizer": "ggg.nyc",
    "types": [
      "day-party"
    ],
    "vibesRaw": "ass shaking flirt community groove",
    "free": true,
    "price": "Free",
    "badges": [
      "Day Party",
      "Free"
    ],
    "time": "6:00 PM",
    "location": "Elsewhere Rooftop / The Loft · 599 Johnson Ave #1, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://dice.fm/partner/tickets/event/pywebp-all-gays-go-to-heaven-14th-aug-elsewhere-rooftop-new-york-the-loft-new-york-tickets",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-day-party",
    "city": "nyc"
  },
  {
    "id": "63",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-07",
    "dayLabel": "Friday",
    "name": "The Salon: Black August Edition",
    "organizer": "Gladys Books",
    "types": [
      "meetup",
      "workshop",
      "educational"
    ],
    "vibesRaw": "chill creative community",
    "free": false,
    "price": "Sliding scale, starts at $10 (suggested $20); free admission option available",
    "badges": [
      "Meetup",
      "Workshop",
      "Educational"
    ],
    "time": "7:00 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Blvd, Brooklyn, NY 11233",
    "vibeTags": [
      "Chill",
      "Creative",
      "Community"
    ],
    "ctaHref": "https://luma.com/thesalon",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "city": "nyc"
  },
  {
    "id": "64",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-15",
    "dayLabel": "Saturday",
    "name": "SASS Summer Polly Popup Tour -- Gladys Books & Wine",
    "organizer": "Gladys Books",
    "types": [
      "meetup",
      "workshop",
      "educational"
    ],
    "vibesRaw": "chill creative community",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Workshop",
      "Educational",
      "Free"
    ],
    "time": "2:00 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Blvd, Brooklyn, NY 11233",
    "vibeTags": [
      "Chill",
      "Creative",
      "Community"
    ],
    "ctaHref": "https://partiful.com/e/0iT0J00MrFgbX88DO8rv",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "city": "nyc"
  },
  {
    "id": "65",
    "festival": "august-events",
    "day": "thursday",
    "dayDate": "2026-08-13",
    "dayLabel": "Thursday",
    "name": "Monthly Journaling Series with Licensed Therapist Aseanté Renee",
    "organizer": "Gladys Books",
    "types": [
      "meetup",
      "workshop",
      "educational"
    ],
    "vibesRaw": "chill creative community",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Workshop",
      "Educational",
      "Free"
    ],
    "time": "7:00 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Blvd, Brooklyn, NY 11233",
    "vibeTags": [
      "Chill",
      "Creative",
      "Community"
    ],
    "ctaHref": "https://www.gladysbooksandwine.com/pages/events#?event-id=86551",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "city": "nyc"
  },
  {
    "id": "66",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-15",
    "dayLabel": "Saturday",
    "name": "Monthly Collage Series + WNBA Watch Party with Fitted WBB, the Living Lesbian Archive, For Them and Autostraddle",
    "organizer": "Gladys Books",
    "types": [
      "meetup",
      "workshop",
      "educational"
    ],
    "vibesRaw": "chill creative community",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Workshop",
      "Educational",
      "Free"
    ],
    "time": "1:00 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Blvd, Brooklyn, NY 11233",
    "vibeTags": [
      "Chill",
      "Creative",
      "Community"
    ],
    "ctaHref": "https://www.gladysbooksandwine.com/pages/events#?event-id=86324",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "city": "nyc"
  },
  {
    "id": "67",
    "festival": "august-events",
    "day": "sunday",
    "dayDate": "2026-08-16",
    "dayLabel": "Sunday",
    "name": "Children's Author Event: The Boredom Monster -- Reading, Drawing & Signing!",
    "organizer": "Gladys Books",
    "types": [
      "meetup",
      "workshop",
      "educational"
    ],
    "vibesRaw": "chill creative community",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Workshop",
      "Educational",
      "Free"
    ],
    "time": "2:00 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Blvd, Brooklyn, NY 11233",
    "vibeTags": [
      "Chill",
      "Creative",
      "Community"
    ],
    "ctaHref": "https://luma.com/THE-BOREDOM-MONSTER",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "city": "nyc"
  },
  {
    "id": "68",
    "festival": "august-events",
    "day": "tuesday",
    "dayDate": "2026-08-18",
    "dayLabel": "Tuesday",
    "name": "Author Event: What (TF) Do I Do Now? by Tareasa “Reesa Teesa” Johnson",
    "organizer": "Gladys Books",
    "types": [
      "meetup",
      "workshop",
      "educational"
    ],
    "vibesRaw": "chill creative community",
    "free": false,
    "price": "$32 (signed book) or $10 (gift card tier)",
    "badges": [
      "Meetup",
      "Workshop",
      "Educational"
    ],
    "time": "7:00 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Blvd, Brooklyn, NY 11233",
    "vibeTags": [
      "Chill",
      "Creative",
      "Community"
    ],
    "ctaHref": "https://luma.com/ReesaTeesa",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "city": "nyc"
  },
  {
    "id": "69",
    "festival": "august-events",
    "day": "wednesday",
    "dayDate": "2026-08-19",
    "dayLabel": "Wednesday",
    "name": "The Butterfly Effect",
    "organizer": "Gladys Books",
    "types": [
      "meetup",
      "workshop",
      "educational"
    ],
    "vibesRaw": "chill creative community",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Workshop",
      "Educational",
      "Free"
    ],
    "time": "7:00 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Blvd, Brooklyn, NY 11233",
    "vibeTags": [
      "Chill",
      "Creative",
      "Community"
    ],
    "ctaHref": "https://www.eventbrite.com/e/the-butterfly-effect-tickets-1489942320589",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "city": "nyc"
  },
  {
    "id": "70",
    "festival": "august-events",
    "day": "thursday",
    "dayDate": "2026-08-27",
    "dayLabel": "Thursday",
    "name": "Broken Hearts Restored presents Unsent: An Evening of Letter Writing & Reflection",
    "organizer": "Gladys Books",
    "types": [
      "meetup",
      "workshop",
      "educational"
    ],
    "vibesRaw": "chill creative community",
    "free": false,
    "price": "Suggested $15, minimum $10",
    "badges": [
      "Meetup",
      "Workshop",
      "Educational"
    ],
    "time": "7:00 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Blvd, Brooklyn, NY 11233",
    "vibeTags": [
      "Chill",
      "Creative",
      "Community"
    ],
    "ctaHref": "https://luma.com/unsent",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "city": "nyc"
  },
  {
    "id": "71",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-28",
    "dayLabel": "Friday",
    "name": "Special Event -- To Be Announced",
    "organizer": "The Function",
    "types": [],
    "vibesRaw": "chill community ass shaking groove",
    "free": false,
    "price": "TBD",
    "badges": [],
    "time": "TBD",
    "location": "TBD",
    "vibeTags": [
      "Chill",
      "Community",
      "Ass Shaking",
      "Groove"
    ],
    "ctaHref": "https://www.instagram.com/p/DX2xEhokY0M/?img_index=1",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "baltimore"
  },
  {
    "id": "72",
    "festival": "august-events",
    "day": "thursday",
    "dayDate": "2026-08-13",
    "dayLabel": "Thursday",
    "name": "Parity Porch Concert Summer Series (August edition)",
    "organizer": "Blk Ass Flea Mkt (shared/promoted -- organized by Parity)",
    "types": [
      "live-show",
      "happy-hour"
    ],
    "vibesRaw": "chill community live show groove",
    "free": true,
    "price": "Free",
    "badges": [
      "Live Show",
      "Happy Hour",
      "Free"
    ],
    "time": "6:30 PM",
    "location": "500 N Carrollton Ave (porch stage) · 500 North Carrollton Avenue, Baltimore, MD 21223",
    "vibeTags": [
      "Chill",
      "Community",
      "Live Show",
      "Groove"
    ],
    "ctaHref": "https://www.eventbrite.com/e/parity-porch-concert-summer-series-tickets-1989124481871",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-live-show",
    "city": "baltimore"
  },
  {
    "id": "73",
    "festival": "august-events",
    "day": "sunday",
    "dayDate": "2026-08-16",
    "dayLabel": "Sunday",
    "name": "DA JUKE: House Is a Home [House + Club Music Vibes]",
    "organizer": "Blk Ass Flea Mkt",
    "types": [
      "day-party",
      "meetup"
    ],
    "vibesRaw": "chill community ass shaking groove",
    "free": false,
    "price": "$5",
    "badges": [
      "Day Party",
      "Meetup"
    ],
    "time": "4:00 PM",
    "location": "Verify manually · LOCATION TBA",
    "vibeTags": [
      "Chill",
      "Community",
      "Ass Shaking",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/da-juke-house-is-a-home-house-club-music-vibes",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "baltimore"
  },
  {
    "id": "75",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-08",
    "dayLabel": "Saturday",
    "name": "Sapphic Saturdays",
    "organizer": "Aphrodites House",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt community grown & sexy groove",
    "free": false,
    "price": "$12",
    "badges": [
      "After Dark"
    ],
    "time": "8:00 PM",
    "location": "The Manor · 924 N Charles St, Baltimore, MD 21201, USA",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Community",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/sapphic-saturdays-25",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "baltimore"
  },
  {
    "id": "76",
    "festival": "august-events",
    "day": "sunday",
    "dayDate": "2026-08-09",
    "dayLabel": "Sunday",
    "name": "Park Takeover x The Kickback Social Club",
    "organizer": "Dee Rene",
    "types": [
      "outdoors-hangout",
      "meetup"
    ],
    "vibesRaw": "community byob chill",
    "free": true,
    "price": "Free",
    "badges": [
      "Outdoors Hangout",
      "Meetup",
      "Free"
    ],
    "time": "3:00 PM",
    "location": "The Great Lawn (exact park/venue name not stated -- near a Whole Foods; possibly Meridian Hill/Malcolm X Park, DC, unconfirmed) · The Parks Historic Walter Reed - The Great Lawn",
    "vibeTags": [
      "Community",
      "BYOB",
      "Chill"
    ],
    "ctaHref": "https://posh.vip/e/park-takeover-x-the-kickback-social-club",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-outdoors-hangout",
    "city": "dc"
  },
  {
    "id": "79",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-15",
    "dayLabel": "Saturday",
    "name": "GATHER August Edition: A Monthly Mixtape Sapphic Tea Dance & Social",
    "organizer": "Mixtape Sapphics",
    "types": [
      "outdoors-hangout",
      "happy-hour"
    ],
    "vibesRaw": "community chill groove",
    "free": false,
    "price": "$21",
    "badges": [
      "Outdoors Hangout",
      "Happy Hour"
    ],
    "time": "5:00 PM",
    "location": "Spark Social · 2009 14th Street Northwest, Washington, DC 20009",
    "vibeTags": [
      "Community",
      "Chill",
      "Groove"
    ],
    "ctaHref": "https://www.eventbrite.com/e/gather-august-edition-a-monthly-mixtape-sapphic-tea-dance-social-tickets-1991954680070",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-outdoors-hangout",
    "city": "dc"
  },
  {
    "id": "80",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-29",
    "dayLabel": "Saturday",
    "name": "Mic Check: A Mixtape Karaoke Community Night",
    "organizer": "Mixtape Sapphics",
    "types": [
      "happy-hour"
    ],
    "vibesRaw": "karaoke chill community groove",
    "free": false,
    "price": "$36",
    "badges": [
      "Happy Hour"
    ],
    "time": "5:00 PM",
    "location": "Muzette · 2305 18th Street Northwest, Washington, DC 20009",
    "vibeTags": [
      "Karaoke",
      "Chill",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://www.eventbrite.com/e/mic-check-a-mixtape-karaoke-community-night-tickets-1995386748479",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-happy-hour",
    "city": "dc"
  },
  {
    "id": "85",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-15",
    "dayLabel": "Saturday",
    "name": "Club Ghetto Tech: Vol. 7",
    "organizer": "Sinners and Saints",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt community ass shaking groove",
    "free": false,
    "price": "$5-20",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "Sinners and Saints · 2309 18th Street Northwest, Washington, DC 20009",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Groove"
    ],
    "ctaHref": "https://ra.co/events/2496972",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "86",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-15",
    "dayLabel": "Saturday",
    "name": "Baddie Island: 2000's Themed Pool Party",
    "organizer": "The Frequency Class",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt community ass shaking groove",
    "free": false,
    "price": "$23",
    "badges": [
      "After Dark"
    ],
    "time": "8:00 PM",
    "location": "Hotel Zena Washington DC · 1155 14th St NW, Washington, DC 20005",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/baddie-island-2000s-themed-pool-party",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "88",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-29",
    "dayLabel": "Saturday",
    "name": "Love Groove Festival -- 10th Anniversary",
    "organizer": "Love Groove Festival",
    "types": [
      "outdoors-hangout",
      "festival",
      "live-show"
    ],
    "vibesRaw": "chill creative groove live show",
    "free": false,
    "price": "$29-$209 (early bird through 8/1)",
    "badges": [
      "Outdoors Hangout",
      "Festival",
      "Live Show"
    ],
    "time": "12:00 PM",
    "location": "Point Park, Harbor East · Harbor East, Baltimore, MD (street address not given)",
    "vibeTags": [
      "Chill",
      "Creative",
      "Groove",
      "Live Show"
    ],
    "ctaHref": "https://lovegroovefestival.com/product/lg10/",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-outdoors-hangout",
    "city": "baltimore"
  },
  {
    "id": "89",
    "festival": "august-events",
    "day": "sunday",
    "dayDate": "2026-08-16",
    "dayLabel": "Sunday",
    "name": "The Hey Cousin Culture Fest 2026 (4th annual): Celebrating Black Joy @ The Plaza",
    "organizer": "The Hey Cousin Culture Fest",
    "types": [
      "outdoors-hangout",
      "festival",
      "live-show"
    ],
    "vibesRaw": "chill creative groove live show family",
    "free": true,
    "price": "Free",
    "badges": [
      "Outdoors Hangout",
      "Festival",
      "Live Show",
      "Free"
    ],
    "time": "1:00 PM",
    "location": "Veterans Plaza · 1 Veterans Place, Silver Spring, MD 20910",
    "vibeTags": [
      "Chill",
      "Creative",
      "Groove",
      "Live Show",
      "Family"
    ],
    "ctaHref": "https://www.eventbrite.com/e/2026-hey-cousin-culture-fest-tickets-1986580366353",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-outdoors-hangout",
    "city": "dc"
  },
  {
    "id": "90",
    "festival": "august-events",
    "day": "monday",
    "dayDate": "2026-08-17",
    "dayLabel": "Monday",
    "name": "Isaiah Rashad: Lil Sunny's Awful Road Trip Tour",
    "organizer": "ISAIAH RASHAD",
    "types": [
      "live-show",
      "after-dark"
    ],
    "vibesRaw": "creative ass shaking chill live show groove",
    "free": false,
    "price": "$87",
    "badges": [
      "Live Show",
      "After Dark"
    ],
    "time": "8:00 PM",
    "location": "The Fillmore Silver Spring · 8656 Colesville Road, Silver Spring, MD",
    "vibeTags": [
      "Creative",
      "Ass Shaking",
      "Chill",
      "Live Show",
      "Groove"
    ],
    "ctaHref": "https://www.ticketmaster.com/isaiah-rashad-lil-sunnys-awful-road-silver-spring-maryland-08-17-2026/event/150064CC1AF7C2B4",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-live-show",
    "city": "dc"
  },
  {
    "id": "91",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-29",
    "dayLabel": "Saturday",
    "name": "KevOnStage (comedy)",
    "organizer": "MGM National Harbor",
    "types": [
      "live-show",
      "after-dark"
    ],
    "vibesRaw": "chill creative live show",
    "free": false,
    "price": "From ~$84-90",
    "badges": [
      "Live Show",
      "After Dark"
    ],
    "time": "8:00 PM",
    "location": "The Theater at MGM National Harbor · 101 MGM National Ave, Oxon Hill, MD 20745",
    "vibeTags": [
      "Chill",
      "Creative",
      "Live Show"
    ],
    "ctaHref": "https://mgmnationalharbor.mgmresorts.com/en/entertainment/kevonstage.html",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-live-show",
    "city": "dc"
  },
  {
    "id": "92",
    "festival": "august-events",
    "day": "wednesday",
    "dayDate": "2026-08-12",
    "dayLabel": "Wednesday",
    "name": "Game Night",
    "organizer": "The Collective: NYC Black Pride",
    "types": [
      "after-dark",
      "meetup"
    ],
    "vibesRaw": "chill community games groove flirt",
    "free": false,
    "price": "TBD",
    "badges": [
      "After Dark",
      "Meetup"
    ],
    "time": "9:00 PM",
    "location": "Solera · Saint Ann's Avenue, The Bronx, NY (exact street number not given)",
    "vibeTags": [
      "Chill",
      "Community",
      "Games",
      "Groove",
      "Flirt"
    ],
    "ctaHref": "https://www.the-nyc-collective.com/events/game-night",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "94",
    "festival": "august-events",
    "day": "thursday",
    "dayDate": "2026-08-13",
    "dayLabel": "Thursday",
    "name": "TrappyHour",
    "organizer": "TrappyHourHarlem",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt community ass shaking grown & sexy groove",
    "free": false,
    "price": "TBD",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "Harlem Nights · 2361 Adam Clayton Powell Jr Blvd, New York, NY 10030",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://www.the-nyc-collective.com/events/trappyhour-1",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "95",
    "festival": "august-events",
    "day": "sunday",
    "dayDate": "2026-08-16",
    "dayLabel": "Sunday",
    "name": "TrappyHour",
    "organizer": "TrappyHourHarlem",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt community ass shaking grown & sexy groove",
    "free": false,
    "price": "TBD",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "Harlem Nights · 2361 Adam Clayton Powell Jr Blvd, New York, NY 10030",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://www.the-nyc-collective.com/events/trappyhour-2",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "96",
    "festival": "august-events",
    "day": "sunday",
    "dayDate": "2026-08-16",
    "dayLabel": "Sunday",
    "name": "Haus of Honey 30+ Sapphic",
    "organizer": "Haus of Honey",
    "types": [
      "day-party"
    ],
    "vibesRaw": "flirt community ass shaking grown & sexy groove",
    "free": false,
    "price": "$30.47",
    "badges": [
      "Day Party"
    ],
    "time": "5:00 PM",
    "location": "The Sultan Room Rooftop · 234 Starr St, Brooklyn, NY 11237",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://dice.fm/event/6do963-haus-of-honey-16th-aug-the-sultan-room-rooftop-brooklyn-tickets",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "nyc"
  },
  {
    "id": "97",
    "festival": "august-events",
    "day": "sunday",
    "dayDate": "2026-08-16",
    "dayLabel": "Sunday",
    "name": "Good Dayz: Tailgate",
    "organizer": "Good Dayz: Tailgate",
    "types": [
      "day-party"
    ],
    "vibesRaw": "flirt community ass shaking grown & sexy groove",
    "free": false,
    "price": "TBD",
    "badges": [
      "Day Party"
    ],
    "time": "5:00 PM",
    "location": "TBD",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://www.the-nyc-collective.com/events/good-dayz-tailgate",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "nyc"
  },
  {
    "id": "98",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-15",
    "dayLabel": "Saturday",
    "name": "Joe Morris Events (Collective weekend date)",
    "organizer": "Joe Morris Events",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt community ass shaking grown & sexy groove",
    "free": false,
    "price": "TBD",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "TBD",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://www.the-nyc-collective.com/events/joe-morris-events",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "99",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-07",
    "dayLabel": "Friday",
    "name": "Detention (powered by Recess)",
    "organizer": "Recess",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt community ass shaking grown & sexy groove",
    "free": false,
    "price": "$16.49-$32.97 (Early Bird sold out)",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "Red Eye NY · 355 West 41st Street, New York, NY 10036",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://redeyetickets.com/events/detention-powered-by-recess",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "100",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-15",
    "dayLabel": "Saturday",
    "name": "Sunkissed by Recess (Collective weekend edition)",
    "organizer": "Recess",
    "types": [
      "day-party"
    ],
    "vibesRaw": "flirt community ass shaking grown & sexy groove",
    "free": false,
    "price": "$10",
    "badges": [
      "Day Party"
    ],
    "time": "3:00 PM",
    "location": "Unlisted Rooftop (11th floor) · 3 Freeman Alley, New York, NY 10002",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/sunkissed-by-recess-1",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "nyc"
  },
  {
    "id": "101",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-15",
    "dayLabel": "Saturday",
    "name": "DC \"Dungeon\"",
    "organizer": "DEVIANT",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt community ass shaking grown & sexy groove kink",
    "free": false,
    "price": "$29",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "ICON · 2001 11th Street NW, Washington, DC 20001",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Grown & Sexy",
      "Groove",
      "Kink"
    ],
    "ctaHref": "https://www.deviant.live/party/dc",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "102",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-14",
    "dayLabel": "Friday",
    "name": "NYC \"Physique\"",
    "organizer": "DEVIANT",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt community ass shaking grown & sexy groove kink",
    "free": false,
    "price": "$25 Before 12AM / $35 General Admission",
    "badges": [
      "After Dark"
    ],
    "time": "11:00 PM",
    "location": "Red Eye · 355 West 41st Street, New York, NY 10036",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Grown & Sexy",
      "Groove",
      "Kink"
    ],
    "ctaHref": "https://www.deviant.live/party/nyc",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc"
  },
  {
    "id": "103",
    "festival": "august-events",
    "day": "saturday",
    "dayDate": "2026-08-22",
    "dayLabel": "Saturday",
    "name": "The Latex Ball 2026",
    "organizer": "Gay Men's Health Crisis (GMHC)",
    "types": [
      "live-show",
      "ball"
    ],
    "vibesRaw": "flirt community ass shaking grown & sexy groove",
    "free": true,
    "price": "Free",
    "badges": [
      "Live Show",
      "Ball",
      "Free"
    ],
    "time": "6:00 PM",
    "location": "Terminal 5 · New York, NY (street address not given on this page)",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://www.eventbrite.com/e/the-latex-ball-2026-tickets-1993548175257",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-live-show",
    "city": "nyc"
  },
  {
    "id": "104",
    "festival": "august-events",
    "day": "wednesday",
    "dayDate": "2026-08-19",
    "dayLabel": "Wednesday",
    "name": "Michael Roberson Margiela Memorial/Community Event",
    "organizer": "NYC Center for Black Pride",
    "types": [
      "live-show"
    ],
    "vibesRaw": "community chill",
    "free": true,
    "price": "Free",
    "badges": [
      "Live Show",
      "Free"
    ],
    "time": "6:00 PM",
    "location": "Dallas BBQ Restaurant (Lower Level) · 261 8th Ave, New York, NY (Lower Level)",
    "vibeTags": [
      "Community",
      "Chill"
    ],
    "ctaHref": "https://www.nycblackpride.org/",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-live-show",
    "city": "nyc"
  },
  {
    "id": "105",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-21",
    "dayLabel": "Friday",
    "name": "Heritage Awards Ceremony: Celebrating A Legacy of Resilience",
    "organizer": "NYC Center for Black Pride",
    "types": [
      "live-show"
    ],
    "vibesRaw": "chill networking community cultural grown & sexy live show",
    "free": false,
    "price": "TBD",
    "badges": [
      "Live Show"
    ],
    "time": "3:00 PM",
    "location": "Renaissance Harlem Hotel · 233 W 125th St, New York, NY 10027",
    "vibeTags": [
      "Chill",
      "Networking",
      "Community",
      "Cultural",
      "Grown & Sexy",
      "Live Show"
    ],
    "ctaHref": "https://www.nycblackpride.org/",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-live-show",
    "city": "nyc"
  },
  {
    "id": "106",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-14",
    "dayLabel": "Friday",
    "name": "Journey To Her (25 Years of Truth)",
    "organizer": "Datruthdapoet",
    "types": [
      "live-show"
    ],
    "vibesRaw": "chill community cultural grown & sexy live show",
    "free": false,
    "price": "$3",
    "badges": [
      "Live Show"
    ],
    "time": "7:00 PM",
    "location": "Baltimore Museum of Art · 10 Art Museum Drive, Baltimore, MD 21218",
    "vibeTags": [
      "Chill",
      "Community",
      "Cultural",
      "Grown & Sexy",
      "Live Show"
    ],
    "ctaHref": "https://www.eventbrite.com/e/journey-to-her-tickets-1991020807833",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-live-show",
    "city": "baltimore"
  },
  {
    "id": "107",
    "festival": "august-events",
    "day": "wednesday",
    "dayDate": "2026-08-26",
    "dayLabel": "Wednesday",
    "name": "Pecha Kucha: 2026 Season (August edition)",
    "organizer": "Pecha Kucha: 2026 Season",
    "types": [
      "meetup",
      "educational"
    ],
    "vibesRaw": "community creative chill live show",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Educational",
      "Free"
    ],
    "time": "8:00 PM (doors/bar opens 7:30 PM)",
    "location": "Current Space Garden Bar · 421 N Howard St, Baltimore, MD (exact address per Current Space -- verify)",
    "vibeTags": [
      "Community",
      "Creative",
      "Chill",
      "Live Show"
    ],
    "ctaHref": "https://pools.events/event/lIuM5RFP/pecha-kucha-2026-season/",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "city": "baltimore"
  },
  {
    "id": "108",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-21",
    "dayLabel": "Friday",
    "name": "NECTAR",
    "organizer": "SDOT",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "groove community ass shaking flirt creative",
    "free": false,
    "price": "$6 advance / $10 day-of",
    "badges": [
      "After Dark"
    ],
    "time": "8:00 PM",
    "location": "Current Space (rear courtyard) · 421 Tyson Street, Baltimore, MD",
    "vibeTags": [
      "Groove",
      "Community",
      "Ass Shaking",
      "Flirt",
      "Creative"
    ],
    "ctaHref": "https://pools.events/event/AesYRV3e/nectar/",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "baltimore"
  },
  {
    "id": "109",
    "festival": "august-events",
    "day": "friday",
    "dayDate": "2026-08-07",
    "dayLabel": "Friday",
    "name": "GIVE WITH: A CLLCTIVGive Celebration",
    "organizer": "CLLCTIVLY",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "groove community ass shaking flirt creative",
    "free": false,
    "price": "$78.50",
    "badges": [
      "After Dark"
    ],
    "time": "7:00 PM (Elevated Access) / 8:00 PM (General Admission)",
    "location": "Baltimore Museum of Industry · 1415 Key Highway, Baltimore, MD 21230",
    "vibeTags": [
      "Groove",
      "Community",
      "Ass Shaking",
      "Flirt",
      "Creative"
    ],
    "ctaHref": "https://tickets.givewith.org/events/cllctivly/2294817",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "baltimore"
  }
];
