/* eslint-disable */
// Auto-generated by scripts/sync-events.ts from the Google Sheets Baltimore Pride Master tab. Do not edit by hand.
import type { PrideEvent } from '../../types/event';

export const generatedEvents: PrideEvent[] = [
  {
    "id": "2",
    "festival": "baltimore-pride",
    "day": "tuesday",
    "dayDate": "2026-06-09",
    "dayLabel": "Tuesday",
    "name": "The Masc Meet Up: The Unspoken Energy We All Know",
    "organizer": "All Love Baltimore & Baltimore City LGBTQ Affairs",
    "types": [
      "meetup",
      "workshop"
    ],
    "vibesRaw": "cultural community networking 30+",
    "free": true,
    "badges": [
      "Meetup",
      "Workshop",
      "Free"
    ],
    "time": "7:30 PM",
    "location": "Impact Hub Baltimore · 10 E North Ave Suite 5, Baltimore, MD 21202",
    "vibeTags": [
      "Cultural",
      "Community",
      "Networking",
      "30+"
    ],
    "ctaHref": "https://posh.vip/e/the-masc-meetup-the-unspoken-energy-we-all-know",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup"
  },
  {
    "id": "3",
    "festival": "baltimore-pride",
    "day": "tuesday",
    "dayDate": "2026-06-09",
    "dayLabel": "Tuesday",
    "name": "Baltimore Pride Happy Hour & Karaoke",
    "organizer": "The Pride Center of Maryland",
    "types": [
      "happy-hour"
    ],
    "vibesRaw": "karaoke groove",
    "free": true,
    "badges": [
      "Happy Hour",
      "Free"
    ],
    "time": "5:00 PM",
    "location": "33 W North Ave, Baltimore, MD 21201",
    "vibeTags": [
      "Karaoke",
      "Groove"
    ],
    "ctaHref": "https://www.eventbrite.com/e/baltimore-pride-happy-hour-karaoke-tickets-1989316825175",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-happy-hour"
  },
  {
    "id": "4",
    "festival": "baltimore-pride",
    "day": "wednesday",
    "dayDate": "2026-06-10",
    "dayLabel": "Wednesday",
    "name": "Flavors; Pride Happy Hour",
    "organizer": "All Love Baltimore & Blk Ass Flea Mkt",
    "types": [
      "happy-hour"
    ],
    "vibesRaw": "flirt groove food 30+",
    "free": true,
    "badges": [
      "Happy Hour",
      "Free"
    ],
    "time": "7:00 PM",
    "location": "Broadway Market · 1640 Aliceanna St. Baltimore MD, 21231",
    "vibeTags": [
      "Flirt",
      "Groove",
      "Food",
      "30+"
    ],
    "ctaHref": "https://posh.vip/e/flavors-pride-happy-hour",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-happy-hour"
  },
  {
    "id": "5",
    "festival": "baltimore-pride",
    "day": "wednesday",
    "dayDate": "2026-06-10",
    "dayLabel": "Wednesday",
    "name": "Pride on the Plaza Resource and Job Fair",
    "organizer": "The Pride Center of Maryland",
    "types": [
      "meetup",
      "workshop",
      "outdoors-hangout"
    ],
    "vibesRaw": "networking community cultural",
    "free": true,
    "badges": [
      "Meetup",
      "Workshop",
      "Outdoors Hangout",
      "Free"
    ],
    "time": "12:00 PM",
    "location": "Mayor’s Lawn at War Memorial Plaza · War Memorial Plaza, Baltimore, MD 21202",
    "vibeTags": [
      "Networking",
      "Community",
      "Cultural"
    ],
    "ctaHref": "https://docs.google.com/forms/d/e/1FAIpQLSe_NaouGyuE9uhccRjcsvE677NeftkBUXHJXcxmkxcC35ZVOw/viewform",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup"
  },
  {
    "id": "6",
    "festival": "baltimore-pride",
    "day": "wednesday",
    "dayDate": "2026-06-10",
    "dayLabel": "Wednesday",
    "name": "There's No Place Like Home Fashion Show",
    "organizer": "The Pride Center of Maryland, LGBTQ Affairs, Free State Justice, NAMI",
    "types": [
      "outdoors-hangout",
      "meetup"
    ],
    "vibesRaw": "creative community live show",
    "free": true,
    "badges": [
      "Outdoors Hangout",
      "Meetup",
      "Free"
    ],
    "time": "4:00 PM",
    "location": "Mayor’s Lawn at War Memorial Plaza · War Memorial Plaza, Baltimore, MD 21203",
    "vibeTags": [
      "Creative",
      "Community",
      "Live Show"
    ],
    "ctaHref": "https://www.baltimorepride.org/event-details/theres-no-place-like-home-fashion-show/form",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-outdoors-hangout"
  },
  {
    "id": "7",
    "festival": "baltimore-pride",
    "day": "wednesday",
    "dayDate": "2026-06-10",
    "dayLabel": "Wednesday",
    "name": "Suits & Sneakers Cocktail Reception",
    "organizer": "The Pride Center of Maryland",
    "types": [
      "happy-hour",
      "ball",
      "after-dark"
    ],
    "vibesRaw": "grown & sexy cultural community networking open bar food",
    "free": false,
    "badges": [
      "Happy Hour",
      "Ball",
      "After Dark"
    ],
    "time": "7:00 PM",
    "location": "Top of the World · 401 E Pratt St 27th floor, Baltimore, MD 21202",
    "vibeTags": [
      "Grown & Sexy",
      "Cultural",
      "Community",
      "Networking",
      "Open Bar",
      "Food"
    ],
    "ctaHref": "https://www.eventbrite.com/e/baltimore-pride-suits-sneakers-cocktail-reception-tickets-1989317656662",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-happy-hour"
  },
  {
    "id": "8",
    "festival": "baltimore-pride",
    "day": "thursday",
    "dayDate": "2026-06-11",
    "dayLabel": "Thursday",
    "name": "The Link-Up: A Pride Mixer",
    "organizer": "RLA & Aphrodite's House",
    "types": [
      "happy-hour",
      "meetup"
    ],
    "vibesRaw": "groove flirt food",
    "free": true,
    "badges": [
      "Happy Hour",
      "Meetup",
      "Free"
    ],
    "time": "5:00 PM",
    "location": "Noir Restaurant and Lounge · 716 York Rd, Baltimore, MD 21212",
    "vibeTags": [
      "Groove",
      "Flirt",
      "Food"
    ],
    "ctaHref": "https://posh.vip/e/the-link-up-a-pride-happy-hour",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-happy-hour"
  },
  {
    "id": "9",
    "festival": "baltimore-pride",
    "day": "thursday",
    "dayDate": "2026-06-11",
    "dayLabel": "Thursday",
    "name": "Parity Porch Concert:Pride Edition Ft. Black Assets",
    "organizer": "All Love Baltimore, PARITY & Baltimore City LGBTQ Affairs",
    "types": [
      "outdoors"
    ],
    "vibesRaw": "community live show",
    "free": true,
    "badges": [
      "Outdoors",
      "Free"
    ],
    "time": "6:30 PM",
    "location": "500 Blk. of North Carrollton Ave",
    "vibeTags": [
      "Community",
      "Live Show"
    ],
    "ctaHref": "https://posh.vip/e/parity-porch-concert-pride-edition-featuring-black-assests",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-outdoors"
  },
  {
    "id": "10",
    "festival": "baltimore-pride",
    "day": "friday",
    "dayDate": "2026-06-12",
    "dayLabel": "Friday",
    "name": "Call Out (The Pool Party)",
    "organizer": "HerVibeEvents",
    "types": [
      "unknown"
    ],
    "vibesRaw": "35+ flirt food byob",
    "free": false,
    "badges": [
      "Unknown"
    ],
    "time": "12:00 PM",
    "location": "TBD w/ticket purchase",
    "vibeTags": [
      "35+",
      "Flirt",
      "Food",
      "BYOB"
    ],
    "ctaHref": "https://www.eventbrite.com/e/call-out-the-pool-party-tickets-1989123427718?utm_experiment=test_share_listing&aff=ebdsshios&sg=76bfd980b4ba9b634c1089308b47b0953783e9018d356a30d11cd21bef8495e92caab815adfdd6cf658dbb2a96798ca3c3fad22edc66e86eec8670d53b4bedb73541aeb3b214c951dda41e2e7b",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-unknown"
  },
  {
    "id": "11",
    "festival": "baltimore-pride",
    "day": "friday",
    "dayDate": "2026-06-12",
    "dayLabel": "Friday",
    "name": "The Black Lesbian Link-up",
    "organizer": "Lez Black Gurls",
    "types": [
      "meetup"
    ],
    "vibesRaw": "flirt dating food",
    "free": false,
    "badges": [
      "Meetup"
    ],
    "time": "7:00 PM",
    "location": "The Empanada Lady · 10 South St STE 100, Baltimore, MD 21202",
    "vibeTags": [
      "Flirt",
      "Dating",
      "Food"
    ],
    "ctaHref": "https://www.eventbrite.com/e/lez-black-gurls-presents-the-black-lesbian-link-up-tickets-1989436050782?utm_experiment=test_share_listing&aff=ebdsshios&sg=d038de198ab6c8565d2dd826e8a4689fce5bd6f89f2f54569e47b261ebc0ad0b191c312e847dc7d1fcd87d960e7edf249810a8371439a9ce985bad02342a7e9c2f84662873d0428c6dcff49927",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "discountCode": "TRUE"
  },
  {
    "id": "12",
    "festival": "baltimore-pride",
    "day": "friday",
    "dayDate": "2026-06-12",
    "dayLabel": "Friday",
    "name": "Sugar Rush: Grown-Up Trampoline Glow Party",
    "organizer": "All Love Baltimore & Baltimore City LGBTQ Affairs",
    "types": [
      "gynasium",
      "after-dark"
    ],
    "vibesRaw": "30+ games groove",
    "free": false,
    "badges": [
      "Gynasium",
      "After Dark"
    ],
    "time": "10:30 PM",
    "location": "Sky Zone Timonium · 23 W Aylesbury Rd, Timonium, MD 21093",
    "vibeTags": [
      "30+",
      "Games",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/sugar-rush-2",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-gynasium"
  },
  {
    "id": "13",
    "festival": "baltimore-pride",
    "day": "friday",
    "dayDate": "2026-06-12",
    "dayLabel": "Friday",
    "name": "Mount Vernon Block Party",
    "organizer": "The Pride Center of Maryland",
    "types": [
      "outdoors-hangout",
      "day-party",
      "meetup"
    ],
    "vibesRaw": "community food wellness groove",
    "free": true,
    "badges": [
      "Outdoors Hangout",
      "Day Party",
      "Meetup",
      "Free"
    ],
    "time": "4:00 PM",
    "location": "200 W Reed Street · 201 W Reed Street",
    "vibeTags": [
      "Community",
      "Food",
      "Wellness",
      "Groove"
    ],
    "ctaHref": "https://www.eventbrite.com/e/mt-vernon-pride-block-party-tickets-1989318307609",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-outdoors-hangout"
  },
  {
    "id": "14",
    "festival": "baltimore-pride",
    "day": "friday",
    "dayDate": "2026-06-12",
    "dayLabel": "Friday",
    "name": "Twilight on the Terrace Gala",
    "organizer": "The Pride Center of Maryland",
    "types": [
      "ball"
    ],
    "vibesRaw": "live show groove networking food community",
    "free": false,
    "badges": [
      "Ball"
    ],
    "time": "7:00 PM",
    "location": "M&T Bank Exchange at the France-Merrick Performing Arts Center · 401 W Fayette St, Baltimore, MD 21201",
    "vibeTags": [
      "Live Show",
      "Groove",
      "Networking",
      "Food",
      "Community"
    ],
    "ctaHref": "https://www.eventbrite.com/e/baltimore-pride-twilight-on-the-terrace-gala-tickets-1989318991655",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-ball"
  },
  {
    "id": "15",
    "festival": "baltimore-pride",
    "day": "friday",
    "dayDate": "2026-06-12",
    "dayLabel": "Friday",
    "name": "Elevation Late Night Happy Hour",
    "organizer": "Alternative Union",
    "types": [
      "happy-hour",
      "after-dark"
    ],
    "vibesRaw": "grown & sexy flirt ass shaking food",
    "free": false,
    "badges": [
      "Happy Hour",
      "After Dark"
    ],
    "time": "8:00 PM",
    "location": "Belieze Rooftop · 316 Guilford Ave, Baltimore, MD 21202",
    "vibeTags": [
      "Grown & Sexy",
      "Flirt",
      "Ass Shaking",
      "Food"
    ],
    "ctaHref": "https://posh.vip/e/yewtopia",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-happy-hour",
    "discountCode": "TRUE"
  },
  {
    "id": "16",
    "festival": "baltimore-pride",
    "day": "friday",
    "dayDate": "2026-06-12",
    "dayLabel": "Friday",
    "name": "The Kickoff",
    "organizer": "Bmore Prides Truth Or Dare 11 With Badd Dolly",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt",
    "free": false,
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "Select Lounge · 415 North Paca Street\nBaltimore, MD 21201",
    "vibeTags": [
      "Ass Shaking",
      "Flirt"
    ],
    "ctaHref": "https://www.eventbrite.com/e/bmore-prides-truth-or-dare-11-with-badd-dolly-tickets-1989971205444?aff=ebdsoporgprofile",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "discountCode": "FALSE"
  },
  {
    "id": "17",
    "festival": "baltimore-pride",
    "day": "saturday",
    "dayDate": "2026-06-13",
    "dayLabel": "Saturday",
    "name": "CharmCityPrideFest",
    "organizer": "CharmCityPride",
    "types": [
      "after-dark",
      "day-party",
      "happy-hour",
      "festival"
    ],
    "vibesRaw": "ass shaking flirt groove karaoke live show",
    "free": false,
    "badges": [
      "After Dark",
      "Day Party",
      "Happy Hour",
      "Festival"
    ],
    "time": "6:00 PM",
    "location": "Power Plant Live · 34 Market Pl, Baltimore, MD 21202",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Groove",
      "Karaoke",
      "Live Show"
    ],
    "ctaHref": "https://www.axs.com/events/1430048/charm-city-pride-fest-tickets?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAdGRleASRZjNleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA8xMjQwMjQ1NzQyODc0MTQAAad0oxEUU2EAH1dxqxa9B7sBs9w37g_YkvixRdfrO1lAjC9S04euf__0aebbbw_aem_wOlUjf04yN7K0U66fhuZiw&utm_id=97760_v0_s00_e0_tv3",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "discountCode": "TRUE"
  },
  {
    "id": "18",
    "festival": "baltimore-pride",
    "day": "saturday",
    "dayDate": "2026-06-13",
    "dayLabel": "Saturday",
    "name": "Pride on the Pier",
    "organizer": "All Love Baltimore, Blk Ass Flea Mkt & Baltimore City LGBTQ Affairs",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking food 30+",
    "free": false,
    "badges": [
      "After Dark"
    ],
    "time": "8:00 PM",
    "location": "Hard Rock Cafe · 601 E Pratt St. Baltimore, MD 21202",
    "vibeTags": [
      "Ass Shaking",
      "Food",
      "30+"
    ],
    "ctaHref": "https://posh.vip/e/pride-on-the-pier",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "19",
    "festival": "baltimore-pride",
    "day": "saturday",
    "dayDate": "2026-06-13",
    "dayLabel": "Saturday",
    "name": "Yams: The [Pride] Function Vol. III",
    "organizer": "[The Function]",
    "types": [
      "day-party"
    ],
    "vibesRaw": "ass shaking",
    "free": false,
    "badges": [
      "Day Party"
    ],
    "time": "5:00 PM",
    "location": "Our Time Kitchen · 118 W 24th St. Baltimore, MD 21218",
    "vibeTags": [
      "Ass Shaking"
    ],
    "ctaHref": "https://ra.co/events/2452980?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAdGRleASRd4JleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA8xMjQwMjQ1NzQyODc0MTQAAacFMvElDRbFeU1VYIP7QpjZpviyFO8c3xEMethGXOR_xFZTzkyEE8565KW9_A_aem_wgW-21jnUZMIscB6o0J7AQ",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party"
  },
  {
    "id": "20",
    "festival": "baltimore-pride",
    "day": "saturday",
    "dayDate": "2026-06-13",
    "dayLabel": "Saturday",
    "name": "Pride 5K Run -Baltimore",
    "organizer": "The Pride Center of Maryland",
    "types": [
      "outdoors"
    ],
    "vibesRaw": "wellness community",
    "free": false,
    "badges": [
      "Outdoors"
    ],
    "time": "8:00 AM",
    "location": "Druid Hill Park · Chinese Pavilion on Swann Dr\nBaltimore, MD US 21217",
    "vibeTags": [
      "Wellness",
      "Community"
    ],
    "ctaHref": "https://runsignup.com/Race/MD/Baltimore/Pride5KBaltimore",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-outdoors"
  },
  {
    "id": "21",
    "festival": "baltimore-pride",
    "day": "saturday",
    "dayDate": "2026-06-13",
    "dayLabel": "Saturday",
    "name": "Baltimore Pride Parade",
    "organizer": "The Pride Center of Maryland",
    "types": [
      "outdoors-hangout",
      "festival"
    ],
    "vibesRaw": "live show community creative networking food",
    "free": true,
    "badges": [
      "Outdoors Hangout",
      "Festival",
      "Free"
    ],
    "time": "12:00 PM",
    "location": "Charles Street & North Avenue · 2900 N. Charles St. Baltimore, MD 21218",
    "vibeTags": [
      "Live Show",
      "Community",
      "Creative",
      "Networking",
      "Food"
    ],
    "ctaHref": "https://www.eventbrite.com/e/baltimore-pride-parade-tickets-1989318878316",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-outdoors-hangout"
  },
  {
    "id": "22",
    "festival": "baltimore-pride",
    "day": "saturday",
    "dayDate": "2026-06-13",
    "dayLabel": "Saturday",
    "name": "Baltimore Pride in the Park Festival (Day 1)",
    "organizer": "The Pride Center of Maryland",
    "types": [
      "festival",
      "outdoors-hangout"
    ],
    "vibesRaw": "live show community food games networking creative groove cultural",
    "free": true,
    "badges": [
      "Festival",
      "Outdoors Hangout",
      "Free"
    ],
    "time": "12:00 PM",
    "location": "Druid Hill Park · 900 Druid Park Lake Dr, Baltimore, MD 21217",
    "vibeTags": [
      "Live Show",
      "Community",
      "Food",
      "Games",
      "Networking",
      "Creative",
      "Groove",
      "Cultural"
    ],
    "ctaHref": "https://www.eventbrite.com/e/baltimore-pride-festival-block-party-in-the-park-tickets-1989318089958?aff=ebdsoporgprofile",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-festival"
  },
  {
    "id": "23",
    "festival": "baltimore-pride",
    "day": "saturday",
    "dayDate": "2026-06-13",
    "dayLabel": "Saturday",
    "name": "YewTopia",
    "organizer": "Alternative Union",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove food",
    "free": false,
    "badges": [
      "After Dark"
    ],
    "time": "8:00 PM",
    "location": "Element · 1818 Maryland Ave. Baltimore, MD 21201",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Food"
    ],
    "ctaHref": "https://posh.vip/e/yewtopia",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "24",
    "festival": "baltimore-pride",
    "day": "saturday",
    "dayDate": "2026-06-13",
    "dayLabel": "Saturday",
    "name": "Baltimore Pride Dinnner & Play",
    "organizer": "Benevolence Lifestyle Club",
    "types": [
      "after-dark",
      "meetup"
    ],
    "vibesRaw": "30+ flirt community food",
    "free": true,
    "badges": [
      "After Dark",
      "Meetup",
      "Free"
    ],
    "time": "5:00 PM",
    "location": "Kinky Cafe · 2015 N Charles St, Baltimore, MD 21218",
    "vibeTags": [
      "30+",
      "Flirt",
      "Community",
      "Food"
    ],
    "ctaHref": "https://posh.vip/e/baltimore-pride-dinner-play",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "25",
    "festival": "baltimore-pride",
    "day": "saturday",
    "dayDate": "2026-06-13",
    "dayLabel": "Saturday",
    "name": "The Biggest Afterparty of Pride Weekend",
    "organizer": "Lil Joe Events",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt",
    "free": true,
    "badges": [
      "After Dark",
      "Free"
    ],
    "time": "10:00 PM",
    "location": "Mansion · 6 E Lafayette Ave, Baltimore MD",
    "vibeTags": [
      "Ass Shaking",
      "Flirt"
    ],
    "ctaHref": "https://posh.vip/e/abc-juneteenth-mansion-pool-party?t=msmira&utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnrqjjgiL-m-cAdMsYNqEbjTn6fw1Am62DGZWK_n230cWqarEm-Gi8L5c1WpA_aem_M0jtY0fkNa52wkHiVLE-rw",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "discountCode": "TRUE"
  },
  {
    "id": "26",
    "festival": "baltimore-pride",
    "day": "sunday",
    "dayDate": "2026-06-14",
    "dayLabel": "Sunday",
    "name": "The Nude Experience",
    "organizer": "All Love Baltimore & Blk Ass Flea Mkt",
    "types": [
      "day-party"
    ],
    "vibesRaw": "grown & sexy 30+ food ass shaking",
    "free": false,
    "badges": [
      "Day Party"
    ],
    "time": "4:00 PM",
    "location": "Our Time Kitchen · 117 W 24th St. Baltimore, MD 21218",
    "vibeTags": [
      "Grown & Sexy",
      "30+",
      "Food",
      "Ass Shaking"
    ],
    "ctaHref": "https://posh.vip/e/the-nude-experience",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party"
  },
  {
    "id": "27",
    "festival": "baltimore-pride",
    "day": "sunday",
    "dayDate": "2026-06-14",
    "dayLabel": "Sunday",
    "name": "Baltimore Pride in the Park Festival (Day 2)",
    "organizer": "The Pride Center of Maryland",
    "types": [
      "outdoors-hangout",
      "festival"
    ],
    "vibesRaw": "live show community networking groove food games cultural",
    "free": true,
    "badges": [
      "Outdoors Hangout",
      "Festival",
      "Free"
    ],
    "time": "12:00 PM",
    "location": "Druid Hill Park · 901 Druid Park Lake Dr, Baltimore, MD 21217",
    "vibeTags": [
      "Live Show",
      "Community",
      "Networking",
      "Groove",
      "Food",
      "Games",
      "Cultural"
    ],
    "ctaHref": "https://www.eventbrite.com/e/baltimore-pride-in-the-park-festival-tickets-1989320163159?aff=oddtdtcreator",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-outdoors-hangout"
  },
  {
    "id": "28",
    "festival": "baltimore-pride",
    "day": "sunday",
    "dayDate": "2026-06-14",
    "dayLabel": "Sunday",
    "name": "Singles Mingle in Living Color",
    "organizer": "Dating with Tiff",
    "types": [
      "meetup"
    ],
    "vibesRaw": "flirt dating 30+",
    "free": true,
    "badges": [
      "Meetup",
      "Free"
    ],
    "time": "12:00 PM",
    "location": "Aye Gallery & Alter Studiio · 100 E 23rd St, Baltimore, MD 21218, USA",
    "vibeTags": [
      "Flirt",
      "Dating",
      "30+"
    ],
    "ctaHref": "https://posh.vip/e/singles-mingle-not-your-average-singles-mixer-3",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup"
  }
];
