/* eslint-disable */
// Auto-generated by scripts/sync-events.ts from the Google Sheets July_Events tab. Do not edit by hand.
import type { PrideEvent } from '../../types/event';

export const generatedEvents: PrideEvent[] = [
  {
    "id": "2",
    "festival": "july-events",
    "day": "thursday",
    "dayDate": "2026-07-09",
    "dayLabel": "Thursday",
    "name": "Parity Porch Concert Summer Series: Performance by Tyler Moonlight",
    "organizer": "Parity",
    "types": [
      "live-show"
    ],
    "vibesRaw": "chill creative community groove",
    "free": true,
    "price": "Free",
    "badges": [
      "Live Show",
      "Free"
    ],
    "time": "6:30 PM",
    "location": "PARITY Porch · 500 N Carrollton Ave Baltimore, MD",
    "vibeTags": [
      "Chill",
      "Creative",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://www.eventbrite.com/e/parity-porch-concert-summer-series-tickets-1989124481871?keep_tld=true",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-live-show",
    "flyerUrl": "https://www.instagram.com/p/DaGZdoMkY6V/?img_index=1",
    "city": "baltimore"
  },
  {
    "id": "3",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-18",
    "dayLabel": "Saturday",
    "name": "Lez Black Gurls presents Lez Picnic",
    "organizer": "LezBlackGurls",
    "types": [
      "meetup",
      "outdoors-hangout"
    ],
    "vibesRaw": "chill community games",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Outdoors Hangout",
      "Free"
    ],
    "time": "1:00 PM",
    "location": "West Covington Park · 101 West Cromwell Street\nBaltimore, MD 21230",
    "vibeTags": [
      "Chill",
      "Community",
      "Games"
    ],
    "ctaHref": "https://www.eventbrite.com/e/lez-black-gurls-presents-lez-picnic-tickets-1991346621350?aff=oddtdtcreator",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.instagram.com/lezblackgurlsbmore/",
    "city": "baltimore"
  },
  {
    "id": "4",
    "festival": "july-events",
    "day": "wednesday",
    "dayDate": "2026-07-01",
    "dayLabel": "Wednesday",
    "name": "LBG presents Gentle Movement & Community Connection with RestEasyBby",
    "organizer": "LezBlackGurls",
    "types": [
      "meetup",
      "workshop"
    ],
    "vibesRaw": "chill community wellness",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Workshop",
      "Free"
    ],
    "time": "7:00 PM",
    "location": "Baltimore Unity Hall · 1505 Eutaw Place\nBaltimore, MD 21217",
    "vibeTags": [
      "Chill",
      "Community",
      "Wellness"
    ],
    "ctaHref": "https://www.eventbrite.com/e/lbg-presents-gentle-movement-community-connection-with-resteasybby-tickets-1991347005499",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.instagram.com/lezblackgurlsbmore/",
    "city": "baltimore"
  },
  {
    "id": "6",
    "festival": "july-events",
    "day": "friday",
    "dayDate": "2026-07-10",
    "dayLabel": "Friday",
    "name": "Queeribbean Carnival Kickoff",
    "organizer": "Aphrodites House",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking grown & sexy groove",
    "free": false,
    "price": "$17.00",
    "badges": [
      "After Dark"
    ],
    "time": "7:00 PM",
    "location": "Nobles (2nd Floor) · 1024 S Charles St, Baltimore, MD 21230, USA",
    "vibeTags": [
      "Ass Shaking",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/queeribbean-carnival-kickoff",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "flyerUrl": "https://www.instagram.com/p/DaAxNLgOxqr/",
    "city": "baltimore"
  },
  {
    "id": "7",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-25",
    "dayLabel": "Saturday",
    "name": "Sapphic Saturdays",
    "organizer": "Aphrodites House",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "grown & sexy",
    "free": false,
    "price": "$11.00",
    "badges": [
      "After Dark"
    ],
    "time": "8:00 PM",
    "location": "The Manor · 924 N Charles St, Baltimore, MD 21201, USA",
    "vibeTags": [
      "Grown & Sexy"
    ],
    "ctaHref": "https://posh.vip/e/sapphic-saturdays-24",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "flyerUrl": "https://www.instagram.com/p/DaLISEUOYKx/",
    "city": "baltimore"
  },
  {
    "id": "8",
    "festival": "july-events",
    "day": "wednesday",
    "dayDate": "2026-07-01",
    "dayLabel": "Wednesday",
    "name": "Salsa with Pride",
    "organizer": "The Pride Center of Maryland",
    "types": [
      "workshop"
    ],
    "vibesRaw": "community cultural grown & sexy groove",
    "free": true,
    "price": "Free",
    "badges": [
      "Workshop",
      "Free"
    ],
    "time": "7:30 PM",
    "location": "The Pride Center of Maryland · 2418 Saint Paul Street\nBaltimore, MD 21218",
    "vibeTags": [
      "Community",
      "Cultural",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://www.eventbrite.com/e/salsa-with-pride-tickets-1988786376589?aff=ebdsoporgprofile",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-workshop",
    "flyerUrl": "https://www.instagram.com/p/DaLjqqxyYjb/",
    "city": "baltimore"
  },
  {
    "id": "9",
    "festival": "july-events",
    "day": "sunday",
    "dayDate": "2026-07-05",
    "dayLabel": "Sunday",
    "name": "Queer Clothing Swap",
    "organizer": "The Pride Center of Maryland",
    "types": [
      "meetup"
    ],
    "vibesRaw": "chill ass shaking",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Free"
    ],
    "time": "12:00 PM",
    "location": "The Pride Center of Maryland · 2418 Saint Paul Street\nBaltimore, MD 21218",
    "vibeTags": [
      "Chill",
      "Ass Shaking"
    ],
    "ctaHref": "https://www.instagram.com/p/DaLO-h1goj-/",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.instagram.com/p/DaLO-h1goj-/",
    "city": "baltimore"
  },
  {
    "id": "10",
    "festival": "july-events",
    "day": "thursday",
    "dayDate": "2026-07-02",
    "dayLabel": "Thursday",
    "name": "NOSTALGIA",
    "organizer": "Peazy",
    "types": [
      "happy-hour",
      "meetup"
    ],
    "vibesRaw": "30+ chill flirt community grown & sexy",
    "free": false,
    "price": "$12.51",
    "badges": [
      "Happy Hour",
      "Meetup"
    ],
    "time": "7:00 PM",
    "location": "Safari Club · 5625 O Donnell Street\nBaltimore, MD 21224",
    "vibeTags": [
      "30+",
      "Chill",
      "Flirt",
      "Community",
      "Grown & Sexy"
    ],
    "ctaHref": "https://www.eventbrite.com/e/nostalgia-72-tickets-1992778045779?aff=oddtdtcreator&utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnCves_Cq-U3qs6TcPlknZOcSCEwoxJDvneqtGSA1DnyS00wZpXpq9i-s4Zew_aem_7xas2-32YPGXtDT1SlgrkA&keep_tld=true",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-happy-hour",
    "flyerUrl": "https://www.instagram.com/p/DaLV6qVgS4E/",
    "city": "baltimore"
  },
  {
    "id": "11",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-11",
    "dayLabel": "Saturday",
    "name": "Queer Dining Series: Taste It!/ Goute li (Haiti/Ayiti – Exploring the Diaspora via Taste",
    "organizer": "PaymahCo",
    "types": [
      "meetup"
    ],
    "vibesRaw": "chill community food cultural 30+",
    "free": false,
    "price": "$84.00",
    "badges": [
      "Meetup"
    ],
    "time": "2:00 PM",
    "location": "The location will be revealed on the event date",
    "vibeTags": [
      "Chill",
      "Community",
      "Food",
      "Cultural",
      "30+"
    ],
    "ctaHref": "https://posh.vip/e/taste-it-2?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0DMTAwAHNydGMGYXBwX2lkDzkzNjYxOTc0MzM5MjQ1OQABp4MZZkmyV-C4sBAFxtlMwxJoacvU0Kmt-p53WbUK7R5PFsx9f4pFWWsgo-Lz_aem_qIRg3afFtweEc2L8zZKQBg",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "city": "dc"
  },
  {
    "id": "12",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-18",
    "dayLabel": "Saturday",
    "name": "Take Bi+ The Night",
    "organizer": "BlaQplight",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove",
    "free": false,
    "price": "$10.00",
    "badges": [
      "After Dark"
    ],
    "time": "11:00 PM",
    "location": "Mixxed Food & Drinks · 2427 18th St NW, Washington, DC 20009, USA",
    "vibeTags": [
      "Ass Shaking",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/take-bi-the-night?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnLrkROeN7N4Qs1-GjX4iSI8JPc8u4yKm0epoA8To65nhX6GNwNs2dozjHK0k_aem_e_-MNXJSgnGjagSEv6svQA",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "flyerUrl": "https://www.instagram.com/p/DaE3QWVOu-T/",
    "city": "dc"
  },
  {
    "id": "13",
    "festival": "july-events",
    "day": "friday",
    "dayDate": "2026-07-03",
    "dayLabel": "Friday",
    "name": "Fruit Punch",
    "organizer": "Transmission",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove",
    "free": false,
    "price": "$22.00",
    "badges": [
      "After Dark"
    ],
    "time": "9:00 PM",
    "location": "Transmission · 1353 H Street Northeast, Washington, DC 20002, USA",
    "vibeTags": [
      "Ass Shaking",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/fruit-punch",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "flyerUrl": "https://www.instagram.com/p/DZ8efnONF79/",
    "city": "dc"
  },
  {
    "id": "14",
    "festival": "july-events",
    "day": "tuesday",
    "dayDate": "2026-07-07",
    "dayLabel": "Tuesday",
    "name": "Sinfully-Funny: A Stand-Up Comedy Show",
    "organizer": "Montenegro Comedy",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "creative community live show",
    "free": true,
    "price": "Free",
    "badges": [
      "After Dark",
      "Free"
    ],
    "time": "6:00 PM",
    "location": "Sinners and Saints · 2309 18th Street Northwest\nWashington, DC 20009",
    "vibeTags": [
      "Creative",
      "Community",
      "Live Show"
    ],
    "ctaHref": "https://www.eventbrite.com/e/sinfully-funny-a-stand-up-comedy-show-tickets-1981351227859?aff=oddtdtcreator",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-after-dark",
    "flyerUrl": "https://www.instagram.com/p/DVJSCqajg4v/",
    "city": "dc"
  },
  {
    "id": "15",
    "festival": "july-events",
    "day": "tuesday",
    "dayDate": "2026-07-14",
    "dayLabel": "Tuesday",
    "name": "Sinfully-Funny: A Stand-Up Comedy Show",
    "organizer": "Montenegro Comedy",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "creative community live show",
    "free": true,
    "price": "Free",
    "badges": [
      "After Dark",
      "Free"
    ],
    "time": "6:00 PM",
    "location": "Sinners and Saints · 2309 18th Street Northwest\nWashington, DC 20009",
    "vibeTags": [
      "Creative",
      "Community",
      "Live Show"
    ],
    "ctaHref": "https://www.eventbrite.com/e/sinfully-funny-a-stand-up-comedy-show-tickets-1981351227859?aff=oddtdtcreator",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-after-dark",
    "flyerUrl": "https://www.instagram.com/p/DVJSCqajg4v/",
    "city": "dc"
  },
  {
    "id": "16",
    "festival": "july-events",
    "day": "tuesday",
    "dayDate": "2026-07-21",
    "dayLabel": "Tuesday",
    "name": "Sinfully-Funny: A Stand-Up Comedy Show",
    "organizer": "Montenegro Comedy",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "creative community live show",
    "free": true,
    "price": "Free",
    "badges": [
      "After Dark",
      "Free"
    ],
    "time": "6:00 PM",
    "location": "Sinners and Saints · 2309 18th Street Northwest\nWashington, DC 20009",
    "vibeTags": [
      "Creative",
      "Community",
      "Live Show"
    ],
    "ctaHref": "https://www.eventbrite.com/e/sinfully-funny-a-stand-up-comedy-show-tickets-1981351227859?aff=oddtdtcreator",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-after-dark",
    "flyerUrl": "https://www.instagram.com/p/DVJSCqajg4v/",
    "city": "dc"
  },
  {
    "id": "17",
    "festival": "july-events",
    "day": "tuesday",
    "dayDate": "2026-07-28",
    "dayLabel": "Tuesday",
    "name": "Sinfully-Funny: A Stand-Up Comedy Show",
    "organizer": "Montenegro Comedy",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "creative community live show",
    "free": true,
    "price": "Free",
    "badges": [
      "After Dark",
      "Free"
    ],
    "time": "6:00 PM",
    "location": "Sinners and Saints · 2309 18th Street Northwest\nWashington, DC 20009",
    "vibeTags": [
      "Creative",
      "Community",
      "Live Show"
    ],
    "ctaHref": "https://www.eventbrite.com/e/sinfully-funny-a-stand-up-comedy-show-tickets-1981351227859?aff=oddtdtcreator",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-after-dark",
    "flyerUrl": "https://www.instagram.com/p/DVJSCqajg4v/",
    "city": "dc"
  },
  {
    "id": "18",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-04",
    "dayLabel": "Saturday",
    "name": "Freak on a Leash 2",
    "organizer": "Sinners and Saints",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking community groove grown & sexy",
    "free": false,
    "price": "$6.00",
    "badges": [
      "After Dark"
    ],
    "time": "9:00 PM",
    "location": "Sinners and Saints · 2309 18th Street Northwest\nWashington, DC 20009",
    "vibeTags": [
      "Ass Shaking",
      "Community",
      "Groove",
      "Grown & Sexy"
    ],
    "ctaHref": "https://tixfox.co/e/XsC3wvshLr",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "flyerUrl": "https://www.instagram.com/p/DZspEO2IoHq/",
    "city": "dc"
  },
  {
    "id": "19",
    "festival": "july-events",
    "day": "thursday",
    "dayDate": "2026-07-09",
    "dayLabel": "Thursday",
    "name": "Daysha's Dancehall Fundraiser",
    "organizer": "Juno Hill",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove",
    "free": true,
    "price": "Free",
    "badges": [
      "After Dark",
      "Free"
    ],
    "time": "9:00 PM",
    "location": "Sinners and Saints · 2309 18th Street Northwest\nWashington, DC 20009",
    "vibeTags": [
      "Ass Shaking",
      "Groove"
    ],
    "ctaHref": "https://www.eventbrite.com/e/dayshas-dancehall-fundraiser-tickets-1992675030658?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&utm-source=wsa&aff=ebdsshwebmobile&fbclid=PAVERFWAStNsZwZG9mAmV4dG4DYWVtAjEwAHNydGMGYXBwX2lkDzEyNDAyNDU3NDI4NzQxNAABp-L59Ig_QaDmZoGGSjUnEdg1hamOohTD0JjRDEtkD43NbdfGffpDpNfKZ8bk_aem_qNot4vOQsaMrOV310feuGw",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-after-dark",
    "flyerUrl": "https://www.instagram.com/juno.hill/",
    "city": "dc"
  },
  {
    "id": "20",
    "festival": "july-events",
    "day": "sunday",
    "dayDate": "2026-07-12",
    "dayLabel": "Sunday",
    "name": "Heatwave",
    "organizer": "LesLinq events",
    "types": [
      "day-party"
    ],
    "vibesRaw": "ass shaking groove",
    "free": false,
    "price": "$15.30",
    "badges": [
      "Day Party"
    ],
    "time": "2:00 PM",
    "location": "The Ven at Embassy Row · 2015 Massachusetts Ave NW, Washington, DC 20036, USA",
    "vibeTags": [
      "Ass Shaking",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/heatwave-20?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnwPKgNosAYdRvEsHpMEUXp8t26zrom2ryEakK3yOgD8ruymwGQdgdOiOsRpM_aem_gmPu13sHCAq2ANUv_yoPoA",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "flyerUrl": "https://www.instagram.com/p/DaLYSnqu2Fd/",
    "city": "dc"
  },
  {
    "id": "21",
    "festival": "july-events",
    "day": "wednesday",
    "dayDate": "2026-07-15",
    "dayLabel": "Wednesday",
    "name": "DMV Dyke Camp 2026 Reunion",
    "organizer": "QueerTalk DC",
    "types": [
      "meetup"
    ],
    "vibesRaw": "community",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Free"
    ],
    "time": "6:00 PM",
    "location": "Trade · 1410 14th Street Northwest\nWashington, DC 20005",
    "vibeTags": [
      "Community"
    ],
    "ctaHref": "https://www.eventbrite.com/e/dmv-dyke-camp-2026-reunion-tickets-1992791252280?aff=oddtdtcreator&utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnoh6PXhscRo5OdfWLIVi_qOjiviLYHDF44e9wfoE6Aq356VSc0P8vx8VxhKg_aem_4GjHmJr6A9gLvEU9sLpYlA",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.instagram.com/p/DaL5powBoKv/",
    "city": "dc"
  },
  {
    "id": "22",
    "festival": "july-events",
    "day": "wednesday",
    "dayDate": "2026-07-22",
    "dayLabel": "Wednesday",
    "name": "SAPPHIC SOCIAL",
    "organizer": "QueerTalk DC",
    "types": [
      "happy-hour",
      "meetup"
    ],
    "vibesRaw": "chill community games",
    "free": false,
    "price": "$12.00",
    "badges": [
      "Happy Hour",
      "Meetup"
    ],
    "time": "6:30 PM",
    "location": "Spark Social Patio · 2009 14th St NW, Washington, DC 20009, USA",
    "vibeTags": [
      "Chill",
      "Community",
      "Games"
    ],
    "ctaHref": "https://posh.vip/e/sapphic-social-11?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnC1aXPpVqlWQgLmPqAIhbGsxdGTguw_bk205GZI-oXJF2ZNZQuuiQ4X0Bbqk_aem_1AKnFL8c3Ci7qSeJEdGTHQ",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-happy-hour",
    "flyerUrl": "https://www.instagram.com/p/DaN8ubjFGqg/?img_index=1",
    "city": "dc"
  },
  {
    "id": "23",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-25",
    "dayLabel": "Saturday",
    "name": "Dyke's Uncorked: Black Wine Country",
    "organizer": "QueerTalk DC",
    "types": [
      "happy-hour",
      "meetup",
      "workshop"
    ],
    "vibesRaw": "chill community cultural",
    "free": false,
    "price": "$75.50",
    "badges": [
      "Happy Hour",
      "Meetup",
      "Workshop"
    ],
    "time": "11:00 AM",
    "location": "Negus Winery · 5509 Vine Street #Suite A Alexandria, VA 22310",
    "vibeTags": [
      "Chill",
      "Community",
      "Cultural"
    ],
    "ctaHref": "https://www.eventbrite.com/e/dykes-uncorked-black-wine-country-tickets-1992378118586?aff=oddtdtcreator&utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGn-B0RwLarRbRHe9YxWCHO-uFRVtB98rmVj3dBbHzrMv8aaG7W_Plwo3wyJoA_aem_wcfBBUksjvzrfs-e_W_wpg",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-happy-hour",
    "flyerUrl": "https://www.instagram.com/p/DZ8GEIwlINv/?img_index=1",
    "city": "dc"
  },
  {
    "id": "24",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-25",
    "dayLabel": "Saturday",
    "name": "Sapphic Day Party",
    "organizer": "Sapphic Social DC",
    "types": [
      "meetup",
      "after-dark"
    ],
    "vibesRaw": "flirt ass shaking groove grown & sexy",
    "free": false,
    "price": "$10.00",
    "badges": [
      "Meetup",
      "After Dark"
    ],
    "time": "6:00 PM",
    "location": "Mixxed DC · 2427 18th St NW, Washington, DC 20009, USA",
    "vibeTags": [
      "Flirt",
      "Ass Shaking",
      "Groove",
      "Grown & Sexy"
    ],
    "ctaHref": "https://posh.vip/e/sapphic-day-party",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.instagram.com/p/DaOGjTlNMAJ/",
    "city": "dc"
  },
  {
    "id": "25",
    "festival": "july-events",
    "day": "sunday",
    "dayDate": "2026-07-12",
    "dayLabel": "Sunday",
    "name": "Sunday Social Brunch",
    "organizer": "Sapphic Social DC",
    "types": [
      "brunch"
    ],
    "vibesRaw": "flirt community 30+ wlw only",
    "free": true,
    "price": "Free",
    "badges": [
      "Brunch",
      "Free"
    ],
    "time": "12:00 PM",
    "location": "Mixxed DC · 2427 18th St NW, Washington, DC 20009, USA",
    "vibeTags": [
      "Flirt",
      "Community",
      "30+",
      "wlw only"
    ],
    "ctaHref": "https://posh.vip/e/sunday-social-brunch",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-brunch",
    "flyerUrl": "https://www.instagram.com/p/DZ-eSGJt_60/",
    "city": "dc"
  },
  {
    "id": "26",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-11",
    "dayLabel": "Saturday",
    "name": "Outside With The Sunflower Child",
    "organizer": "The Sunflower Child",
    "types": [
      "day-party"
    ],
    "vibesRaw": "chill groove",
    "free": true,
    "price": "Free",
    "badges": [
      "Day Party",
      "Free"
    ],
    "time": "5:00 PM",
    "location": "Mixxed DC · 2427 18th St NW, Washington, DC 20009, USA",
    "vibeTags": [
      "Chill",
      "Groove"
    ],
    "ctaHref": "https://www.eventbrite.com.au/e/outside-with-the-sunflower-child-mixxed-dc-tickets-1992731159541?utm_experiment=test_share_listing&aff=ebdsshios&utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnyPXH5ogsT6NA-Mi-FyXltiyTm2ZJB9mujHvwkaYNIsY7eDjRETG1gyTr6s0_aem_gnIgzzZj7GrDSnEACRFQ-Q&utm_id=97760_v0_s00_e0_tv3",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-day-party",
    "flyerUrl": "https://www.instagram.com/p/DaJYflTo80S/",
    "city": "dc"
  },
  {
    "id": "27",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-11",
    "dayLabel": "Saturday",
    "name": "Chimstar Pres. Birthday Rave",
    "organizer": "Transmission",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove",
    "free": false,
    "price": "$20.00",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "Transmission · 1353 H Street Northeast, Washington, DC 20002, USA",
    "vibeTags": [
      "Ass Shaking",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/chimstar",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "flyerUrl": "https://www.instagram.com/p/DZV5_-spHz-/",
    "city": "dc"
  },
  {
    "id": "28",
    "festival": "july-events",
    "day": "thursday",
    "dayDate": "2026-07-30",
    "dayLabel": "Thursday",
    "name": "Deep Cvnt: Mini Ball",
    "organizer": "Girliepopdc",
    "types": [
      "after-dark",
      "ball"
    ],
    "vibesRaw": "ass shaking groove live show",
    "free": true,
    "price": "Free",
    "badges": [
      "After Dark",
      "Ball",
      "Free"
    ],
    "time": "9:00 PM",
    "location": "Crush Dance Bar · 2007 14th St NW, Washington, DC 20009",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Live Show"
    ],
    "ctaHref": "https://www.instagram.com/deepcvntparty/",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-after-dark",
    "flyerUrl": "https://www.instagram.com/p/DGdseIhOV3V/",
    "city": "dc"
  },
  {
    "id": "29",
    "festival": "july-events",
    "day": "wednesday",
    "dayDate": "2026-07-01",
    "dayLabel": "Wednesday",
    "name": "LADIES LOVE R&B ❤️",
    "organizer": "MIM ENTERTAINMENT",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt groove",
    "free": true,
    "price": "Free",
    "badges": [
      "After Dark",
      "Free"
    ],
    "time": "9:00 PM",
    "location": "Saint Ex · 1847 14th St NW, Washington, DC 20009, USA",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/ladies-love-rb--19?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnqdXW6JASJMZGxE1y9hNaEuHRarwjXOhL4b0dOfG4P6MC1n2M788--pt-3Yk_aem_APAzozLWVqpr22_Fj9sUMw",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-after-dark",
    "flyerUrl": "https://www.instagram.com/p/DaEdv5xDRQK/?img_index=1",
    "city": "dc"
  },
  {
    "id": "30",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-18",
    "dayLabel": "Saturday",
    "name": "Macrame Plant Hanger Workshop",
    "organizer": "Venusian Knots",
    "types": [
      "workshop"
    ],
    "vibesRaw": "creative community",
    "free": false,
    "price": "$45.00",
    "badges": [
      "Workshop"
    ],
    "time": "2:00 PM",
    "location": "Creative Grounds DC · 1822 North Capitol Street Northwest\nWashington, DC 20002",
    "vibeTags": [
      "Creative",
      "Community"
    ],
    "ctaHref": "https://www.eventbrite.com/e/macrame-plant-hanger-workshop-tickets-1992782024680?aff=oddtdtcreator&utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnM3DrVGZzMnrESa4IBxr83zU37UUJYpAgbWMkoNwxd3nhL_TsJLx6W_dDyNM_aem_V-3aee7zb1g8Z7yILR3yhw&keep_tld=true",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-workshop",
    "flyerUrl": "https://www.instagram.com/p/DaLs-0_CeTX/?img_index=1",
    "city": "dc"
  },
  {
    "id": "31",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-18",
    "dayLabel": "Saturday",
    "name": "GATHER July Edition: A Monthly Mixtape Sapphic Tea Dance & Social",
    "organizer": "Mixtape Sapphics",
    "types": [
      "happy-hour",
      "meetup"
    ],
    "vibesRaw": "chill flirt community 30+ groove",
    "free": false,
    "price": "$15.50",
    "badges": [
      "Happy Hour",
      "Meetup"
    ],
    "time": "5:00 PM",
    "location": "Spark Social · 2009 14th Street Northwest\nWashington, DC 20009",
    "vibeTags": [
      "Chill",
      "Flirt",
      "Community",
      "30+",
      "Groove"
    ],
    "ctaHref": "https://www.eventbrite.com/o/mixtape-sapphics-110074518471?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnoDLhj6aYfHmz6Tw5808JhFQcVu59uGoW2_wftto-vl7L4WNaZCznTtBXZL4_aem_uP2v-qxZvY-KbMJCaABT-A",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-happy-hour",
    "flyerUrl": "https://www.instagram.com/p/DaMDl8hjpiw/?img_index=1",
    "city": "dc"
  },
  {
    "id": "32",
    "festival": "july-events",
    "day": "sunday",
    "dayDate": "2026-07-19",
    "dayLabel": "Sunday",
    "name": "Remix OUTings: Summer Sunday 2026 Edition",
    "organizer": "Mixtape Sapphics",
    "types": [
      "meetup",
      "brunch",
      "outdoors-hangout",
      "workshop"
    ],
    "vibesRaw": "chill community networking creative flirt",
    "free": false,
    "price": "$115.00",
    "badges": [
      "Meetup",
      "Brunch",
      "Outdoors Hangout",
      "Workshop"
    ],
    "time": "5:00 PM",
    "location": "Mixxed DC · 2427 18th Street Northwest\nWashington, DC 20009",
    "vibeTags": [
      "Chill",
      "Community",
      "Networking",
      "Creative",
      "Flirt"
    ],
    "ctaHref": "https://www.eventbrite.com/e/remix-outings-summer-sunday-2026-edition-tickets-1992468046563?aff=ebdsoporgprofile",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.instagram.com/p/DaMDl8hjpiw/?img_index=1",
    "city": "dc"
  },
  {
    "id": "33",
    "festival": "july-events",
    "day": "thursday",
    "dayDate": "2026-07-02",
    "dayLabel": "Thursday",
    "name": "Here: Pride and Belonging in African Art",
    "organizer": "National Museum of African Art",
    "types": [
      "educational"
    ],
    "vibesRaw": "chill creative cultural",
    "free": true,
    "price": "Free",
    "badges": [
      "Educational",
      "Free"
    ],
    "time": "10:00 AM",
    "location": "National Museum of African Art · 950 Independence Avenue, SW\nWashington, DC 20560",
    "vibeTags": [
      "Chill",
      "Creative",
      "Cultural"
    ],
    "ctaHref": "https://africa.si.edu/exhibitions/here-pride-and-belonging-african-art",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-educational",
    "flyerUrl": "https://www.instagram.com/p/DZsaqUTFBpH/?img_index=1",
    "city": "dc"
  },
  {
    "id": "34",
    "festival": "july-events",
    "day": "wednesday",
    "dayDate": "2026-07-29",
    "dayLabel": "Wednesday",
    "name": "Hump Day Cheers",
    "organizer": "BlackDMVSapphics",
    "types": [
      "happy-hour"
    ],
    "vibesRaw": "food flirt community",
    "free": true,
    "price": "Free",
    "badges": [
      "Happy Hour",
      "Free"
    ],
    "time": "5:30 PM",
    "location": "Shanklin Hall · 2325 18th St NW, Washington, DC 20009, USA",
    "vibeTags": [
      "Food",
      "Flirt",
      "Community"
    ],
    "ctaHref": "https://posh.vip/e/midweek-happy-hour?u=dvn__a&_t=mr3vw6op&os=web&src=event_page",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-happy-hour",
    "city": "dc"
  },
  {
    "id": "35",
    "festival": "july-events",
    "day": "friday",
    "dayDate": "2026-07-17",
    "dayLabel": "Friday",
    "name": "The 'Cule Club - a polyam/ENM meet up",
    "organizer": "Dee René",
    "types": [
      "meetup"
    ],
    "vibesRaw": "chill flirt community 30+ grown & sexy groove polyamorous",
    "free": false,
    "price": "$15.00",
    "badges": [
      "Meetup"
    ],
    "time": "6:30 PM",
    "location": "The Muni · 1400 14th St NW Ste B, Washington, DC 20005, USA",
    "vibeTags": [
      "Chill",
      "Flirt",
      "Community",
      "30+",
      "Grown & Sexy",
      "Groove",
      "Polyamorous"
    ],
    "ctaHref": "https://posh.vip/e/the-cule-club-a-polyamenm-meet-up",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "city": "dc"
  },
  {
    "id": "36",
    "festival": "july-events",
    "day": "friday",
    "dayDate": "2026-07-17",
    "dayLabel": "Friday",
    "name": "After Hours Leather Society: Open House",
    "organizer": "After Hours Leather Society",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt community grown & sexy groove polyamorous",
    "free": true,
    "price": "Free",
    "badges": [
      "After Dark",
      "Free"
    ],
    "time": "7:30 PM",
    "location": "Please register to see the exact location of this event. · O St. NW",
    "vibeTags": [
      "Flirt",
      "Community",
      "Grown & Sexy",
      "Groove",
      "Polyamorous"
    ],
    "ctaHref": "https://api.leadconnectorhq.com/widget/form/LF1nfP6EGb2Nx0h381zu",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-after-dark",
    "flyerUrl": "https://www.instagram.com/p/DTnyY1skfiV/?hl=en",
    "city": "dc"
  },
  {
    "id": "37",
    "festival": "july-events",
    "day": "sunday",
    "dayDate": "2026-07-26",
    "dayLabel": "Sunday",
    "name": "Art-Making Club Artist Workshop",
    "organizer": "The Sapphic Sanctuary",
    "types": [
      "workshop"
    ],
    "vibesRaw": "creative community",
    "free": true,
    "price": "Free",
    "badges": [
      "Workshop",
      "Free"
    ],
    "time": "2:00 PM",
    "location": "Francis Gregory Neighborhood Library · 3660 Alabama Ave SE, Washington, DC",
    "vibeTags": [
      "Creative",
      "Community"
    ],
    "ctaHref": "https://docs.google.com/forms/d/e/1FAIpQLSdyoMIAw1uGukj-LVm04qgTcctCSpJE0ukRUdNzJG6Xxn5J2w/viewform",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-workshop",
    "flyerUrl": "https://www.instagram.com/p/Dabcksnlm3j/?img_index=1",
    "city": "dc"
  },
  {
    "id": "38",
    "festival": "july-events",
    "day": "wednesday",
    "dayDate": "2026-07-29",
    "dayLabel": "Wednesday",
    "name": "Tongue Twisted",
    "organizer": "Dame Sadie",
    "types": [
      "workshop",
      "educational",
      "meetup"
    ],
    "vibesRaw": "creative flirt community grown & sexy wlw only",
    "free": false,
    "price": "$25.00",
    "badges": [
      "Workshop",
      "Educational",
      "Meetup"
    ],
    "time": "7:00 PM",
    "location": "Mixxed DC · 2427 18th Street Northwest\nWashington, DC 20009",
    "vibeTags": [
      "Creative",
      "Flirt",
      "Community",
      "Grown & Sexy",
      "wlw only"
    ],
    "ctaHref": "https://damesadie.com/events",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-workshop",
    "flyerUrl": "https://www.instagram.com/p/Dah9jjyFchD/?img_index=1",
    "city": "dc"
  },
  {
    "id": "40",
    "festival": "july-events",
    "day": "friday",
    "dayDate": "2026-07-10",
    "dayLabel": "Friday",
    "name": "Rumba Queer: Rueda de Casino Workshop",
    "organizer": "Rumba Queer DC",
    "types": [
      "meetup",
      "workshop"
    ],
    "vibesRaw": "creative groove community",
    "free": false,
    "price": "$23.00",
    "badges": [
      "Meetup",
      "Workshop"
    ],
    "time": "7:00 PM",
    "location": "Dance Loft on 14 · 4618 14th St NW, Washington, DC 20011, USA",
    "vibeTags": [
      "Creative",
      "Groove",
      "Community"
    ],
    "ctaHref": "https://posh.vip/e/rumba-queer-rueda-de-casino-workshop?t=lt",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.instagram.com/p/DaOJrMuj1zs/?img_index=1",
    "city": "dc"
  },
  {
    "id": "41",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-18",
    "dayLabel": "Saturday",
    "name": "Verano de Vuelta",
    "organizer": "Rumba Queer DC",
    "types": [
      "after-dark",
      "workshop"
    ],
    "vibesRaw": "groove ass shaking",
    "free": true,
    "price": "Free",
    "badges": [
      "After Dark",
      "Workshop",
      "Free"
    ],
    "time": "7:00 PM",
    "location": "Icon DC · 2001 11th St NW, Washington, DC 20001, USA",
    "vibeTags": [
      "Groove",
      "Ass Shaking"
    ],
    "ctaHref": "https://posh.vip/e/verano-de-vuelta?t=lt",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-after-dark",
    "city": "dc"
  },
  {
    "id": "42",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-11",
    "dayLabel": "Saturday",
    "name": "Rumba Queer: 3 Week Beginner Bachata Series",
    "organizer": "Rumba Queer DC",
    "types": [
      "meetup",
      "workshop"
    ],
    "vibesRaw": "creative groove community",
    "free": false,
    "price": "$18.00",
    "badges": [
      "Meetup",
      "Workshop"
    ],
    "time": "6:00 PM",
    "location": "Dance Loft on 14 · 4618 14th St NW, Washington, DC 20011, USA",
    "vibeTags": [
      "Creative",
      "Groove",
      "Community"
    ],
    "ctaHref": "https://posh.vip/e/rumba-queer-3-week-beginner-bachata-series-2?t=lt",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.instagram.com/p/DaO4IPcM9hb/",
    "city": "dc"
  },
  {
    "id": "43",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-11",
    "dayLabel": "Saturday",
    "name": "Soft and Seen: A Cuddle and Consent Experience for Fem 4 Fem Black Lesbians & Bisexual Women",
    "organizer": "DMV Black Feme 4 Feme",
    "types": [
      "workshop",
      "meetup"
    ],
    "vibesRaw": "community chill wlw only",
    "free": false,
    "price": "$35.00",
    "badges": [
      "Workshop",
      "Meetup"
    ],
    "time": "6:00 PM",
    "location": "Mixxed DC · 2427 18th Street Northwest\nWashington, DC 20009",
    "vibeTags": [
      "Community",
      "Chill",
      "wlw only"
    ],
    "ctaHref": "https://events.eventnoire.com/e/soft-and-seen-a-cuddle-and-consent-experience-for",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-workshop",
    "flyerUrl": "https://www.instagram.com/p/DaBlw3mgcKx/",
    "city": "dc"
  },
  {
    "id": "44",
    "festival": "july-events",
    "day": "friday",
    "dayDate": "2026-07-24",
    "dayLabel": "Friday",
    "name": "The LinqUp: Summer Edition Sunset Series",
    "organizer": "LesLinq",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt community ass shaking groove",
    "free": false,
    "price": "$8.00",
    "badges": [
      "After Dark"
    ],
    "time": "6:00 PM",
    "location": "Electric Cool-Aid · 512 Rhode Island Ave NW, Washington, DC 20001, USA",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/the-linqup-summer-edition-sunset-series?u=tyravaughn243&_t=mrmbqnuo&os=ios&src=event_page&utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnIYtxBqUVFXR35WAo78BDhYtKZkdbM9MmzFMLleX_vUVYBlyFmVJpUH98onU_aem_zQQOZ4nYjXUQm75Visa6aQ",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "discountCode": "Two Giveaway Tickets",
    "flyerUrl": "https://www.instagram.com/p/Da0jB_5DjD2/?img_index=1",
    "city": "dc"
  },
  {
    "id": "45",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-18",
    "dayLabel": "Saturday",
    "name": "To be determined: a Black queer portrait exhibition + happy hour",
    "organizer": "Morganeliz",
    "types": [
      "meetup",
      "live-show"
    ],
    "vibesRaw": "chill creative community live show",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Live Show",
      "Free"
    ],
    "time": "6:00 PM",
    "location": "miXt Food Hall · 3809 Rhode Island Avenue\nBrentwood, MD 20722",
    "vibeTags": [
      "Chill",
      "Creative",
      "Community",
      "Live Show"
    ],
    "ctaHref": "https://www.eventbrite.com/e/to-be-determined-a-black-queer-portrait-exhibition-happy-hour-tickets-1992166238848?aff=oddtdtcreator&keep_tld=true",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.instagram.com/p/DaBcRSyPz0H/",
    "city": "dmv"
  },
  {
    "id": "46",
    "festival": "july-events",
    "day": "tuesday",
    "dayDate": "2026-07-07",
    "dayLabel": "Tuesday",
    "name": "Author Event: Colorism by Dr. Sarah L. Webb in Conversation with Eboni K. Williams",
    "organizer": "Gladys Books & Wine",
    "types": [
      "meetup",
      "live-show",
      "educational"
    ],
    "vibesRaw": "creative networking community",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Live Show",
      "Educational",
      "Free"
    ],
    "time": "7:00 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Blvd, Brooklyn, NY 11233, USA",
    "vibeTags": [
      "Creative",
      "Networking",
      "Community"
    ],
    "ctaHref": "https://luma.com/colorism",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.instagram.com/p/DZ3Jp63lC8P/?img_index=1",
    "city": "nyc"
  },
  {
    "id": "47",
    "festival": "july-events",
    "day": "thursday",
    "dayDate": "2026-07-09",
    "dayLabel": "Thursday",
    "name": "Black Girls Cinema Club presents Coffee & Conversation: a film theory workshop on Bessie\nEven Timings",
    "organizer": "Gladys Books & Wine",
    "types": [
      "meetup",
      "workshop",
      "educational"
    ],
    "vibesRaw": "creative networking community",
    "free": false,
    "price": "$15.00",
    "badges": [
      "Meetup",
      "Workshop",
      "Educational"
    ],
    "time": "6:00 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Blvd, Brooklyn, NY 11233, USA",
    "vibeTags": [
      "Creative",
      "Networking",
      "Community"
    ],
    "ctaHref": "https://luma.com/Black-Girl-Cinema-Club",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.instagram.com/p/DaLMTSJxgjs/",
    "city": "nyc"
  },
  {
    "id": "48",
    "festival": "july-events",
    "day": "friday",
    "dayDate": "2026-07-10",
    "dayLabel": "Friday",
    "name": "A Black Feminist Climate Arts Salon Presented by the Climate Museum",
    "organizer": "Gladys Books & Wine",
    "types": [
      "meetup",
      "workshop",
      "educational"
    ],
    "vibesRaw": "creative networking community",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Workshop",
      "Educational",
      "Free"
    ],
    "time": "6:30 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Blvd, Brooklyn, NY 11233, USA",
    "vibeTags": [
      "Creative",
      "Networking",
      "Community"
    ],
    "ctaHref": "https://www.climatemuseum.org/events/a-black-feminist-climate-arts-salon",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "city": "nyc"
  },
  {
    "id": "49",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-11",
    "dayLabel": "Saturday",
    "name": "Monthly Collage Series + WNBA Watch Party with Fitted WBB, the Living Lesbian Archive, For Them and Autostraddle",
    "organizer": "For Them + Autostraddle",
    "types": [
      "meetup",
      "workshop"
    ],
    "vibesRaw": "creative community",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Workshop",
      "Free"
    ],
    "time": "1:00 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Blvd, Brooklyn, NY 11233, USA",
    "vibeTags": [
      "Creative",
      "Community"
    ],
    "ctaHref": "https://www.gladysbooksandwine.com/pages/events#?event-id=84452",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "city": "nyc"
  },
  {
    "id": "50",
    "festival": "july-events",
    "day": "friday",
    "dayDate": "2026-07-17",
    "dayLabel": "Friday",
    "name": "Author Event: Free Girls by Kristen McCallum in Conversation with Jennifer Baker",
    "organizer": "Gladys Books & Wine",
    "types": [
      "meetup",
      "educational"
    ],
    "vibesRaw": "creative networking community",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Educational",
      "Free"
    ],
    "time": "6:30 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Blvd, Brooklyn, NY 11233, USA",
    "vibeTags": [
      "Creative",
      "Networking",
      "Community"
    ],
    "ctaHref": "https://luma.com/Free-Girls",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "city": "nyc"
  },
  {
    "id": "51",
    "festival": "july-events",
    "day": "thursday",
    "dayDate": "2026-07-23",
    "dayLabel": "Thursday",
    "name": "Somatic Perimenopause - The Peri Portal: Why What's Working Isn't Working Anymore",
    "organizer": "Gladys Books & Wine",
    "types": [
      "meetup",
      "educational"
    ],
    "vibesRaw": "creative networking community",
    "free": false,
    "price": "$25.00",
    "badges": [
      "Meetup",
      "Educational"
    ],
    "time": "6:30 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Blvd, Brooklyn, NY 11233, USA",
    "vibeTags": [
      "Creative",
      "Networking",
      "Community"
    ],
    "ctaHref": "https://luma.com/bohjkjdc",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "city": "nyc"
  },
  {
    "id": "52",
    "festival": "july-events",
    "day": "thursday",
    "dayDate": "2026-07-30",
    "dayLabel": "Thursday",
    "name": "Unsent: An Evening of Letter Writing & Reflection",
    "organizer": "Broken Hearts Restored",
    "types": [
      "meetup",
      "educational"
    ],
    "vibesRaw": "creative networking community wellness",
    "free": false,
    "price": "$15.00",
    "badges": [
      "Meetup",
      "Educational"
    ],
    "time": "7:00 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Blvd, Brooklyn, NY 11233, USA",
    "vibeTags": [
      "Creative",
      "Networking",
      "Community",
      "Wellness"
    ],
    "ctaHref": "https://luma.com/unsent",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "city": "nyc"
  },
  {
    "id": "53",
    "festival": "july-events",
    "day": "wednesday",
    "dayDate": "2026-07-01",
    "dayLabel": "Wednesday",
    "name": "The ANTICRASTINATION",
    "organizer": "sociaLight social club",
    "types": [
      "meetup",
      "workshop"
    ],
    "vibesRaw": "creative networking community",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Workshop",
      "Free"
    ],
    "time": "5:00 PM",
    "location": "Saint James Libations · 269 Stanhope St, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Creative",
      "Networking",
      "Community"
    ],
    "ctaHref": "https://posh.vip/e/the-anticrastination-1",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.instagram.com/p/DaL9dkdEagh/?img_index=1",
    "city": "nyc"
  },
  {
    "id": "54",
    "festival": "july-events",
    "day": "thursday",
    "dayDate": "2026-07-02",
    "dayLabel": "Thursday",
    "name": "Ladies Night Happy Hour",
    "organizer": "Nine11",
    "types": [
      "happy-hour"
    ],
    "vibesRaw": "chill ass shaking grown & sexy groove",
    "free": true,
    "price": "Free",
    "badges": [
      "Happy Hour",
      "Free"
    ],
    "time": "6:00 PM",
    "location": "Saint James Libations · 269 Stanhope St, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Chill",
      "Ass Shaking",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://partiful.com/e/BxAtuBl2mjENGM83GJyv?",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-happy-hour",
    "flyerUrl": "https://www.instagram.com/p/DaL9dkdEagh/?img_index=1",
    "city": "nyc"
  },
  {
    "id": "55",
    "festival": "july-events",
    "day": "friday",
    "dayDate": "2026-07-03",
    "dayLabel": "Friday",
    "name": "Lovergirl After Dark",
    "organizer": "Lovergurl",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt groove grown & sexy",
    "free": true,
    "price": "Free",
    "badges": [
      "After Dark",
      "Free"
    ],
    "time": "10:00 PM",
    "location": "Saint James Libations · 269 Stanhope St, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Groove",
      "Grown & Sexy"
    ],
    "ctaHref": "https://posh.vip/e/lovergirl-after-dark",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-after-dark",
    "flyerUrl": "https://www.instagram.com/p/DaL9dkdEagh/?img_index=1",
    "city": "nyc"
  },
  {
    "id": "56",
    "festival": "july-events",
    "day": "sunday",
    "dayDate": "2026-07-05",
    "dayLabel": "Sunday",
    "name": "Blacker The Berry: Live @ Saint James Libations - 7/5",
    "organizer": "Sun Phillage Productions",
    "types": [
      "live-show",
      "after-dark"
    ],
    "vibesRaw": "groove grown & sexy flirt",
    "free": false,
    "price": "$23.00",
    "badges": [
      "Live Show",
      "After Dark"
    ],
    "time": "8:00 PM",
    "location": "Saint James Libations · 269 Stanhope St, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Groove",
      "Grown & Sexy",
      "Flirt"
    ],
    "ctaHref": "https://sickening.events/e/blackertheberry-saintjames/tickets?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZnRzaASvknBwZG9mAmV4dG4DYWVtAjExAHNydGMGYXBwX2lkDzEyNDAyNDU3NDI4NzQxNAABp85ZGEXMeT2xmERUKNWZa_vs5yX_x5N4qkHC2G2umG16fwD3_3sc2qej0_DM_aem_iNrLvn2gca4OeVeYImNTRw",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-live-show",
    "flyerUrl": "https://www.instagram.com/p/DaL9dkdEagh/?img_index=1",
    "city": "nyc"
  },
  {
    "id": "126",
    "festival": "july-events",
    "day": "sunday",
    "dayDate": "2026-07-26",
    "dayLabel": "Sunday",
    "name": "Chocolate City Swim",
    "organizer": "Party Girls by DJ Fay",
    "types": [
      "pool"
    ],
    "vibesRaw": "community flirt food",
    "free": false,
    "price": "$18.00",
    "badges": [
      "Pool"
    ],
    "time": "2:00 PM",
    "location": "Tag Rooftop Bar at The Ven at Embassy Row · 2015 Massachusetts Ave NW, Washington, DC 20036, USA",
    "vibeTags": [
      "Community",
      "Flirt",
      "Food"
    ],
    "ctaHref": "https://posh.vip/e/partygirl-chocolate-city-swim-event?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnQukih-kxjUVJ3jV_1L4JR3lCOVJRbqX-m-YI6VdxcH0xAF6V2TVznpKIPBs_aem_vtW2qYxNRBnQPmKu8i-ORA",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-pool",
    "flyerUrl": "https://www.instagram.com/p/DadsA3uKc1n/",
    "city": "dc"
  },
  {
    "id": "127",
    "festival": "july-events",
    "day": "sunday",
    "dayDate": "2026-07-12",
    "dayLabel": "Sunday",
    "name": "Les Linq’s Book Club",
    "organizer": "Les Linq",
    "types": [],
    "vibesRaw": "",
    "free": true,
    "price": "Free",
    "badges": [
      "Free"
    ],
    "time": "2:00 PM",
    "location": "MLK Library · 901 G St NW, Washington, DC 20001",
    "vibeTags": [],
    "ctaHref": "https://web.groupme.com/join_group/115747585/SCBHdPQm?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGn9sKUe9UZgu8r5Sz2e9_AyJfPvQquoY05uiJrx3Xdt0G7GX1KYloe2LEJVqo_aem_3p8yEBhKDfagVm4fxymd9A",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-day-party",
    "flyerUrl": "https://www.instagram.com/p/DYmlj6gxKui/",
    "city": "dc"
  },
  {
    "id": "128",
    "festival": "july-events",
    "day": "sunday",
    "dayDate": "2026-07-12",
    "dayLabel": "Sunday",
    "name": "Heatwave",
    "organizer": "Les Linq",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "badges": [],
    "time": "",
    "location": "DC",
    "vibeTags": [],
    "ctaHref": "https://posh.vip/e/heatwave-20?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnFZHXncS_fDIGJy4rv6wuUwoGhtiALUE3Uz0iUbHFew8ijutiGmwQNysYNhk_aem_bExrBkcDXD_bwiFvQA1Wfg",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "dc"
  },
  {
    "id": "129",
    "festival": "july-events",
    "day": "sunday",
    "dayDate": "2026-07-12",
    "dayLabel": "Sunday",
    "name": "Lavendar Evolutions Book Club",
    "organizer": "Lavendar Evolutions",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "badges": [],
    "time": "",
    "location": "DC",
    "vibeTags": [],
    "ctaHref": "https://bookclubs.com/clubs/6019622/join/c56cf2?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGni75adVQ1HZSDAhixnuCyTvDSHBvagiDyac-Bow8_gLREvbh-XwVHHoxy5d0_aem_ZmFrZWR1bW15MTZieXRlcw",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "dc"
  },
  {
    "id": "130",
    "festival": "july-events",
    "day": "sunday",
    "dayDate": "2026-07-26",
    "dayLabel": "Sunday",
    "name": "BRUNCH & BADDIES MANSION POOL PARTY",
    "organizer": "TMS Entertainment DC",
    "types": [
      "day-party",
      "pool"
    ],
    "vibesRaw": "chill flirt grown & sexy food",
    "free": false,
    "price": "$34.00",
    "badges": [
      "Day Party",
      "Pool"
    ],
    "time": "3:00 PM",
    "location": "TBD",
    "vibeTags": [
      "Chill",
      "Flirt",
      "Grown & Sexy",
      "Food"
    ],
    "ctaHref": "https://www.eventbrite.com/e/brunch-baddies-mansion-pool-party-tickets-1993505567817?aff=oddtdtcreator&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnhkeiO9XbWWNHb_65r7g3uPmLlQ_XNiCxZdyMlB_XEAybSst6Sid8V9PfU7Q_aem_hBOwaGdjW0Rxl14scHeprw&utm_content=link_in_bio&utm_medium=social&utm_source=ig",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "dc"
  },
  {
    "id": "131",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-25",
    "dayLabel": "Saturday",
    "name": "WNBA ALL STAR WATCH PARTY",
    "organizer": "The Frequency Class",
    "types": [
      "meetup"
    ],
    "vibesRaw": "food networking groove",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Free"
    ],
    "time": "9:00 PM",
    "location": "Public Bar Live · 1214 18th St NW Washington, DC 20036",
    "vibeTags": [
      "Food",
      "Networking",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/wnba-all-star-watch-party-3?u=kiddfresh&_t=mrc86jrc&os=web&src=event_page&utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnWokQQQjVEHTp0TT71h0VUbhJaKQHPaPAS4KarWx7d5Va0yXyHVJ4a1dEy9M_aem_R-lqosRAhQm1dgnWthcZdg",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "city": "dc"
  },
  {
    "id": "133",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-25",
    "dayLabel": "Saturday",
    "name": "Virtual Intuitive Movement: A Grounding & Embodiment Experience with Dr. Udim Isang",
    "organizer": "Lesbifriends Travel",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "badges": [],
    "time": "",
    "location": "DC",
    "vibeTags": [],
    "ctaHref": "https://www.lesbifriendstravel.com/events/virtual-intuitive-movement",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "dc"
  },
  {
    "id": "134",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-18",
    "dayLabel": "Saturday",
    "name": "Slippery When Wet 4.0: Evening Edition",
    "organizer": "Lesbifriends Travel",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "badges": [],
    "time": "",
    "location": "DC",
    "vibeTags": [],
    "ctaHref": "https://www.lesbifriendstravel.com/events/slippery-when-wet-4-evening-edition",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "dc"
  },
  {
    "id": "135",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-18",
    "dayLabel": "Saturday",
    "name": "Slippery When Wet 4.0: Day Party",
    "organizer": "Lesbifriends Travel",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "badges": [],
    "time": "",
    "location": "DC",
    "vibeTags": [],
    "ctaHref": "https://www.lesbifriendstravel.com/events/slippery-when-wet-4-day-party",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "dc"
  },
  {
    "id": "136",
    "festival": "july-events",
    "day": "saturday",
    "dayDate": "2026-07-18",
    "dayLabel": "Saturday",
    "name": "MUSE! Hike",
    "organizer": "The Big Kids Club",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "badges": [],
    "time": "",
    "location": "DC",
    "vibeTags": [],
    "ctaHref": "https://posh.vip/e/muse-hike?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnmyFjTHGxfDcjugwR3xj4R04WhfuwojucOvOpo2UhgqykHHUIBJSuu0j_afE_aem_NTfzkcO9NGQ0jgyvBV1muw",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "dc"
  }
];
