/* eslint-disable */
// Auto-generated by scripts/sync-events.ts from the Google Sheets June 2026 tab. Do not edit by hand.
import type { PrideEvent } from '../../types/event';

export const generatedEvents: PrideEvent[] = [
  {
    "id": "2",
    "festival": "june-2026",
    "day": "tuesday",
    "dayDate": "2026-06-23",
    "dayLabel": "Tuesday",
    "name": "Hot Spur at Dew Drop",
    "organizer": "Hot Spur Line Dance",
    "types": [
      "meetup",
      "workshop"
    ],
    "vibesRaw": "chill flirt community",
    "free": false,
    "price": "$13.00",
    "badges": [
      "Meetup",
      "Workshop"
    ],
    "time": "7:00 PM",
    "location": "The Dew Drop Inn · 2801 8th Street Northeast\nWashington, DC 20017",
    "vibeTags": [
      "Chill",
      "Flirt",
      "Community"
    ],
    "ctaHref": "https://www.eventbrite.com/e/hot-spur-at-dew-drop-tickets-1991200873414?aff=oddtdtcreator",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup"
  },
  {
    "id": "3",
    "festival": "june-2026",
    "day": "wednesday",
    "dayDate": "2026-06-24",
    "dayLabel": "Wednesday",
    "name": "Open Decks",
    "organizer": "Mixxed DC",
    "types": [
      "happy-hour"
    ],
    "vibesRaw": "chill flirt groove",
    "free": true,
    "price": "Free",
    "badges": [
      "Happy Hour",
      "Free"
    ],
    "time": "6:00 PM",
    "location": "Mixxed DC · 2427 18th St NW, Washington, DC 20009",
    "vibeTags": [
      "Chill",
      "Flirt",
      "Groove"
    ],
    "ctaHref": "https://www.instagram.com/p/DZoKMykFL_U/?img_index=1",
    "ctaLabel": "More Info",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-happy-hour"
  },
  {
    "id": "4",
    "festival": "june-2026",
    "day": "thursday",
    "dayDate": "2026-06-25",
    "dayLabel": "Thursday",
    "name": "The Kickback: Hobby night and book swap",
    "organizer": "Dee Rene",
    "types": [
      "meetup"
    ],
    "vibesRaw": "chill community creative",
    "free": false,
    "price": "$5.00",
    "badges": [
      "Meetup"
    ],
    "time": "6:30 PM",
    "location": "Urban Garden · Washington DC",
    "vibeTags": [
      "Chill",
      "Community",
      "Creative"
    ],
    "ctaHref": "https://posh.vip/e/the-kickback-bring-your-own-hobby-and-book-swap",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup"
  },
  {
    "id": "5",
    "festival": "june-2026",
    "day": "friday",
    "dayDate": "2026-06-26",
    "dayLabel": "Friday",
    "name": "One Last Toast to HER — Pride Edition (30+)",
    "organizer": "With Love, Leah + Nice To Meet HER",
    "types": [
      "happy-hour",
      "meetup"
    ],
    "vibesRaw": "chill community flirt",
    "free": false,
    "price": "$25.00",
    "badges": [
      "Happy Hour",
      "Meetup"
    ],
    "time": "8:00 PM",
    "location": "Mixxed DC · 2427 18th St NW, Washington, DC 20009",
    "vibeTags": [
      "Chill",
      "Community",
      "Flirt"
    ],
    "ctaHref": "https://posh.vip/e/pride-close-out-for-her?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnEi8d3UlenW7oTvEt_RXF8-hOqg3t-5Oi7BvZlpoGSH194QKXu7XDd8iT_eg_aem_HxdgU8FslWt8ZU7GFgGVVg",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-happy-hour"
  },
  {
    "id": "6",
    "festival": "june-2026",
    "day": "friday",
    "dayDate": "2026-06-26",
    "dayLabel": "Friday",
    "name": "BOOMscat presents: In that Order, A Break from the Chaos",
    "organizer": "BOOMscat",
    "types": [
      "live-show"
    ],
    "vibesRaw": "groove grown & sexy",
    "free": false,
    "price": "$35.00",
    "badges": [
      "Live Show"
    ],
    "time": "7:00 PM",
    "location": "Blues Alley Jazz Supper Club · 1073 Wisconsin Ave NW 1st Floor, Washington, DC 20007",
    "vibeTags": [
      "Groove",
      "Grown & Sexy"
    ],
    "ctaHref": "https://www.instantseats.com/index.cfm?fuseaction=buy.event&eventID=1B5B210C-C3AB-0773-BD9BD83174D76A1F",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-live-show"
  },
  {
    "id": "7",
    "festival": "june-2026",
    "day": "friday",
    "dayDate": "2026-06-26",
    "dayLabel": "Friday",
    "name": "BOOMscat presents: In that Order, A Break from the Chaos",
    "organizer": "BOOMscat",
    "types": [
      "live-show"
    ],
    "vibesRaw": "groove grown & sexy",
    "free": false,
    "price": "$35.00",
    "badges": [
      "Live Show"
    ],
    "time": "9:30 PM",
    "location": "Blues Alley Jazz Supper Club · 1073 Wisconsin Ave NW 1st Floor, Washington, DC 20007",
    "vibeTags": [
      "Groove",
      "Grown & Sexy"
    ],
    "ctaHref": "https://www.instantseats.com/index.cfm?fuseaction=buy.event&eventID=1B5B2251-ED3B-521B-9F1F7989386E01DD",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-live-show"
  },
  {
    "id": "8",
    "festival": "june-2026",
    "day": "saturday",
    "dayDate": "2026-06-27",
    "dayLabel": "Saturday",
    "name": "STATIC: A QUEER FASHION DISRUPTION",
    "organizer": "QueerTalk + Dykemint",
    "types": [
      "live-show",
      "after-dark",
      "meetup"
    ],
    "vibesRaw": "flirt ass shaking cultural creative community groove",
    "free": false,
    "price": "$10.00",
    "badges": [
      "Live Show",
      "After Dark",
      "Meetup"
    ],
    "time": "6:00 PM",
    "location": "Transmission · 1353 H St NE, Washington, DC 20002",
    "vibeTags": [
      "Flirt",
      "Ass Shaking",
      "Cultural",
      "Creative",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://www.instagram.com/p/DZLRQ5flA7K/?img_index=1",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-live-show"
  },
  {
    "id": "9",
    "festival": "june-2026",
    "day": "saturday",
    "dayDate": "2026-06-27",
    "dayLabel": "Saturday",
    "name": "We're Not Dead Pres: Y2gay / Glup Sleazo",
    "organizer": "Transmission",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove flirt",
    "free": false,
    "price": "$30.00",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "Transmission · 1353 H St NE, Washington, DC 20002",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Flirt"
    ],
    "ctaHref": "https://shotgun.live/en/events/y-2-gay-glup-sleazo",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "10",
    "festival": "june-2026",
    "day": "saturday",
    "dayDate": "2026-06-27",
    "dayLabel": "Saturday",
    "name": "So MASSIVE Rooftop Day Party: Official DC Caribbean Pride Party",
    "organizer": "Queeribbeans Of The DMV",
    "types": [
      "day-party"
    ],
    "vibesRaw": "ass shaking groove",
    "free": false,
    "price": "$10.00",
    "badges": [
      "Day Party"
    ],
    "time": "5:00 PM",
    "location": "Focus Social Club · 1348 H St NE, Washington, DC 20002, USA",
    "vibeTags": [
      "Ass Shaking",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/so-massive-queeribbean-day-party?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnG-PUHC1sUYg-vEWYeIfA9w8NIP57jul9bTSGVNLHctiE-33v6N9MGgoPUkQ_aem_iABx-39W7m16YBXuwsbrrw",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party"
  },
  {
    "id": "11",
    "festival": "june-2026",
    "day": "saturday",
    "dayDate": "2026-06-27",
    "dayLabel": "Saturday",
    "name": "Gay Bay Day ‘26 ☀️",
    "organizer": "Nia Coleman + Asiza",
    "types": [
      "outdoors-hangout",
      "meetup"
    ],
    "vibesRaw": "chill community byob",
    "free": true,
    "price": "Free",
    "badges": [
      "Outdoors Hangout",
      "Meetup",
      "Free"
    ],
    "time": "11:00 AM",
    "location": "Sandy Point State Park, · 1100 East College Parkway, Annapolis, MD",
    "vibeTags": [
      "Chill",
      "Community",
      "BYOB"
    ],
    "ctaHref": "https://partiful.com/e/fMCyebRPGJzbm2AKM51e?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnIEn_0VYQOqNDv7nTnF6XsreYuYhZDmNxyV8x3XVg_3AAObPJ_pEtr6ThXM0_aem_Hcb5yOTnwVPynNg2b6mEDA",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-outdoors-hangout"
  },
  {
    "id": "12",
    "festival": "june-2026",
    "day": "saturday",
    "dayDate": "2026-06-27",
    "dayLabel": "Saturday",
    "name": "UNITED WE CRAWL: PRIDE PASSPORT",
    "organizer": "A League of Her Own, Pitchers, and MIXXED",
    "types": [
      "happy-hour",
      "day-party"
    ],
    "vibesRaw": "games chill flirt",
    "free": true,
    "price": "Free",
    "badges": [
      "Happy Hour",
      "Day Party",
      "Free"
    ],
    "time": "4:00 PM",
    "location": "A League Of Her Own · 2319 18th St NW, Washington, DC 20009",
    "vibeTags": [
      "Games",
      "Chill",
      "Flirt"
    ],
    "ctaHref": "https://www.instagram.com/p/DZYgod1NY0w/",
    "ctaLabel": "More Info",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-happy-hour"
  },
  {
    "id": "13",
    "festival": "june-2026",
    "day": "sunday",
    "dayDate": "2026-06-28",
    "dayLabel": "Sunday",
    "name": "Spritz & Blooms",
    "organizer": "Lesbifriends Travel",
    "types": [
      "day-party",
      "happy-hour",
      "meetup"
    ],
    "vibesRaw": "chill community flirt",
    "free": false,
    "price": "$75.00",
    "badges": [
      "Day Party",
      "Happy Hour",
      "Meetup"
    ],
    "time": "2:00 PM",
    "location": "Garden Venue · Washington DC",
    "vibeTags": [
      "Chill",
      "Community",
      "Flirt"
    ],
    "ctaHref": "https://posh.vip/e/spritz-blooms-a-black-lesbian-queer-garden-party",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party"
  },
  {
    "id": "14",
    "festival": "june-2026",
    "day": "sunday",
    "dayDate": "2026-06-28",
    "dayLabel": "Sunday",
    "name": "Transmission Pres. Dj Lag",
    "organizer": "Transmission",
    "types": [
      "day-party"
    ],
    "vibesRaw": "ass shaking groove flirt",
    "free": false,
    "price": "$15.00",
    "badges": [
      "Day Party"
    ],
    "time": "3:00 PM",
    "location": "Transmission · 1353 H St NE, Washington, DC 20002",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Flirt"
    ],
    "ctaHref": "https://shotgun.live/en/festivals/transmission-pres-dj-lag",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party"
  },
  {
    "id": "15",
    "festival": "june-2026",
    "day": "sunday",
    "dayDate": "2026-06-28",
    "dayLabel": "Sunday",
    "name": "Queeribbean's Day in di Park",
    "organizer": "Queeribbeans Of The DMV",
    "types": [
      "outdoors-hangout",
      "meetup"
    ],
    "vibesRaw": "chill community byob",
    "free": false,
    "price": "$3.00",
    "badges": [
      "Outdoors Hangout",
      "Meetup"
    ],
    "time": "12:00 PM",
    "location": "Fort DuPont Park | Lanham Estates · 4150 Alabama Ave SE, Washington, DC 20019, USA",
    "vibeTags": [
      "Chill",
      "Community",
      "BYOB"
    ],
    "ctaHref": "https://posh.vip/e/queeribbeans-day-in-di-yaad?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGngsmFsegzWxlkDH6-bgR5QNXryxmYDxxh_DKuntAickxmCy24x35hm50srdI_aem_FtzR6VLMkZ14ljjNV-hzkQ",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-outdoors-hangout"
  },
  {
    "id": "16",
    "festival": "june-2026",
    "day": "wednesday",
    "dayDate": "2026-06-24",
    "dayLabel": "Wednesday",
    "name": "Team DC Night OUT Series: Nats Night OUT 2026",
    "organizer": "Baseball Team DC",
    "types": [
      "outdoors-hangout",
      "meetup"
    ],
    "vibesRaw": "chill community food games",
    "free": false,
    "price": "$40.00",
    "badges": [
      "Outdoors Hangout",
      "Meetup"
    ],
    "time": "5:30 PM",
    "location": "Nationals Park · 1500 South Capitol Street SE, Washington, DC 20003",
    "vibeTags": [
      "Chill",
      "Community",
      "Food",
      "Games"
    ],
    "ctaHref": "https://www.zeffy.com/en-US/ticketing/nats-night-out--2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-outdoors-hangout"
  },
  {
    "id": "17",
    "festival": "june-2026",
    "day": "monday",
    "dayDate": "2026-06-22",
    "dayLabel": "Monday",
    "name": "Wicked Mondaze Summer Kickoff",
    "organizer": "MIM Entertainment & Jaywalking Productions",
    "types": [
      "day-party"
    ],
    "vibesRaw": "chill ass shaking flirt",
    "free": true,
    "price": "Free",
    "badges": [
      "Day Party",
      "Free"
    ],
    "time": "6:00 PM",
    "location": "Wild Days - Eaton Hotel",
    "vibeTags": [
      "Chill",
      "Ass Shaking",
      "Flirt"
    ],
    "ctaHref": "https://www.eventbrite.com/e/wicked-mondaze-pop-up-happy-hour-tickets-1991574097738?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&utm-source=wsa&aff=ebdsshwebmobile",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-day-party"
  }
];
