/* eslint-disable */
// Auto-generated by scripts/sync-events.ts from the Google Sheets Filterable August Events tab. Do not edit by hand.
import type { PrideEvent } from '../../types/event';

export const generatedEvents: PrideEvent[] = [
  {
    "id": "nyc-collective-black-queer-takeover-17",
    "festival": "nyc-collective-black-queer-takeover",
    "day": "wednesday",
    "dayDate": "2026-08-12",
    "dayLabel": "Wednesday",
    "name": "Game Night: CANCELED",
    "organizer": "Deviant",
    "types": [
      "after-dark",
      "meetup"
    ],
    "vibesRaw": "chill community games groove flirt",
    "free": true,
    "price": "Free",
    "badges": [
      "After Dark",
      "Meetup",
      "Free"
    ],
    "time": "9:00 PM",
    "location": "Solera · Saint Ann's Avenue, The Bronx, NY (exact street number not given)",
    "vibeTags": [
      "Chill",
      "Community",
      "Games",
      "Groove",
      "Flirt"
    ],
    "ctaHref": "https://www.the-nyc-collective.com/events/game-night",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-after-dark",
    "city": "nyc",
    "prideSeries": "The Collective: NYC Black Pride"
  },
  {
    "id": "nyc-collective-black-queer-takeover-18",
    "festival": "nyc-collective-black-queer-takeover",
    "day": "friday",
    "dayDate": "2026-08-14",
    "dayLabel": "Friday",
    "name": "Physique",
    "organizer": "Deviant",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt grown & sexy groove",
    "free": false,
    "price": "$35.00",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "Red Eye · 355 West 41st StreetNew York, New York, 10036",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://redeyetickets.com/events/deviant-physique",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc",
    "prideSeries": "The Collective: NYC Black Pride"
  },
  {
    "id": "nyc-collective-black-queer-takeover-35",
    "festival": "nyc-collective-black-queer-takeover",
    "day": "sunday",
    "dayDate": "2026-08-16",
    "dayLabel": "Sunday",
    "name": "Tailgate",
    "organizer": "Good Dayz",
    "types": [
      "day-party"
    ],
    "vibesRaw": "flirt community ass shaking grown & sexy groove",
    "free": false,
    "price": "$10.00",
    "badges": [
      "Day Party"
    ],
    "time": "4:00 PM",
    "location": "BK Backyard · 151 Banker St. Brooklyn, NY 11222",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/tailgate-9?u=dvn__a&_t=mskqsbow&os=ios&src=event_page",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "nyc",
    "prideSeries": "The Collective: NYC Black Pride"
  },
  {
    "id": "nyc-collective-black-queer-takeover-38",
    "festival": "nyc-collective-black-queer-takeover",
    "day": "sunday",
    "dayDate": "2026-08-16",
    "dayLabel": "Sunday",
    "name": "Haus of Honey",
    "organizer": "Haus of Honey",
    "types": [
      "day-party"
    ],
    "vibesRaw": "flirt community ass shaking grown & sexy groove",
    "free": false,
    "price": "$10.00",
    "badges": [
      "Day Party"
    ],
    "time": "5:00 PM",
    "location": "Dive Bar BK · 408 troutman street East Williamsburg, Brooklyn",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://dice.fm/event/6do963-haus-of-honey-16th-aug-the-sultan-room-rooftop-brooklyn-tickets",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "nyc",
    "prideSeries": "The Collective: NYC Black Pride"
  },
  {
    "id": "nyc-collective-black-queer-takeover-69",
    "festival": "nyc-collective-black-queer-takeover",
    "day": "friday",
    "dayDate": "2026-08-14",
    "dayLabel": "Friday",
    "name": "THE CROSSOVER (Twerk vs Bashment)",
    "organizer": "Out N Bad x She Shed x Sapphic Ja",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove community flirt",
    "free": false,
    "price": "$18.00",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "The House · 29 Locust St, Brooklyn, NY 11206, USA",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Community",
      "Flirt"
    ],
    "ctaHref": "https://posh.vip/e/out-n-bad-x-sapphic-ja-x-sheshed-dc-presents-the-crossover-twerk-vs-bashment",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc",
    "prideSeries": "The Collective: NYC Black Pride"
  },
  {
    "id": "nyc-collective-black-queer-takeover-74",
    "festival": "nyc-collective-black-queer-takeover",
    "day": "saturday",
    "dayDate": "2026-08-15",
    "dayLabel": "Saturday",
    "name": "Zestyworld: The Collective Weekend",
    "organizer": "Raw Honey",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking groove community flirt",
    "free": false,
    "price": "$19.00",
    "badges": [
      "After Dark"
    ],
    "time": "11:00 PM",
    "location": "Putnam's Pub & Cooker · 419 Myrtle Avenue, Brooklyn, NY 11205",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Community",
      "Flirt"
    ],
    "ctaHref": "https://posh.vip/e/nyc-zestyworld-the-collective-weekend",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "nyc",
    "prideSeries": "The Collective: NYC Black Pride"
  },
  {
    "id": "nyc-collective-black-queer-takeover-76",
    "festival": "nyc-collective-black-queer-takeover",
    "day": "saturday",
    "dayDate": "2026-08-22",
    "dayLabel": "Saturday",
    "name": "(NYC) Raw Honey: COZY",
    "organizer": "Raw Honey",
    "types": [
      "day-party"
    ],
    "vibesRaw": "ass shaking groove community flirt",
    "free": false,
    "price": "$13.00",
    "badges": [
      "Day Party"
    ],
    "time": "5:00 PM",
    "location": "Dive Bar · 408 Troutman St, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Ass Shaking",
      "Groove",
      "Community",
      "Flirt"
    ],
    "ctaHref": "https://posh.vip/e/nyc-haus-of-honey-the-collective-weekend",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "nyc",
    "prideSeries": "The Collective: NYC Black Pride"
  },
  {
    "id": "nyc-collective-black-queer-takeover-78",
    "festival": "nyc-collective-black-queer-takeover",
    "day": "saturday",
    "dayDate": "2026-08-15",
    "dayLabel": "Saturday",
    "name": "Sunkissed",
    "organizer": "Recess",
    "types": [
      "day-party"
    ],
    "vibesRaw": "flirt community ass shaking grown & sexy groove",
    "free": false,
    "price": "$10.00",
    "badges": [
      "Day Party"
    ],
    "time": "3:00 PM",
    "location": "Unlisted Rooftop (11th floor) · 3 Freeman Alley, New York, NY 10002",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/sunkissed-by-recess-1",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "nyc",
    "prideSeries": "The Collective: NYC Black Pride"
  }
];
