/* eslint-disable */
// Auto-generated by scripts/sync-events.ts from the Google Sheets NYC Pride Master tab. Do not edit by hand.
import type { PrideEvent } from '../../types/event';

export const generatedEvents: PrideEvent[] = [
  {
    "id": "nyc-pride-2",
    "festival": "nyc-pride",
    "day": "sunday",
    "dayDate": "2026-06-21",
    "dayLabel": "Sunday",
    "name": "Pride HEAL IN Restorative Flow class",
    "organizer": "Angelito",
    "types": [
      "workshop"
    ],
    "vibesRaw": "wellness community",
    "free": false,
    "price": "$20.00",
    "badges": [
      "Workshop"
    ],
    "time": "1:00 PM",
    "location": "Honey's Rooftop* · 99 Scott Ave,\nBrooklyn, NY",
    "vibeTags": [
      "Wellness",
      "Community"
    ],
    "ctaHref": "https://docs.google.com/forms/d/1crmnKPeCwOOftzKg8jdMp4mZPrLqDbjiX4vyoTf-46s/viewform?edit_requested=true",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-workshop"
  },
  {
    "id": "nyc-pride-3",
    "festival": "nyc-pride",
    "day": "wednesday",
    "dayDate": "2026-06-24",
    "dayLabel": "Wednesday",
    "name": "Since You Asked: A Hot Takes Open Mic (Pride Edition)",
    "organizer": "Saint James Libations",
    "types": [
      "live-show"
    ],
    "vibesRaw": "chill creative",
    "free": false,
    "price": "$11.00",
    "badges": [
      "Live Show"
    ],
    "time": "6:00 PM",
    "location": "Saint James Libations · 269 Stanhope St, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Chill",
      "Creative"
    ],
    "ctaHref": "https://posh.vip/e/since-you-asked-a-hot-takes-debate-night-2",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-live-show"
  },
  {
    "id": "nyc-pride-4",
    "festival": "nyc-pride",
    "day": "wednesday",
    "dayDate": "2026-06-24",
    "dayLabel": "Wednesday",
    "name": "Feelin good & grown karaoke: Pride Edition",
    "organizer": "Sounds by Neisey",
    "types": [
      "live-show"
    ],
    "vibesRaw": "karaoke community creative chill groove",
    "free": true,
    "price": "Free",
    "badges": [
      "Live Show",
      "Free"
    ],
    "time": "9:00 PM",
    "location": "Saint James Libations · 269 Stanhope St, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Karaoke",
      "Community",
      "Creative",
      "Chill",
      "Groove"
    ],
    "ctaHref": "https://partiful.com/e/e6CXWYoFeO4xsMvJNTOv?",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-live-show"
  },
  {
    "id": "nyc-pride-5",
    "festival": "nyc-pride",
    "day": "wednesday",
    "dayDate": "2026-06-24",
    "dayLabel": "Wednesday",
    "name": "Indigipride 2026: Ballroom Pow Wow",
    "organizer": "House of Yes",
    "types": [
      "ball",
      "after-dark"
    ],
    "vibesRaw": "cultural community",
    "free": false,
    "price": "$26.00",
    "badges": [
      "Ball",
      "After Dark"
    ],
    "time": "8:00 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Cultural",
      "Community"
    ],
    "ctaHref": "https://shotgun.live/en/events/indigipride-june-24-2026?utm_medium=widget&utm_term=html_widget&_gl=1*1fjxbl2*_gcl_au*OTQ1MTgyODUuMTc4MTg5NTAxMA..",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-ball"
  },
  {
    "id": "nyc-pride-6",
    "festival": "nyc-pride",
    "day": "thursday",
    "dayDate": "2026-06-25",
    "dayLabel": "Thursday",
    "name": "The Orbit presents Playgrnd: a Pre-Pride Mixer",
    "organizer": "BoyGrrrl",
    "types": [
      "happy-hour",
      "meetup"
    ],
    "vibesRaw": "flirt community groove",
    "free": false,
    "price": "$18.00",
    "badges": [
      "Happy Hour",
      "Meetup"
    ],
    "time": "5:00 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Boulevard\nBrooklyn, NY 11233",
    "vibeTags": [
      "Flirt",
      "Community",
      "Groove"
    ],
    "ctaHref": "https://www.eventbrite.com/e/the-playgrnd-tickets-1990185015957",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-happy-hour"
  },
  {
    "id": "nyc-pride-7",
    "festival": "nyc-pride",
    "day": "thursday",
    "dayDate": "2026-06-25",
    "dayLabel": "Thursday",
    "name": "Pride Vybz",
    "organizer": "Saint James Libations",
    "types": [
      "meetup",
      "happy-hour"
    ],
    "vibesRaw": "chill networking community",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Happy Hour",
      "Free"
    ],
    "time": "7:00 PM",
    "location": "Saint James Libations · 269 Stanhope St, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Chill",
      "Networking",
      "Community"
    ],
    "ctaHref": "https://secure.everyaction.com/0QI8fPMAF0qoBJbjEUdG6A2?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZnRzaASlL_pleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA8xMjQwMjQ1NzQyODc0MTQAAadchkKiT_AeiNhpjVi7sh1e-FaSJxxmVR6EkL2wFudEI0UfPNAJHrmB6VD5XA_aem_tU0WRaDHFmom-_1mGhBiOw",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup"
  },
  {
    "id": "nyc-pride-8",
    "festival": "nyc-pride",
    "day": "thursday",
    "dayDate": "2026-06-25",
    "dayLabel": "Thursday",
    "name": "GayDar Pride",
    "organizer": "House of Yes",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt ass shaking",
    "free": false,
    "price": "$24.00",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Flirt",
      "Ass Shaking"
    ],
    "ctaHref": "https://shotgun.live/en/events/gaydar-pride-june-25-2026?utm_medium=widget&utm_term=html_widget&_gl=1*1fjxbl2*_gcl_au*OTQ1MTgyODUuMTc4MTg5NTAxMA..",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "nyc-pride-9",
    "festival": "nyc-pride",
    "day": "thursday",
    "dayDate": "2026-06-25",
    "dayLabel": "Thursday",
    "name": "SWEET WHINE [NYC Pride]: Slow Whine Function",
    "organizer": "Out N Bad",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking",
    "free": false,
    "price": "$20.00",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "Lovejoys · 412 Troutman St, Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking"
    ],
    "ctaHref": "https://www.eventbrite.com/e/out-n-bad-sweet-whine-nyc-pride-queer-caribbean-slow-whine-function-tickets-1990062294895?aff=oddtdtcreator",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "nyc-pride-10",
    "festival": "nyc-pride",
    "day": "friday",
    "dayDate": "2026-06-26",
    "dayLabel": "Friday",
    "name": "DJ Quiana Parks Pride",
    "organizer": "DJ Quiana",
    "types": [
      "day-party"
    ],
    "vibesRaw": "groove",
    "free": true,
    "price": "Free",
    "badges": [
      "Day Party",
      "Free"
    ],
    "time": "7:00 PM",
    "location": "Ace Hotel · 252 Schermerhorn St, Brooklyn, NY 11217, USA",
    "vibeTags": [
      "Groove"
    ],
    "ctaHref": "https://www.quianaparks.com/event-details/lounge-fridays-with-quiana-parks-2026-06-26-19-00",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-day-party"
  },
  {
    "id": "nyc-pride-11",
    "festival": "nyc-pride",
    "day": "friday",
    "dayDate": "2026-06-26",
    "dayLabel": "Friday",
    "name": "(NYC) Raw Honey: Seduction",
    "organizer": "Raw Honey",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt ass shaking",
    "free": false,
    "price": "$35.00",
    "badges": [
      "After Dark"
    ],
    "time": "10:30 PM",
    "location": "The Chocolate Factory · 70 Scott Avenue, NY 11237",
    "vibeTags": [
      "Flirt",
      "Ass Shaking"
    ],
    "ctaHref": "https://events.eventnoire.com/e/nyc-raw-honey-seduction/tickets",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "nyc-pride-12",
    "festival": "nyc-pride",
    "day": "friday",
    "dayDate": "2026-06-26",
    "dayLabel": "Friday",
    "name": "A BODY MADE HOME: THEY BLACK TRANS LOVE Author Talk & Book Signing with Dr. Kai Marshall Green",
    "organizer": "Dr. Kai Marshall Green",
    "types": [
      "meetup",
      "workshop"
    ],
    "vibesRaw": "chill creative community cultural",
    "free": true,
    "price": "$18.00",
    "badges": [
      "Meetup",
      "Workshop",
      "Free"
    ],
    "time": "7:00 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Boulevard\nBrooklyn, NY 11233",
    "vibeTags": [
      "Chill",
      "Creative",
      "Community",
      "Cultural"
    ],
    "ctaHref": "https://luma.com/a-body-made-home",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup"
  },
  {
    "id": "nyc-pride-13",
    "festival": "nyc-pride",
    "day": "friday",
    "dayDate": "2026-06-26",
    "dayLabel": "Friday",
    "name": "SOFT LAUNCH: Sapphic NYC's Pride Party",
    "organizer": "Saint James Libations",
    "types": [
      "meetup",
      "happy-hour"
    ],
    "vibesRaw": "chill community flirt groove",
    "free": false,
    "price": "$25.00",
    "badges": [
      "Meetup",
      "Happy Hour"
    ],
    "time": "6:00 PM",
    "location": "Saint James Libations · 269 Stanhope St, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Chill",
      "Community",
      "Flirt",
      "Groove"
    ],
    "ctaHref": "https://www.eventcreate.com/e/sapphicnyc-pride-party-2026",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup"
  },
  {
    "id": "nyc-pride-14",
    "festival": "nyc-pride",
    "day": "friday",
    "dayDate": "2026-06-26",
    "dayLabel": "Friday",
    "name": "WLW Friday",
    "organizer": "Saint James Libations",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt ass shaking grown & sexy groove",
    "free": false,
    "price": "$12.00",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "Saint James Libations · 269 Stanhope St, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Flirt",
      "Ass Shaking",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://posh.vip/e/wlw-friday",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "nyc-pride-15",
    "festival": "nyc-pride",
    "day": "friday",
    "dayDate": "2026-06-26",
    "dayLabel": "Friday",
    "name": "Queer Aunties Presents: Aunties in Brooklyn",
    "organizer": "Queer Aunties",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt",
    "free": false,
    "price": "$45.00",
    "badges": [
      "After Dark"
    ],
    "time": "9:00 PM",
    "location": "Bogart House · 230 Bogart St, Brooklyn, NY 11206, USA",
    "vibeTags": [
      "Ass Shaking",
      "Flirt"
    ],
    "ctaHref": "https://posh.vip/e/queer-aunties-presents-aunties-in-brooklyn?c=6a358d5773cb9a4109e8ced3&t=posh-embed",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "nyc-pride-16",
    "festival": "nyc-pride",
    "day": "friday",
    "dayDate": "2026-06-26",
    "dayLabel": "Friday",
    "name": "Pure Honey Pride: Mike Q, Kevin Aviance, David Elimelech",
    "organizer": "House of Yes",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking",
    "free": false,
    "price": "$21.00",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Ass Shaking"
    ],
    "ctaHref": "https://shotgun.live/en/events/pure-honey-pride-june-26-2026?utm_medium=widget&utm_term=html_widget&_gl=1*1fjxbl2*_gcl_au*OTQ1MTgyODUuMTc4MTg5NTAxMA..",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "nyc-pride-17",
    "festival": "nyc-pride",
    "day": "friday",
    "dayDate": "2026-06-26",
    "dayLabel": "Friday",
    "name": "PRESSURE [NYC Pride]: Queer Caribbean Bashment",
    "organizer": "Out N Bad",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking",
    "free": false,
    "price": "$30.00",
    "badges": [
      "After Dark"
    ],
    "time": "11:00 PM",
    "location": "The Meadows · 17 Meadow St, Brooklyn, NY 11206",
    "vibeTags": [
      "Ass Shaking"
    ],
    "ctaHref": "https://kydlabs.com/e/EVfb22d40c-43a1-4c63-b2a5-0d656a748eaf?referral_id=g-1ca0fa55-ea8e-44bc-a191-d4bf40bf3fe5",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "nyc-pride-19",
    "festival": "nyc-pride",
    "day": "saturday",
    "dayDate": "2026-06-27",
    "dayLabel": "Saturday",
    "name": "NYC Mega Day Party",
    "organizer": "Zestyworld.nyc",
    "types": [
      "day-party"
    ],
    "vibesRaw": "ass shaking groove",
    "free": false,
    "price": "$50.00",
    "badges": [
      "Day Party"
    ],
    "time": "4:00 PM",
    "location": "The Yard at 3 Dollar Bill · 260 Meserole StreetBrooklyn, NY, 11206United States",
    "vibeTags": [
      "Ass Shaking",
      "Groove"
    ],
    "ctaHref": "https://www.etix.com/ticket/p/57559998/zestyworld-brooklyn-3-dollar-bill",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party"
  },
  {
    "id": "nyc-pride-20",
    "festival": "nyc-pride",
    "day": "saturday",
    "dayDate": "2026-06-27",
    "dayLabel": "Saturday",
    "name": "(NYC) Haus of Honey: 30+ Forbidden Fruit",
    "organizer": "Raw Honey/Haus of Honey",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt ass shaking 30+",
    "free": false,
    "price": "$45.00",
    "badges": [
      "After Dark"
    ],
    "time": "10:30 PM",
    "location": "Red Pavillion · 1241 Flushing Ave, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Flirt",
      "Ass Shaking",
      "30+"
    ],
    "ctaHref": "https://posh.vip/e/nyc-haus-of-honey-saturday",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "nyc-pride-22",
    "festival": "nyc-pride",
    "day": "saturday",
    "dayDate": "2026-06-27",
    "dayLabel": "Saturday",
    "name": "Glo in the City Live! Black and POC Queer Comedy PRIDE/Post Dyke March Show",
    "organizer": "Glo Butler",
    "types": [
      "live-show"
    ],
    "vibesRaw": "community creative",
    "free": false,
    "price": "$13.00",
    "badges": [
      "Live Show"
    ],
    "time": "7:00 PM",
    "location": "Gladys Books & Wine · 306 Malcolm X Boulevard\nBrooklyn, NY 11233",
    "vibeTags": [
      "Community",
      "Creative"
    ],
    "ctaHref": "https://www.eventbrite.com/e/glo-in-the-city-live-black-and-poc-queer-comedy-pridepost-dyke-march-show-tickets-1988108637453",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-live-show"
  },
  {
    "id": "nyc-pride-23",
    "festival": "nyc-pride",
    "day": "saturday",
    "dayDate": "2026-06-27",
    "dayLabel": "Saturday",
    "name": "SPICE NYC PRIDE BRUNCH & DANCE PARTY!",
    "organizer": "SPICE NYC",
    "types": [
      "brunch",
      "day-party"
    ],
    "vibesRaw": "flirt ass shaking groove grown & sexy",
    "free": false,
    "price": "$33.00",
    "badges": [
      "Brunch",
      "Day Party"
    ],
    "time": "2:00 PM",
    "location": "VIVA L.I.C. · 33-02 Queens Boulevard\nQueens, NY 11101",
    "vibeTags": [
      "Flirt",
      "Ass Shaking",
      "Groove",
      "Grown & Sexy"
    ],
    "ctaHref": "https://www.eventbrite.com/e/spice-nyc-pride-brunch-dance-party-tickets-1984609976865?aff=oddtdtcreator&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnfKptfeSgO8YcFjKWhSTO8a_uDm3Ehk9H9Urw1phpz7rGSdEfzi3DBRt3fQo_aem_Xorx_qDZtv3OYo0xrgEUeQ&utm_content=link_in_bio&utm_medium=social&utm_source=ig",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-brunch"
  },
  {
    "id": "nyc-pride-24",
    "festival": "nyc-pride",
    "day": "saturday",
    "dayDate": "2026-06-27",
    "dayLabel": "Saturday",
    "name": "Moby D!Ck A Pride Odyssey: Tedd Patterson, Griffin Maxwell..",
    "organizer": "House of Yes",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt",
    "free": false,
    "price": "$35.00",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "House of Yes · 2 Wyckoff Avenue, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Ass Shaking",
      "Flirt"
    ],
    "ctaHref": "https://shotgun.live/en/events/pride-odyssey-june-27-2026?utm_medium=widget&utm_term=html_widget&_gl=1*yf6be9*_gcl_au*OTQ1MTgyODUuMTc4MTg5NTAxMA..",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "nyc-pride-25",
    "festival": "nyc-pride",
    "day": "sunday",
    "dayDate": "2026-06-28",
    "dayLabel": "Sunday",
    "name": "RIIS BEACH PRIDE CELEBRATION the GLADYS EDITION",
    "organizer": "Gladys Books & Wine",
    "types": [
      "meetup"
    ],
    "vibesRaw": "chill community",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Free"
    ],
    "time": "12:00 PM",
    "location": "The People's Beach at Jacob Riis Park · 157 Rockaway Beach Blvd, Queens, NY 11694",
    "vibeTags": [
      "Chill",
      "Community"
    ],
    "ctaHref": "https://www.gladysbooksandwine.com/#?event-id=82731",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup"
  },
  {
    "id": "nyc-pride-26",
    "festival": "nyc-pride",
    "day": "sunday",
    "dayDate": "2026-06-28",
    "dayLabel": "Sunday",
    "name": "The 3rd Annual: Make NYC Pride Fun Again",
    "organizer": "Fancy",
    "types": [
      "meetup"
    ],
    "vibesRaw": "chill community",
    "free": false,
    "price": "$12.00",
    "badges": [
      "Meetup"
    ],
    "time": "8:00 PM",
    "location": "Mazaar Lounge · 137 Essex Street, New York, NY",
    "vibeTags": [
      "Chill",
      "Community"
    ],
    "ctaHref": "https://www.eventbrite.com/e/make-nyc-pride-fun-again-3rd-annual-tickets-1991233282350?aff=oddtdtcreator&utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnBiVk-tmEKfQHQASxvGL-Wrdv6TUuut0SXqJ-T9ess4aGJTEtzHIN0Lr-B1c_aem_3YmuxMvJFGgEdAtGP3diZQ",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup"
  },
  {
    "id": "nyc-pride-27",
    "festival": "nyc-pride",
    "day": "sunday",
    "dayDate": "2026-06-28",
    "dayLabel": "Sunday",
    "name": "Pride 2026: Hoy X Tiki Disco X Glitterbox",
    "organizer": "House of Yes",
    "types": [
      "day-party",
      "outdoors"
    ],
    "vibesRaw": "flirt groove",
    "free": false,
    "price": "$79.00",
    "badges": [
      "Day Party",
      "Outdoors"
    ],
    "time": "2:00 PM",
    "location": "Industry City · 220 36th Street, Brooklyn, NY 11232, USA",
    "vibeTags": [
      "Flirt",
      "Groove"
    ],
    "ctaHref": "https://shotgun.live/en/events/nyc-pride-2026?utm_medium=widget&utm_term=html_widget&_gl=1*mek86h*_gcl_au*OTQ1MTgyODUuMTc4MTg5NTAxMA..",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party"
  },
  {
    "id": "nyc-pride-28",
    "festival": "nyc-pride",
    "day": "sunday",
    "dayDate": "2026-06-28",
    "dayLabel": "Sunday",
    "name": "Sinderella Queer Ball – Pride Grand Finale",
    "organizer": "House of Yes",
    "types": [
      "after-dark",
      "ball"
    ],
    "vibesRaw": "ass shaking flirt",
    "free": false,
    "price": "$22.00",
    "badges": [
      "After Dark",
      "Ball"
    ],
    "time": "10:00 PM",
    "location": "House of Yes · 220 36th Street, Brooklyn, NY 11232, USA",
    "vibeTags": [
      "Ass Shaking",
      "Flirt"
    ],
    "ctaHref": "https://shotgun.live/en/events/sinderella-queer-ball-june-28-2026?utm_medium=widget&utm_term=html_widget&_gl=1*1azimhi*_gcl_au*OTQ1MTgyODUuMTc4MTg5NTAxMA..",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "nyc-pride-29",
    "festival": "nyc-pride",
    "day": "sunday",
    "dayDate": "2026-06-28",
    "dayLabel": "Sunday",
    "name": "NYC Pride Parade Afterparty 2026",
    "organizer": "SOB’s",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking",
    "free": true,
    "price": "$21.00",
    "badges": [
      "After Dark",
      "Free"
    ],
    "time": "5:00 PM",
    "location": "Sounds Of Brazil · 204 Varick St, New York City, New York 10014, United States",
    "vibeTags": [
      "Ass Shaking"
    ],
    "ctaHref": "https://kydlabs.com/e/EV80992557-1c97-4015-8a58-89c3968372b2?ref=bio",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "nyc-pride-30",
    "festival": "nyc-pride",
    "day": "saturday",
    "dayDate": "2026-06-27",
    "dayLabel": "Saturday",
    "name": "How Single RU?! Mixer (NYC Pride Day Party)",
    "organizer": "Adult Supervision Needed",
    "types": [
      "day-party",
      "happy-hour"
    ],
    "vibesRaw": "flirt community",
    "free": false,
    "price": "$23.00",
    "badges": [
      "Day Party",
      "Happy Hour"
    ],
    "time": "2:00 PM",
    "location": "Saint James Libations · 269 Stanhope St, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Flirt",
      "Community"
    ],
    "ctaHref": "https://posh.vip/e/how-single-ru-mixer-nyc-pride-day-party",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party"
  },
  {
    "id": "nyc-pride-31",
    "festival": "nyc-pride",
    "day": "saturday",
    "dayDate": "2026-06-27",
    "dayLabel": "Saturday",
    "name": "The Wine Down Brooklyn",
    "organizer": "Queer Aunties",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt ass shaking groove chill",
    "free": false,
    "price": "$30.00",
    "badges": [
      "After Dark"
    ],
    "time": "7:00 PM",
    "location": "Saint James Libations · 269 Stanhope St, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Flirt",
      "Ass Shaking",
      "Groove",
      "Chill"
    ],
    "ctaHref": "https://posh.vip/e/the-wine-down-brooklyn?c=6a39645163aee0a13dd7a740&t=posh-embed",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "nyc-pride-32",
    "festival": "nyc-pride",
    "day": "saturday",
    "dayDate": "2026-06-27",
    "dayLabel": "Saturday",
    "name": "Gay Gayer Gayest: Pride Party",
    "organizer": "ggg.nyc",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking",
    "free": true,
    "price": "$36.00",
    "badges": [
      "After Dark",
      "Free"
    ],
    "time": "10:00 PM",
    "location": "314 Scholes · 314 Scholes Street, Brooklyn, NY",
    "vibeTags": [
      "Ass Shaking"
    ],
    "ctaHref": "https://tickets.venuepilot.com/e/gay-gayer-gayest-pride-party-2026-06-27-314-scholes-brooklyn-612064?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnDFohiki_MBU8Ct1w6teYb1KxAuLX5w1AgwxUh_rT5bcKGHFuAlPE_6-b068_aem_aM3Ylb5kIz4g9lqMb1kOug",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "nyc-pride-33",
    "festival": "nyc-pride",
    "day": "wednesday",
    "dayDate": "2026-06-24",
    "dayLabel": "Wednesday",
    "name": "PRIDE PREGAME",
    "organizer": "gURLS Like gIRLS",
    "types": [
      "happy-hour"
    ],
    "vibesRaw": "flirt community groove chill",
    "free": false,
    "price": "$15.00",
    "badges": [
      "Happy Hour"
    ],
    "time": "8:00 PM",
    "location": "Friends & Lovers · 641 Classon Ave, Brooklyn, NY 11238, USA",
    "vibeTags": [
      "Flirt",
      "Community",
      "Groove",
      "Chill"
    ],
    "ctaHref": "https://posh.vip/e/pride-pregame?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnbBBHzdSX4fUvmQSjHAuXWyp42NX993frk_rbqWuyeKmDPuxsh_UNjxcx4Hw_aem_nhbXF-gbNMu2JkMeV0ixJQ",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-happy-hour"
  },
  {
    "id": "nyc-pride-34",
    "festival": "nyc-pride",
    "day": "saturday",
    "dayDate": "2026-06-27",
    "dayLabel": "Saturday",
    "name": "DickAppointment NYC Pride 2026: Bobby Beethoven, KENDOLLAZ, Daniro B2B Pressure Point, + more",
    "organizer": "DICKAPPOINTMENT",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "ass shaking flirt groove",
    "free": false,
    "price": "$40.50",
    "badges": [
      "After Dark"
    ],
    "time": "10:00 PM",
    "location": "Chocolate Factory · 70 Scott Ave Brooklyn, NY 11237",
    "vibeTags": [
      "Ass Shaking",
      "Flirt",
      "Groove"
    ],
    "ctaHref": "https://ra.co/events/2436797",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark"
  },
  {
    "id": "nyc-pride-35",
    "festival": "nyc-pride",
    "day": "sunday",
    "dayDate": "2026-06-28",
    "dayLabel": "Sunday",
    "name": "Libations & Liberation",
    "organizer": "Saint James Libations",
    "types": [
      "day-party",
      "live-show",
      "workshop"
    ],
    "vibesRaw": "chill creative flirt community",
    "free": true,
    "price": "Free",
    "badges": [
      "Day Party",
      "Live Show",
      "Workshop",
      "Free"
    ],
    "time": "3:00 PM",
    "location": "Saint James Libations · 269 Stanhope St, Brooklyn, NY 11237, USA",
    "vibeTags": [
      "Chill",
      "Creative",
      "Flirt",
      "Community"
    ],
    "ctaHref": "https://www.sapphi.app/e/71b7d88a-0a7b-46e5-8e5a-2d2d9e0d9940?fbclid=PARlRTSASlMdtleHRuA2FlbQIxMABzcnRjBmFwcF9pZA8xMjQwMjQ1NzQyODc0MTQAAadVvAJ6HsDiFTljemtuFJmaHRhVstaAHTe2_XwIoII6NExHmRm71XnQQnUWcQ_aem_Rxkld1vlGQ38B4rmMwyxGA",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-day-party"
  }
];
