/* eslint-disable */
// Auto-generated by scripts/sync-events.ts from the Google Sheets July_Events tab. Do not edit by hand.
import type { PrideEvent } from '../../types/event';

export const generatedEvents: PrideEvent[] = [
  {
    "id": "wnba-all-star-weekend-46",
    "festival": "wnba-all-star-weekend",
    "day": "friday",
    "dayDate": "2026-07-24",
    "dayLabel": "Friday",
    "name": "WNBA All-Star Weekend: THE DRAFT",
    "organizer": "Girlytheceo + Queer Aunties",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "badges": [],
    "time": "",
    "location": "The Chi",
    "vibeTags": [],
    "ctaHref": "Tickets go live Monday, June 15 👀",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-47",
    "festival": "wnba-all-star-weekend",
    "day": "saturday",
    "dayDate": "2026-07-25",
    "dayLabel": "Saturday",
    "name": "WNBA All-Star Weekend: FOR THE LOVE OF BASKETBALL",
    "organizer": "Girlytheceo + Queer Aunties",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "badges": [],
    "time": "",
    "location": "The Chi",
    "vibeTags": [],
    "ctaHref": "Tickets go live Monday, June 15 👀",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-48",
    "festival": "wnba-all-star-weekend",
    "day": "thursday",
    "dayDate": "2026-07-02",
    "dayLabel": "Thursday",
    "name": "WNBA ASW ‘26 Cousins Camp",
    "organizer": "Off The Dribble + Clubhouse Buckets",
    "types": [
      "meetup",
      "outdoors-hangout"
    ],
    "vibesRaw": "community games",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Outdoors Hangout",
      "Free"
    ],
    "time": "",
    "location": "The Chi",
    "vibeTags": [
      "Community",
      "Games"
    ],
    "ctaHref": "https://www.heylo.com/g/7fd1f873-5b39-42d3-b666-c2651567cd81?utm_content=vanity-url&utm_medium=referral&utm_source=l.threads.com",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-49",
    "festival": "wnba-all-star-weekend",
    "day": "friday",
    "dayDate": "2026-07-24",
    "dayLabel": "Friday",
    "name": "Unrivaled Coffee Club",
    "organizer": "Unrivaled Basketball",
    "types": [
      "meetup"
    ],
    "vibesRaw": "community food games",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Free"
    ],
    "time": "11:00 AM",
    "location": "Drip Collective · 172 N Racine Ave, Chicago, IL 60607, USA",
    "vibeTags": [
      "Community",
      "Food",
      "Games"
    ],
    "ctaHref": "https://www.unrivaled.basketball/coffee-club?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGn52rxKipWwNSN_bhl81nbJUebMRoy30l7BRINHI5KbS6X-QalUn4q8WSw6KA_aem_gaqfv7RGqzeb4Y8bAO1X_A",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.instagram.com/p/DaQLrZyEbpY/?hl=en&img_index=1",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-50",
    "festival": "wnba-all-star-weekend",
    "day": "friday",
    "dayDate": "2026-07-24",
    "dayLabel": "Friday",
    "name": "TOGETHXR House: Chicago, we're Home. 🏀",
    "organizer": "TOGETHXR House",
    "types": [
      "meetup"
    ],
    "vibesRaw": "community food games",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Free"
    ],
    "time": "10:00 AM",
    "location": "Big City Pickle (West Loop) · 113 N Elizabeth St, Chicago, IL 60607",
    "vibeTags": [
      "Community",
      "Food",
      "Games"
    ],
    "ctaHref": "https://www.togethxr.com/pages/togethxr-house",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.instagram.com/p/DaQSdIkEc6l/?hl=en&img_index=1",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-51",
    "festival": "wnba-all-star-weekend",
    "day": "saturday",
    "dayDate": "2026-07-25",
    "dayLabel": "Saturday",
    "name": "TOGETHXR House: Chicago, we're Home. 🏀",
    "organizer": "TOGETHXR House",
    "types": [
      "meetup"
    ],
    "vibesRaw": "community food games",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Free"
    ],
    "time": "9:30 AM",
    "location": "Big City Pickle (West Loop) · 113 N Elizabeth St, Chicago, IL 60607",
    "vibeTags": [
      "Community",
      "Food",
      "Games"
    ],
    "ctaHref": "https://www.togethxr.com/pages/togethxr-house",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.instagram.com/p/DaQSdIkEc6l/?hl=en&img_index=1",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-52",
    "festival": "wnba-all-star-weekend",
    "day": "thursday",
    "dayDate": "2026-07-23",
    "dayLabel": "Thursday",
    "name": "Drip Social x 2026 WNBA All-Star Kickoff",
    "organizer": "dripsocialhq",
    "types": [
      "meetup"
    ],
    "vibesRaw": "community food games",
    "free": false,
    "price": "$35.00",
    "badges": [
      "Meetup"
    ],
    "time": "7:00 PM",
    "location": "Please register to see the exact location of this event.",
    "vibeTags": [
      "Community",
      "Food",
      "Games"
    ],
    "ctaHref": "https://luma.com/8x6xkao9?fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnD2dNHyONyexdmYhTU7N8u968CBpM5ed7lxAZThLTcKjJafjZbxqrmG6TJuM_aem_NL4Zgrv1X8yGm1IDBPcICA&utm_content=link_in_bio&utm_id=97760_v0_s00_e0_tv3&utm_medium=social&utm_source=ig",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.instagram.com/p/DYSO0vHDiqT/?hl=en&img_index=1",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-53",
    "festival": "wnba-all-star-weekend",
    "day": "friday",
    "dayDate": "2026-07-24",
    "dayLabel": "Friday",
    "name": "Future of Sports: Investing in Athletes",
    "organizer": "State Street Investment Management SPY",
    "types": [
      "meetup"
    ],
    "vibesRaw": "community food games",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Free"
    ],
    "time": "2:00 PM",
    "location": "Please register to see the exact location of this event.",
    "vibeTags": [
      "Community",
      "Food",
      "Games"
    ],
    "ctaHref": "https://events.frontofficesports.com/investinginathletes2026/threads",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.threads.com/@frontofficesports/post/DZdBRclEf5H?xmt=AQG0HzOrviP9_rOAtcznN4Qn09ytB-Bu4DfosQyGaqwpZQc",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-54",
    "festival": "wnba-all-star-weekend",
    "day": "thursday",
    "dayDate": "2026-07-23",
    "dayLabel": "Thursday",
    "name": "Run It Back Chicago: The All-Star Fundraising Gala",
    "organizer": "Run It Back",
    "types": [
      "meetup",
      "educational"
    ],
    "vibesRaw": "community food games networking",
    "free": false,
    "price": "$100.00",
    "badges": [
      "Meetup",
      "Educational"
    ],
    "time": "5:00 PM",
    "location": "Salesforce Tower Chicago · 333 W Wolf Point Plaza, Chicago, IL 60654, USA",
    "vibeTags": [
      "Community",
      "Food",
      "Games",
      "Networking"
    ],
    "ctaHref": "https://www.werunitback.org/event-details/run-it-back-chicago-the-all-star-fundraising-gala",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.threads.com/@lexismickens/post/DaQXKMkDhPN/good-morning-thriends-its-wednesday-and-you-know-what-also-starts-with-a-w-our/",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-58",
    "festival": "wnba-all-star-weekend",
    "day": "thursday",
    "dayDate": "2026-07-23",
    "dayLabel": "Thursday",
    "name": "The Green Room — a WNBA All-Star Weekend activation",
    "organizer": "Social Market Agency",
    "types": [
      "meetup"
    ],
    "vibesRaw": "community food games networking",
    "free": false,
    "price": "$28.00",
    "badges": [
      "Meetup"
    ],
    "time": "4:00 PM",
    "location": "Level Sporting Club · 3343 N. Clark St, Chicago, IL 60657",
    "vibeTags": [
      "Community",
      "Food",
      "Games",
      "Networking"
    ],
    "ctaHref": "https://app.promotix.com/events/details/The-Green-Room-tickets?utm_source=threads&utm_medium=social&utm_content=link_in_bio",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.threads.com/@mov.bri/post/DaMHI0JDd23/introducing-the-green-room-a-wnba-all-star-weekend-activation-presented-by/",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-59",
    "festival": "wnba-all-star-weekend",
    "day": "friday",
    "dayDate": "2026-07-24",
    "dayLabel": "Friday",
    "name": "Full Court Salon- an exploration of beauty, identity, and women’s basketball",
    "organizer": "@leagueoftheirownchi + @sweetteasbeautysupply.la + JD Sports US",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "badges": [],
    "time": "",
    "location": "The Chi",
    "vibeTags": [],
    "ctaHref": "https://www.instagram.com/p/DaQR9MTRP9X/?hl=en",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-60",
    "festival": "wnba-all-star-weekend",
    "day": "saturday",
    "dayDate": "2026-07-25",
    "dayLabel": "Saturday",
    "name": "Full Court Salon- an exploration of beauty, identity, and women’s basketball",
    "organizer": "@leagueoftheirownchi + @sweetteasbeautysupply.la + JD Sports US",
    "types": [],
    "vibesRaw": "",
    "free": false,
    "badges": [],
    "time": "",
    "location": "The Chi",
    "vibeTags": [],
    "ctaHref": "https://www.instagram.com/p/DaQR9MTRP9X/?hl=en",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-day-party",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-61",
    "festival": "wnba-all-star-weekend",
    "day": "thursday",
    "dayDate": "2026-07-23",
    "dayLabel": "Thursday",
    "name": "LESBIAN ALL STAR WEEKEND: Thursday: Exclusive Welcome WLW Mixer",
    "organizer": "@blissxsundays",
    "types": [
      "meetup"
    ],
    "vibesRaw": "chill networking community food groove games grown & sexy",
    "free": false,
    "price": "$27.00",
    "badges": [
      "Meetup"
    ],
    "time": "5:00 PM",
    "location": "Nobody's Darling · 1744 W Balmoral Ave, Chicago, IL 60640",
    "vibeTags": [
      "Chill",
      "Networking",
      "Community",
      "Food",
      "Groove",
      "Games",
      "Grown & Sexy"
    ],
    "ctaHref": "https://speakeasygo.com/event/EVE-LNAFY7?t=BlissSundays",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "flyerUrl": "https://www.instagram.com/p/DZ8uSc1O2L0/?hl=en",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-62",
    "festival": "wnba-all-star-weekend",
    "day": "friday",
    "dayDate": "2026-07-24",
    "dayLabel": "Friday",
    "name": "LESBIAN ALL STAR WEEKEND: Friday: Sneaker Ball",
    "organizer": "@blissxsundays",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt community ass shaking groove grown & sexy",
    "free": false,
    "price": "$43.00",
    "badges": [
      "After Dark"
    ],
    "time": "9:00 PM",
    "location": "Hubbard Inn · 110 W Hubbard St, Chicago, IL 60654",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Groove",
      "Grown & Sexy"
    ],
    "ctaHref": "https://speakeasygo.com/event/EVE-LNAFY7?t=BlissSundays",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "flyerUrl": "https://www.instagram.com/p/DZ8uSc1O2L0/?hl=en",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-63",
    "festival": "wnba-all-star-weekend",
    "day": "saturday",
    "dayDate": "2026-07-25",
    "dayLabel": "Saturday",
    "name": "LESBIAN ALL STAR WEEKEND: Saturday: Walk/Run Club",
    "organizer": "@blissxsundays",
    "types": [
      "outdoors-hangout",
      "meetup"
    ],
    "vibesRaw": "community wellness",
    "free": true,
    "price": "Free",
    "badges": [
      "Outdoors Hangout",
      "Meetup",
      "Free"
    ],
    "time": "10:00 AM",
    "location": "Tunnel · 151 W Kinzie St, Chicago, IL 60654",
    "vibeTags": [
      "Community",
      "Wellness"
    ],
    "ctaHref": "https://speakeasygo.com/event/EVE-LNAFY7?t=BlissSundays",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-outdoors-hangout",
    "flyerUrl": "https://www.instagram.com/p/DZ8uSc1O2L0/?hl=en",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-64",
    "festival": "wnba-all-star-weekend",
    "day": "sunday",
    "dayDate": "2026-07-26",
    "dayLabel": "Sunday",
    "name": "LESBIAN ALL STAR WEEKEND: Sunday: Brunch Day Party",
    "organizer": "@blissxsundays",
    "types": [
      "brunch",
      "day-party"
    ],
    "vibesRaw": "flirt community grown & sexy groove open bar food",
    "free": false,
    "price": "$27.00",
    "badges": [
      "Brunch",
      "Day Party"
    ],
    "time": "9:00 PM",
    "location": "Dime Chi · 2263 N Lincoln Ave, Chicago, IL 60614",
    "vibeTags": [
      "Flirt",
      "Community",
      "Grown & Sexy",
      "Groove",
      "Open Bar",
      "Food"
    ],
    "ctaHref": "https://speakeasygo.com/event/EVE-LNAFY7?t=BlissSundays",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-brunch",
    "flyerUrl": "https://www.instagram.com/p/DZ8uSc1O2L0/?hl=en",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-65",
    "festival": "wnba-all-star-weekend",
    "day": "thursday",
    "dayDate": "2026-07-23",
    "dayLabel": "Thursday",
    "name": "LESBIAN ALL STAR WEEKEND: ALL ACCESS PASS",
    "organizer": "@blissxsundays",
    "types": [
      "brunch",
      "day-party",
      "after-dark",
      "meetup"
    ],
    "vibesRaw": "flirt community grown & sexy groove open bar food chill networking",
    "free": false,
    "price": "$105.00",
    "badges": [
      "Brunch",
      "Day Party",
      "After Dark",
      "Meetup"
    ],
    "time": "12:00 PM",
    "location": "Across locations",
    "vibeTags": [
      "Flirt",
      "Community",
      "Grown & Sexy",
      "Groove",
      "Open Bar",
      "Food",
      "Chill",
      "Networking"
    ],
    "ctaHref": "https://speakeasygo.com/event/EVE-LNAFY7?t=BlissSundays",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-brunch",
    "flyerUrl": "https://www.instagram.com/p/DZ8uSc1O2L0/?hl=en",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-66",
    "festival": "wnba-all-star-weekend",
    "day": "saturday",
    "dayDate": "2026-07-25",
    "dayLabel": "Saturday",
    "name": "LESBIAN WNBA ALL-STAR WEEKEND AFTER PARTY",
    "organizer": "Dirty Matriarch",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt community grown & sexy groove ass shaking",
    "free": false,
    "price": "$38.00",
    "badges": [
      "After Dark"
    ],
    "time": "9:00 PM",
    "location": "Joy District · 112 W Hubbard St, Chicago, 60654",
    "vibeTags": [
      "Flirt",
      "Community",
      "Grown & Sexy",
      "Groove",
      "Ass Shaking"
    ],
    "ctaHref": "https://speakeasygo.com/event/EVE-D205Y5?t=BlissSundays",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "flyerUrl": "https://www.instagram.com/p/DZ8uSc1O2L0/?hl=en",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-67",
    "festival": "wnba-all-star-weekend",
    "day": "friday",
    "dayDate": "2026-07-24",
    "dayLabel": "Friday",
    "name": "HOOP SOCIAL: THE COUSIN ALL-STAR WEEKEND LINK-UP",
    "organizer": "Hoops Social Chicago",
    "types": [
      "meetup"
    ],
    "vibesRaw": "community food games groove",
    "free": false,
    "price": "$65.00",
    "badges": [
      "Meetup"
    ],
    "time": "9:00 PM",
    "location": "Register to See Address",
    "vibeTags": [
      "Community",
      "Food",
      "Games",
      "Groove"
    ],
    "ctaHref": "https://luma.com/b3q2gqox?fbclid=PARlRTSASzmMBwZG9mAmV4dG4DYWVtAjEwAHNydGMGYXBwX2lkDzEyNDAyNDU3NDI4NzQxNAABp-3czDr_vEwpjd6YwwhhyKIkDdAqfbRkvbHPvWVKp-gAJ-LpBvqoSY4ADlF4_aem_R0sjPkMev9_pkB6_Wx0msg&utm_id=97760_v0_s00_e0_tv4",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-68",
    "festival": "wnba-all-star-weekend",
    "day": "friday",
    "dayDate": "2026-07-24",
    "dayLabel": "Friday",
    "name": "GloBall Life Connect - WNBA All Star Weekend",
    "organizer": "NYCH Gallery",
    "types": [
      "meetup"
    ],
    "vibesRaw": "community food games groove networking",
    "free": true,
    "price": "Free",
    "badges": [
      "Meetup",
      "Free"
    ],
    "time": "1:00 PM",
    "location": "NYCH Gallery · 2025 S Laflin St, Chicago, IL 60608, USA",
    "vibeTags": [
      "Community",
      "Food",
      "Games",
      "Groove",
      "Networking"
    ],
    "ctaHref": "https://www.globalllife.com/event-details/globall-life-connect-wnba-all-star-weekend?fbclid=PARlRTSASzme9wZG9mAmV4dG4DYWVtAjEwAHNydGMGYXBwX2lkDzEyNDAyNDU3NDI4NzQxNAABp8OCYmnR1xyx9NHEgfQDX1qZBWhIvsx1OnqcvENgs_VvnduQsd4d6mFutg2h_aem_KprqgPznq4CVQGKFbjg1OQ",
    "ctaLabel": "RSVP Free",
    "ctaButtonClass": "btn-free",
    "cardClass": "tp-meetup",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-69",
    "festival": "wnba-all-star-weekend",
    "day": "saturday",
    "dayDate": "2026-07-25",
    "dayLabel": "Saturday",
    "name": "WNBA ALL STAR DAY PARTY",
    "organizer": "Cut Cuz + Kels + Adonia",
    "types": [
      "meetup",
      "happy-hour"
    ],
    "vibesRaw": "chill flirt community food groove games",
    "free": false,
    "price": "$18.00",
    "badges": [
      "Meetup",
      "Happy Hour"
    ],
    "time": "2:00 PM",
    "location": "Chalet · 228 W Chicago Ave, Chicago, IL 60654, USA",
    "vibeTags": [
      "Chill",
      "Flirt",
      "Community",
      "Food",
      "Groove",
      "Games"
    ],
    "ctaHref": "https://posh.vip/e/wnba-all-star-day-party-725?fbclid=PARlRTSASzmptwZG9mAmV4dG4DYWVtAjEwAHNydGMGYXBwX2lkDzEyNDAyNDU3NDI4NzQxNAABpz6y5IJefkthFVLgCxeQDMsVAwCAyEUMS7Y_l3z9TnR8wuqFcJtebQxoIP3Q_aem_1uEyOurO5bIUvnw54ZtZUA",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-meetup",
    "city": "chicago"
  },
  {
    "id": "wnba-all-star-weekend-70",
    "festival": "wnba-all-star-weekend",
    "day": "saturday",
    "dayDate": "2026-07-25",
    "dayLabel": "Saturday",
    "name": "Love U Better , Rooftop R&B Party",
    "organizer": "Homie Lover Friends",
    "types": [
      "after-dark"
    ],
    "vibesRaw": "flirt community ass shaking grown & sexy groove",
    "free": false,
    "price": "$15.00",
    "badges": [
      "After Dark"
    ],
    "time": "8:00 PM",
    "location": "Azul · 1177 N Elston Ave\nChicago, IL 60642",
    "vibeTags": [
      "Flirt",
      "Community",
      "Ass Shaking",
      "Grown & Sexy",
      "Groove"
    ],
    "ctaHref": "https://events.eventnoire.com/e/homie-love-friends-the-mostly-r-b-party-69/tickets?utm_source=affiliate&utm_name=Sid-Bio&utm_campaign=Sid-Bio&utm_id=6a1b25e26d3c4f44a1ad00140a1e6089",
    "ctaLabel": "Get Tickets",
    "ctaButtonClass": "btn-p",
    "cardClass": "tp-after-dark",
    "city": "chicago"
  }
];
