/**
 * One-time / CI helper: parse legacy/index.html → src/data/events.generated.ts
 * Run: node scripts/extract-events.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { load } from 'cheerio';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const htmlPath = path.join(root, 'legacy', 'index.html');
const outPath = path.join(root, 'src', 'data', 'events.generated.ts');

const html = fs.readFileSync(htmlPath, 'utf8');
const $ = load(html);

function slugify(s) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 80) || 'event';
}

/** Keep in sync with `decodeHtmlEntities` in src/lib/decodeHtmlEntities.ts */
function decodeHtmlEntities(text) {
  if (!text.includes('&')) return text;
  let out = text;
  for (let i = 0; i < 8; i++) {
    const next = out
      .replace(/&#x([0-9a-f]{1,6});/gi, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
      .replace(/&#([0-9]{1,7});/g, (_, dec) => String.fromCodePoint(parseInt(dec, 10)))
      .replace(/&nbsp;/gi, ' ')
      .replace(/&amp;/gi, '&')
      .replace(/&lt;/gi, '<')
      .replace(/&gt;/gi, '>')
      .replace(/&quot;/gi, '"')
      .replace(/&apos;/gi, "'");
    if (next === out) break;
    out = next;
  }
  return out.replace(/\u00a0/g, ' ');
}

/** Keep in sync with `shouldHideDiscountCode` in src/lib/parseDiscountDisplay.ts */
function shouldHideDiscountCode(raw) {
  return /\bpending\b/i.test(decodeHtmlEntities(String(raw)).trim());
}

const events = [];

$('.event-card').each((_, el) => {
  const $card = $(el);
  const types = ($card.attr('data-types') || '')
    .split(/\s+/)
    .map((t) => t.trim())
    .filter(Boolean);
  const vibesRaw = ($card.attr('data-vibes') || '')
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .trim();
  const free = $card.attr('data-free') === 'true';
  const $section = $card.closest('.day-section');
  const day = ($section.attr('data-day') || '').toLowerCase();
  const dayLabel = $section.find('.day-label').first().text().trim() || day;

  const name = $card.find('.event-name').first().text().trim();
  const organizer = $card.find('.event-organizer').first().text().trim() || undefined;

  const badges = $card
    .find('.event-badges .badge')
    .map((_, b) => $(b).text().trim())
    .get();

  const pills = $card
    .find('.event-meta .meta-pill')
    .map((_, p) => $(p).text().replace(/\s+/g, ' ').trim())
    .get();

  let time = '';
  let location = '';
  if (pills.length >= 1) time = pills[0];
  if (pills.length >= 2) location = pills[1];

  const vibeTags = $card
    .find('.event-vibes .vibes-tag')
    .map((_, v) => $(v).text().trim())
    .get();

  const $btn = $card.find('.event-action a.btn').first();
  const ctaHref = $btn.attr('href') || '';
  const ctaLabel = $btn.text().replace(/→/g, '').replace(/\s+/g, ' ').trim() || 'Link';
  const btnClass = ($btn.attr('class') || '').split(/\s+/).find((c) => c.startsWith('btn-')) || 'btn-p';

  const $discount = $card.find('.event-action .discount-code').first();
  let discountCode;
  if ($discount.length) {
    const html = $discount.html() ?? '';
    const plain = html
      .replace(/<br\s*\/?>/gi, ' ')
      .replace(/<\/p>/gi, ' ')
      .replace(/<[^>]+>/g, ' ');
    discountCode = decodeHtmlEntities(plain.replace(/\s+/g, ' ').trim()) || undefined;
    if (discountCode && shouldHideDiscountCode(discountCode)) discountCode = undefined;
  }

  const tpClass = ($card.attr('class') || '').split(/\s+/).find((c) => c.startsWith('tp-')) || 'tp-day-party';

  const id = slugify(`${day}-${name}`) + '-' + events.length;

  events.push({
    id,
    day,
    dayLabel,
    name,
    organizer,
    types,
    vibesRaw,
    free,
    badges,
    time,
    location,
    vibeTags,
    ctaHref,
    ctaLabel,
    ctaButtonClass: btnClass,
    cardClass: tpClass,
    ...(discountCode ? { discountCode } : {}),
  });
});

const file = `/* eslint-disable */
// Auto-generated by scripts/extract-events.mjs — do not edit by hand.
import type { PrideEvent } from '../types/event';

export const generatedEvents: PrideEvent[] = ${JSON.stringify(events, null, 2)};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, file);
console.log('Wrote', outPath, 'events:', events.length);
