/**
 * Sync Google Sheets `events` tab -> src/data/events.generated.ts
 * Run: npm run sync-events
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { fetchSheetEvents } from '../src/data/googleSheets.ts';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const envPath = path.join(root, '.env');
const outPath = path.join(root, 'src', 'data', 'events.generated.ts');

function loadDotEnv() {
  if (!fs.existsSync(envPath)) return;

  const lines = fs.readFileSync(envPath, 'utf8').split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const equalsIndex = trimmed.indexOf('=');
    if (equalsIndex < 0) continue;

    const key = trimmed.slice(0, equalsIndex).trim();
    const rawValue = trimmed.slice(equalsIndex + 1).trim();
    const value = rawValue.replace(/^['"]|['"]$/g, '');
    if (key && process.env[key] === undefined) process.env[key] = value;
  }
}

loadDotEnv();

const events = await fetchSheetEvents();

const file = `/* eslint-disable */
// Auto-generated by scripts/sync-events.ts from the Google Sheets events tab. Do not edit by hand.
import type { PrideEvent } from '../types/event';

export const generatedEvents: PrideEvent[] = ${JSON.stringify(events, null, 2)};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, file);

console.log(`Wrote ${path.relative(root, outPath)} events: ${events.length}`);

for (const event of events.filter((item) => /fight or flight|mary bowman/i.test(item.name))) {
  console.log(`  ${event.dayLabel} · ${event.time} · ${event.name}`);
}
