/**
 * Sync Google Sheets festival tabs -> src/data/festivals/*.generated.ts
 * Run: npm run sync-events
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { ENABLED_FESTIVALS } from '../src/constants/festivals.ts';
import { fetchFestivalSheetEvents } from '../src/data/googleSheets.ts';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const envPath = path.join(root, '.env');
const festivalsDir = path.join(root, 'src', 'data', 'festivals');

function loadDotEnv() {
  if (!fs.existsSync(envPath)) return;

  const lines = fs.readFileSync(envPath, 'utf8').split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const equalsIndex = trimmed.indexOf('=');
    if (equalsIndex < 0) continue;

    const key = trimmed.slice(0, equalsIndex).trim();
    const rawValue = trimmed.slice(equalsIndex + 1).trim();
    const value = rawValue.replace(/^['"]|['"]$/g, '');
    if (key && process.env[key] === undefined) process.env[key] = value;
  }
}

loadDotEnv();

fs.mkdirSync(festivalsDir, { recursive: true });

let totalEvents = 0;
const syncedByFestival: Record<string, Awaited<ReturnType<typeof fetchFestivalSheetEvents>>> = {};

for (const festival of ENABLED_FESTIVALS) {
  const events = await fetchFestivalSheetEvents(festival.id);
  syncedByFestival[festival.id] = events;
  const outPath = path.join(festivalsDir, `${festival.id}.generated.ts`);
  const file = `/* eslint-disable */
// Auto-generated by scripts/sync-events.ts from the Google Sheets ${festival.sheetName} tab. Do not edit by hand.
import type { PrideEvent } from '../../types/event';

export const generatedEvents: PrideEvent[] = ${JSON.stringify(events, null, 2)};
`;

  fs.writeFileSync(outPath, file);
  totalEvents += events.length;
  console.log(`Wrote ${path.relative(root, outPath)} events: ${events.length}`);
}

if (totalEvents === 0) {
  throw new Error('No valid events were found in any festival sheet.');
}

console.log(`Total events synced: ${totalEvents}`);

for (const festival of ENABLED_FESTIVALS) {
  const events = syncedByFestival[festival.id] ?? [];
  for (const event of events.filter((item) => /fight or flight|mary bowman/i.test(item.name))) {
    console.log(`  [${festival.id}] ${event.dayLabel} · ${event.time} · ${event.name}`);
  }
}
