/* eslint-disable */
// Auto-generated by scripts/sync-beauty.mjs from the Google Sheets Business tab. Do not edit by hand.
import type { BeautyItem } from '../types/beauty';

export const generatedBeautyItems: BeautyItem[] = [
  {
    "id": "hair-salon-girls-next-door-on-the-runnn-0",
    "name": "Girls Next Door + On the RuNNN",
    "businessType": "Hair Salon",
    "fields": [
      {
        "key": "businessname",
        "label": "Business Name",
        "value": "Girls Next Door + On the RuNNN"
      },
      {
        "key": "businesstype",
        "label": "Business Type",
        "value": "Hair Salon"
      },
      {
        "key": "services",
        "label": "Services",
        "value": "Hair Extension + Wig Designs"
      },
      {
        "key": "city",
        "label": "City",
        "value": "DMV"
      },
      {
        "key": "neighborhood",
        "label": "Neighborhood",
        "value": "Silver Spring"
      },
      {
        "key": "contactinfo",
        "label": "Contact Info",
        "value": "https://www.ontherunnnsalon.com/",
        "href": "https://www.ontherunnnsalon.com/"
      },
      {
        "key": "discountcode",
        "label": "Discount Code?",
        "value": "GIRLYPOP"
      },
      {
        "key": "promo",
        "label": "Promo",
        "value": "$15 off services $350 and above"
      },
      {
        "key": "bookingsite",
        "label": "Booking Site",
        "value": "https://girlnextdoorhair.com/products/bundle-sale",
        "href": "https://girlnextdoorhair.com/products/bundle-sale"
      },
      {
        "key": "owner",
        "label": "Owner",
        "value": "Quarita"
      },
      {
        "key": "travels",
        "label": "Travels?",
        "value": "No"
      }
    ],
    "primaryHref": "https://girlnextdoorhair.com/products/bundle-sale"
  },
  {
    "id": "hair-salon-sugar-braids-1",
    "name": "Sugar Braids",
    "businessType": "Hair Salon",
    "fields": [
      {
        "key": "businessname",
        "label": "Business Name",
        "value": "Sugar Braids"
      },
      {
        "key": "businesstype",
        "label": "Business Type",
        "value": "Hair Salon"
      },
      {
        "key": "services",
        "label": "Services",
        "value": "Braids, Cornrows, French Curls, Natural Styles + Twists"
      },
      {
        "key": "city",
        "label": "City",
        "value": "DMV"
      },
      {
        "key": "neighborhood",
        "label": "Neighborhood",
        "value": "Silver Spring"
      },
      {
        "key": "contactinfo",
        "label": "Contact Info",
        "value": "sugarbraid@gmail.com",
        "href": "mailto:sugarbraid@gmail.com"
      },
      {
        "key": "discountcode",
        "label": "Discount Code?",
        "value": "PRIDEBRAID26\nMention in person"
      },
      {
        "key": "promo",
        "label": "Promo",
        "value": "15% off"
      },
      {
        "key": "bookingsite",
        "label": "Booking Site",
        "value": "https://www.sugarbraid.com/",
        "href": "https://www.sugarbraid.com/"
      },
      {
        "key": "owner",
        "label": "Owner",
        "value": "Gaelle Laure Djeukam"
      },
      {
        "key": "travels",
        "label": "Travels?",
        "value": "No"
      }
    ],
    "primaryHref": "https://www.sugarbraid.com/"
  },
  {
    "id": "brows-brow-d-2",
    "name": "Brow'd",
    "businessType": "Brows",
    "fields": [
      {
        "key": "businessname",
        "label": "Business Name",
        "value": "Brow'd"
      },
      {
        "key": "businesstype",
        "label": "Business Type",
        "value": "Brows"
      },
      {
        "key": "services",
        "label": "Services",
        "value": "Brow Lamination + Tint, Lips + Chin Wax"
      },
      {
        "key": "city",
        "label": "City",
        "value": "DC"
      },
      {
        "key": "neighborhood",
        "label": "Neighborhood",
        "value": "The Wharf"
      },
      {
        "key": "contactinfo",
        "label": "Contact Info",
        "value": "https://browd.glossgenius.com/contact",
        "href": "https://browd.glossgenius.com/contact"
      },
      {
        "key": "discountcode",
        "label": "Discount Code?",
        "value": "Select \"SQW Pride\" service"
      },
      {
        "key": "promo",
        "label": "Promo",
        "value": "20% off"
      },
      {
        "key": "bookingsite",
        "label": "Booking Site",
        "value": "https://browd.glossgenius.com/?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGnja_bXAuLQJvNMGleW2OdargNUyYNAInkPlgdrDqCUF1dBw5uW7IVDSSqj-o_aem_LRRV7D8GMoHE4xuKao4LTA",
        "href": "https://browd.glossgenius.com/?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGnja_bXAuLQJvNMGleW2OdargNUyYNAInkPlgdrDqCUF1dBw5uW7IVDSSqj-o_aem_LRRV7D8GMoHE4xuKao4LTA"
      },
      {
        "key": "owner",
        "label": "Owner",
        "value": "A'Jahna Chapman"
      },
      {
        "key": "travels",
        "label": "Travels?",
        "value": "No"
      }
    ],
    "primaryHref": "https://browd.glossgenius.com/?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGnja_bXAuLQJvNMGleW2OdargNUyYNAInkPlgdrDqCUF1dBw5uW7IVDSSqj-o_aem_LRRV7D8GMoHE4xuKao4LTA"
  },
  {
    "id": "acupuncture-acu-with-naja-3",
    "name": "Acu with Naja",
    "businessType": "Acupuncture",
    "fields": [
      {
        "key": "businessname",
        "label": "Business Name",
        "value": "Acu with Naja"
      },
      {
        "key": "businesstype",
        "label": "Business Type",
        "value": "Acupuncture"
      },
      {
        "key": "services",
        "label": "Services",
        "value": "Acupuncture"
      },
      {
        "key": "city",
        "label": "City",
        "value": "Baltimore"
      },
      {
        "key": "neighborhood",
        "label": "Neighborhood",
        "value": "TBD"
      },
      {
        "key": "contactinfo",
        "label": "Contact Info",
        "value": "DM to book"
      },
      {
        "key": "discountcode",
        "label": "Discount Code?",
        "value": "Mention SQW in DM to redeem"
      },
      {
        "key": "promo",
        "label": "Promo",
        "value": "20% off first session"
      },
      {
        "key": "bookingsite",
        "label": "Booking Site",
        "value": "https://www.instagram.com/acuwithnaja?igsh=MWVjOW51ZjJqMm5iYQ==",
        "href": "https://www.instagram.com/acuwithnaja?igsh=MWVjOW51ZjJqMm5iYQ=="
      },
      {
        "key": "owner",
        "label": "Owner",
        "value": "Naja"
      },
      {
        "key": "travels",
        "label": "Travels?",
        "value": "Yes"
      }
    ],
    "primaryHref": "https://www.instagram.com/acuwithnaja?igsh=MWVjOW51ZjJqMm5iYQ=="
  },
  {
    "id": "barber-adaptable-creationz-4",
    "name": "Adaptable Creationz",
    "businessType": "Barber",
    "fields": [
      {
        "key": "businessname",
        "label": "Business Name",
        "value": "Adaptable Creationz"
      },
      {
        "key": "businesstype",
        "label": "Business Type",
        "value": "Barber"
      },
      {
        "key": "services",
        "label": "Services",
        "value": "Haircuts, Locs, Natural Braids/Twists"
      },
      {
        "key": "city",
        "label": "City",
        "value": "Baltimore"
      },
      {
        "key": "neighborhood",
        "label": "Neighborhood",
        "value": "TBD"
      },
      {
        "key": "contactinfo",
        "label": "Contact Info",
        "value": "https://www.adaptablecreationz.com/contact-us",
        "href": "https://www.adaptablecreationz.com/contact-us"
      },
      {
        "key": "discountcode",
        "label": "Discount Code?",
        "value": "#SQW"
      },
      {
        "key": "promo",
        "label": "Promo",
        "value": "20% off until 6/30 (starts 5/15)"
      },
      {
        "key": "bookingsite",
        "label": "Booking Site",
        "value": "https://www.adaptablecreationz.com/?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAb21jcARx5AdleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA81NjcwNjczNDMzNTI0MjcAAaePj-ai_4f6hBYWtQ4FHgw0njBjCciYOoJW9jc46DXSHl_WGD0f6sb3kbG2XA_aem_RmzObZMizZIAWs4TrlccCQ",
        "href": "https://www.adaptablecreationz.com/?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAb21jcARx5AdleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA81NjcwNjczNDMzNTI0MjcAAaePj-ai_4f6hBYWtQ4FHgw0njBjCciYOoJW9jc46DXSHl_WGD0f6sb3kbG2XA_aem_RmzObZMizZIAWs4TrlccCQ"
      },
      {
        "key": "owner",
        "label": "Owner",
        "value": "Lydia Gulley"
      },
      {
        "key": "travels",
        "label": "Travels?",
        "value": "Yes"
      }
    ],
    "primaryHref": "https://www.adaptablecreationz.com/?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAb21jcARx5AdleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA81NjcwNjczNDMzNTI0MjcAAaePj-ai_4f6hBYWtQ4FHgw0njBjCciYOoJW9jc46DXSHl_WGD0f6sb3kbG2XA_aem_RmzObZMizZIAWs4TrlccCQ"
  },
  {
    "id": "shop-loni-s-lp-baltimore-s-finest-vinyls-cd-s-11",
    "name": "Loni's LP: Baltimore's Finest Vinyls & CD's",
    "businessType": "Shop",
    "fields": [
      {
        "key": "businessname",
        "label": "Business Name",
        "value": "Loni's LP: Baltimore's Finest Vinyls & CD's"
      },
      {
        "key": "businesstype",
        "label": "Business Type",
        "value": "Shop"
      },
      {
        "key": "services",
        "label": "Services",
        "value": "Vinyl Shop"
      },
      {
        "key": "city",
        "label": "City",
        "value": "Baltimore"
      },
      {
        "key": "neighborhood",
        "label": "Neighborhood",
        "value": "Baltimore"
      },
      {
        "key": "contactinfo",
        "label": "Contact Info",
        "value": "loniboo.content@gmail.com",
        "href": "mailto:loniboo.content@gmail.com"
      },
      {
        "key": "discountcode",
        "label": "Discount Code?",
        "value": "BPride26"
      },
      {
        "key": "promo",
        "label": "Promo",
        "value": "10% off"
      },
      {
        "key": "bookingsite",
        "label": "Booking Site",
        "value": "https://lonislps.com/",
        "href": "https://lonislps.com/"
      },
      {
        "key": "owner",
        "label": "Owner",
        "value": "NaLoni Scott"
      }
    ],
    "primaryHref": "https://lonislps.com/"
  },
  {
    "id": "barber-osmosis-combs-12",
    "name": "Osmosis Combs",
    "businessType": "Barber",
    "fields": [
      {
        "key": "businessname",
        "label": "Business Name",
        "value": "Osmosis Combs"
      },
      {
        "key": "businesstype",
        "label": "Business Type",
        "value": "Barber"
      },
      {
        "key": "services",
        "label": "Services",
        "value": "Hair"
      },
      {
        "key": "city",
        "label": "City",
        "value": "Pikesville, MD"
      },
      {
        "key": "neighborhood",
        "label": "Neighborhood",
        "value": "Pikesville"
      },
      {
        "key": "igpage",
        "label": "IG Page",
        "value": "https://www.instagram.com/osmosiscombs/",
        "href": "https://www.instagram.com/osmosiscombs/"
      },
      {
        "key": "vibestype",
        "label": "Vibes Type",
        "value": "Chill"
      },
      {
        "key": "communityfavoritefor",
        "label": "Community Favorite For",
        "value": "Barber"
      },
      {
        "key": "contactinfo",
        "label": "Contact Info",
        "value": "https://www.instagram.com/osmosiscombs/",
        "href": "https://www.instagram.com/osmosiscombs/"
      },
      {
        "key": "discountcode",
        "label": "Discount Code?",
        "value": "Mention Pride at appt"
      },
      {
        "key": "promo",
        "label": "Promo",
        "value": "Complimentary scalp refresh service"
      },
      {
        "key": "bookingsite",
        "label": "Booking Site",
        "value": "https://booksy.com/en-us/119326_rae-barber_barber-shop_126442_pikesville",
        "href": "https://booksy.com/en-us/119326_rae-barber_barber-shop_126442_pikesville"
      },
      {
        "key": "owner",
        "label": "Owner",
        "value": "Rae"
      },
      {
        "key": "travels",
        "label": "Travels?",
        "value": "No"
      }
    ],
    "primaryHref": "https://booksy.com/en-us/119326_rae-barber_barber-shop_126442_pikesville"
  },
  {
    "id": "salon-anumee-aesthetics-13",
    "name": "Anumee Aesthetics",
    "businessType": "Salon",
    "fields": [
      {
        "key": "businessname",
        "label": "Business Name",
        "value": "Anumee Aesthetics"
      },
      {
        "key": "businesstype",
        "label": "Business Type",
        "value": "Salon"
      },
      {
        "key": "services",
        "label": "Services",
        "value": "Laser|Peels|Facials|Botox|Filler & More"
      },
      {
        "key": "city",
        "label": "City",
        "value": "Ellicott City, Maryland"
      },
      {
        "key": "neighborhood",
        "label": "Neighborhood",
        "value": "Ellicott City"
      },
      {
        "key": "vibestype",
        "label": "Vibes Type",
        "value": "Chill"
      },
      {
        "key": "contactinfo",
        "label": "Contact Info",
        "value": "https://www.instagram.com/anumeeaesthetics/",
        "href": "https://www.instagram.com/anumeeaesthetics/"
      },
      {
        "key": "discountcode",
        "label": "Discount Code?",
        "value": "Mention SQW at appt"
      },
      {
        "key": "promo",
        "label": "Promo",
        "value": "15% off all our services to new clients"
      },
      {
        "key": "bookingsite",
        "label": "Booking Site",
        "value": "https://anumeeaesthetics.myaestheticrecord.com/online-booking?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnqSSejw4jDHKpy4Sx5dpbS0ovsfQj0ciECy_UnablmwihEozfzaPe00JuEVA_aem_gE5Ip_A30opFbzDCVCa-SA",
        "href": "https://anumeeaesthetics.myaestheticrecord.com/online-booking?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnqSSejw4jDHKpy4Sx5dpbS0ovsfQj0ciECy_UnablmwihEozfzaPe00JuEVA_aem_gE5Ip_A30opFbzDCVCa-SA"
      },
      {
        "key": "travels",
        "label": "Travels?",
        "value": "No"
      }
    ],
    "primaryHref": "https://anumeeaesthetics.myaestheticrecord.com/online-booking?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPOTM2NjE5NzQzMzkyNDU5AAGnqSSejw4jDHKpy4Sx5dpbS0ovsfQj0ciECy_UnablmwihEozfzaPe00JuEVA_aem_gE5Ip_A30opFbzDCVCa-SA"
  }
];
