/* eslint-disable */
// Auto-generated by scripts/sync-beauty.mjs from the Google Sheets beauty tab. Do not edit by hand.
import type { BeautyItem } from '../types/beauty';

export const generatedBeautyItems: BeautyItem[] = [
  {
    "id": "hair-salon-girls-next-door-on-the-runnn-0",
    "name": "Girls Next Door + On the RuNNN",
    "businessType": "Hair Salon",
    "fields": [
      {
        "key": "businessname",
        "label": "Business Name",
        "value": "Girls Next Door + On the RuNNN"
      },
      {
        "key": "businesstype",
        "label": "Business Type",
        "value": "Hair Salon"
      },
      {
        "key": "services",
        "label": "Services",
        "value": "Hair Extension + Wig Designs"
      },
      {
        "key": "contactinfo",
        "label": "Contact Info",
        "value": "https://www.ontherunnnsalon.com/",
        "href": "https://www.ontherunnnsalon.com/"
      },
      {
        "key": "discountcode",
        "label": "Discount Code?",
        "value": "GIRLYPOP"
      },
      {
        "key": "promo",
        "label": "Promo",
        "value": "$15 off services $350 and above"
      },
      {
        "key": "bookingsite",
        "label": "Booking Site",
        "value": "https://girlnextdoorhair.com/products/bundle-sale",
        "href": "https://girlnextdoorhair.com/products/bundle-sale"
      },
      {
        "key": "owner",
        "label": "Owner",
        "value": "Quarita"
      },
      {
        "key": "travels",
        "label": "Travels?",
        "value": "No"
      }
    ],
    "primaryHref": "https://girlnextdoorhair.com/products/bundle-sale"
  },
  {
    "id": "brows-brow-d-2",
    "name": "Brow'd",
    "businessType": "Brows",
    "fields": [
      {
        "key": "businessname",
        "label": "Business Name",
        "value": "Brow'd"
      },
      {
        "key": "businesstype",
        "label": "Business Type",
        "value": "Brows"
      },
      {
        "key": "services",
        "label": "Services",
        "value": "Brow Lamination + Tint, Lips + Chin Wax"
      },
      {
        "key": "contactinfo",
        "label": "Contact Info",
        "value": "https://browd.glossgenius.com/contact",
        "href": "https://browd.glossgenius.com/contact"
      },
      {
        "key": "discountcode",
        "label": "Discount Code?",
        "value": "Select \"SQW Pride\" service"
      },
      {
        "key": "promo",
        "label": "Promo",
        "value": "20% off"
      },
      {
        "key": "bookingsite",
        "label": "Booking Site",
        "value": "https://browd.glossgenius.com/?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGnja_bXAuLQJvNMGleW2OdargNUyYNAInkPlgdrDqCUF1dBw5uW7IVDSSqj-o_aem_LRRV7D8GMoHE4xuKao4LTA",
        "href": "https://browd.glossgenius.com/?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGnja_bXAuLQJvNMGleW2OdargNUyYNAInkPlgdrDqCUF1dBw5uW7IVDSSqj-o_aem_LRRV7D8GMoHE4xuKao4LTA"
      },
      {
        "key": "owner",
        "label": "Owner",
        "value": "A'Jahna Chapman"
      },
      {
        "key": "travels",
        "label": "Travels?",
        "value": "No"
      }
    ],
    "primaryHref": "https://browd.glossgenius.com/?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQMMjU2MjgxMDQwNTU4AAGnja_bXAuLQJvNMGleW2OdargNUyYNAInkPlgdrDqCUF1dBw5uW7IVDSSqj-o_aem_LRRV7D8GMoHE4xuKao4LTA"
  },
  {
    "id": "acupuncture-acu-with-naja-3",
    "name": "Acu with Naja",
    "businessType": "Acupuncture",
    "fields": [
      {
        "key": "businessname",
        "label": "Business Name",
        "value": "Acu with Naja"
      },
      {
        "key": "businesstype",
        "label": "Business Type",
        "value": "Acupuncture"
      },
      {
        "key": "services",
        "label": "Services",
        "value": "Acupuncture"
      },
      {
        "key": "contactinfo",
        "label": "Contact Info",
        "value": "DM to book"
      },
      {
        "key": "discountcode",
        "label": "Discount Code?",
        "value": "Mention SQW in DM to redeem"
      },
      {
        "key": "promo",
        "label": "Promo",
        "value": "20% off first session"
      },
      {
        "key": "bookingsite",
        "label": "Booking Site",
        "value": "https://www.instagram.com/acuwithnaja?igsh=MWVjOW51ZjJqMm5iYQ==",
        "href": "https://www.instagram.com/acuwithnaja?igsh=MWVjOW51ZjJqMm5iYQ=="
      },
      {
        "key": "owner",
        "label": "Owner",
        "value": "Naja"
      },
      {
        "key": "travels",
        "label": "Travels?",
        "value": "Yes"
      }
    ],
    "primaryHref": "https://www.instagram.com/acuwithnaja?igsh=MWVjOW51ZjJqMm5iYQ=="
  },
  {
    "id": "barber-adaptable-creationz-9",
    "name": "Adaptable Creationz",
    "businessType": "Barber",
    "fields": [
      {
        "key": "businessname",
        "label": "Business Name",
        "value": "Adaptable Creationz"
      },
      {
        "key": "businesstype",
        "label": "Business Type",
        "value": "Barber"
      },
      {
        "key": "services",
        "label": "Services",
        "value": "Haircuts, Locs, Natural Braids/Twists"
      },
      {
        "key": "contactinfo",
        "label": "Contact Info",
        "value": "https://www.adaptablecreationz.com/contact-us",
        "href": "https://www.adaptablecreationz.com/contact-us"
      },
      {
        "key": "discountcode",
        "label": "Discount Code?",
        "value": "SQW"
      },
      {
        "key": "promo",
        "label": "Promo",
        "value": "20% off until 6/30"
      },
      {
        "key": "bookingsite",
        "label": "Booking Site",
        "value": "https://www.adaptablecreationz.com/?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAb21jcARx5AdleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA81NjcwNjczNDMzNTI0MjcAAaePj-ai_4f6hBYWtQ4FHgw0njBjCciYOoJW9jc46DXSHl_WGD0f6sb3kbG2XA_aem_RmzObZMizZIAWs4TrlccCQ",
        "href": "https://www.adaptablecreationz.com/?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAb21jcARx5AdleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA81NjcwNjczNDMzNTI0MjcAAaePj-ai_4f6hBYWtQ4FHgw0njBjCciYOoJW9jc46DXSHl_WGD0f6sb3kbG2XA_aem_RmzObZMizZIAWs4TrlccCQ"
      },
      {
        "key": "owner",
        "label": "Owner",
        "value": "Lydia Gulley"
      },
      {
        "key": "travels",
        "label": "Travels?",
        "value": "Yes"
      }
    ],
    "primaryHref": "https://www.adaptablecreationz.com/?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAb21jcARx5AdleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA81NjcwNjczNDMzNTI0MjcAAaePj-ai_4f6hBYWtQ4FHgw0njBjCciYOoJW9jc46DXSHl_WGD0f6sb3kbG2XA_aem_RmzObZMizZIAWs4TrlccCQ"
  }
];
